[package]
name = "pg_swarm"
version = "0.3.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Distributed task processing swarm for PostgreSQL"

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "pgrx_embed_pg_swarm"
path = "src/bin/pgrx_embed.rs"

[features]
default = ["pg18"]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14", "pg_bgworker/pg14"]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15", "pg_bgworker/pg15"]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16", "pg_bgworker/pg16"]
pg17 = ["pgrx/pg17", "pgrx-tests/pg17", "pg_bgworker/pg17"]
pg18 = ["pgrx/pg18", "pgrx-tests/pg18", "pg_bgworker/pg18"]
pg_test = []

[dependencies]
pg_bgworker = { git = "https://github.com/matroidbe/pg_extensions", default-features = false }
pgrx.workspace = true
serde_json.workspace = true
libc = "0.2"

[dev-dependencies]
toml.workspace = true
pgrx-tests.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
tokio-postgres.workspace = true
serde_json.workspace = true
