/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:41
-- bootstrap

-- Bucket registry
CREATE TABLE pgs3.buckets (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_buckets_name ON pgs3.buckets (name);

-- Object metadata
CREATE TABLE pgs3.objects (
    id BIGSERIAL PRIMARY KEY,
    bucket_id BIGINT NOT NULL REFERENCES pgs3.buckets(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    content_hash TEXT NOT NULL,
    content_type TEXT NOT NULL DEFAULT 'application/octet-stream',
    storage_path TEXT NOT NULL,
    custom_metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_bucket_key UNIQUE (bucket_id, key)
);

-- Fast lookup by bucket + key (primary access pattern)
CREATE UNIQUE INDEX idx_objects_bucket_key ON pgs3.objects (bucket_id, key);

-- Prefix listing (LIST operations)
CREATE INDEX idx_objects_bucket_key_prefix ON pgs3.objects (bucket_id, key text_pattern_ops);

-- Content dedup reference check
CREATE INDEX idx_objects_content_hash ON pgs3.objects (content_hash);

-- Aggressive autovacuum for high-write objects table
ALTER TABLE pgs3.objects SET (
    autovacuum_vacuum_scale_factor = 0.02,
    autovacuum_analyze_scale_factor = 0.01,
    autovacuum_vacuum_cost_delay = 10
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:723
-- pg_s3::bucket_stats

CREATE FUNCTION bucket_stats(bucket TEXT) RETURNS JSONB
VOLATILE STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'bucket_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:323
-- pg_s3::create_bucket

CREATE FUNCTION create_bucket(name TEXT) RETURNS BIGINT
VOLATILE STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'create_bucket_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:345
-- pg_s3::delete_bucket

CREATE FUNCTION delete_bucket(name TEXT, force BOOLEAN DEFAULT FALSE) RETURNS BOOLEAN
VOLATILE STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'delete_bucket_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:516
-- pg_s3::delete_object

CREATE FUNCTION delete_object(bucket TEXT, key TEXT) RETURNS BOOLEAN
VOLATILE STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'delete_object_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:488
-- pg_s3::get_object

CREATE FUNCTION get_object(bucket TEXT, key TEXT) RETURNS BYTEA
VOLATILE STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'get_object_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:562
-- pg_s3::head_object

CREATE FUNCTION head_object(bucket TEXT, key TEXT) RETURNS JSONB
VOLATILE STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'head_object_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:592
-- pg_s3::list_buckets
CREATE  FUNCTION "list_buckets"() RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"object_count" bigint,  /* i64 */
	"total_size_bytes" bigint,  /* i64 */
	"created_at" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_buckets_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:630
-- pg_s3::list_objects

CREATE FUNCTION list_objects(
    bucket TEXT,
    prefix TEXT DEFAULT '',
    delimiter TEXT DEFAULT '',
    max_keys INT DEFAULT 1000,
    start_after TEXT DEFAULT ''
) RETURNS TABLE(key TEXT, size_bytes BIGINT, content_type TEXT, etag TEXT, last_modified TEXT, is_prefix BOOLEAN)
VOLATILE LANGUAGE c AS 'MODULE_PATHNAME', 'list_objects_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:389
-- pg_s3::put_object

CREATE FUNCTION put_object(
    bucket TEXT,
    key TEXT,
    content BYTEA,
    content_type TEXT DEFAULT 'application/octet-stream',
    metadata JSONB DEFAULT NULL
) RETURNS TEXT
VOLATILE LANGUAGE c AS 'MODULE_PATHNAME', 'put_object_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:94
-- pg_s3::reset_workers
CREATE  FUNCTION "reset_workers"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reset_workers_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:268
-- pg_s3::status
CREATE  FUNCTION "status"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:752
-- pg_s3::storage_stats
CREATE  FUNCTION "storage_stats"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'storage_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_s3/src/lib.rs:94
-- pg_s3::worker_status
CREATE  FUNCTION "worker_status"() RETURNS TABLE (
	"worker" INT,  /* i32 */
	"name" TEXT,  /* alloc::string::String */
	"state" TEXT,  /* alloc::string::String */
	"failures" INT,  /* i32 */
	"restarts" INT,  /* i32 */
	"pid" INT,  /* i32 */
	"since" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"last_failure" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'worker_status_wrapper';
/* </end connected objects> */

