/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:38
-- pg_image::extension_docs
CREATE  FUNCTION "extension_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'extension_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:279
-- pg_image::img_auto_orient
CREATE  FUNCTION "img_auto_orient"(
	"data" bytea /* &[u8] */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_auto_orient_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:93
-- pg_image::img_bit_depth
CREATE  FUNCTION "img_bit_depth"(
	"data" bytea /* &[u8] */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_bit_depth_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:139
-- pg_image::img_camera_make
CREATE  FUNCTION "img_camera_make"(
	"data" bytea /* core::option::Option<&[u8]> */
) RETURNS TEXT /* core::option::Option<alloc::string::String> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_camera_make_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:145
-- pg_image::img_camera_model
CREATE  FUNCTION "img_camera_model"(
	"data" bytea /* core::option::Option<&[u8]> */
) RETURNS TEXT /* core::option::Option<alloc::string::String> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_camera_model_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:416
-- pg_image::img_caption
CREATE  FUNCTION "img_caption"(
	"data" bytea, /* &[u8] */
	"max_tokens" INT DEFAULT 0 /* i32 */
) RETURNS TEXT /* alloc::string::String */
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_caption_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:84
-- pg_image::img_channels
CREATE  FUNCTION "img_channels"(
	"data" bytea /* &[u8] */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_channels_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:75
-- pg_image::img_colorspace
CREATE  FUNCTION "img_colorspace"(
	"data" bytea /* &[u8] */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_colorspace_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:252
-- pg_image::img_convert
CREATE  FUNCTION "img_convert"(
	"data" bytea, /* &[u8] */
	"format" TEXT /* &str */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_convert_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:243
-- pg_image::img_crop
CREATE  FUNCTION "img_crop"(
	"data" bytea, /* &[u8] */
	"x" INT, /* i32 */
	"y" INT, /* i32 */
	"width" INT, /* i32 */
	"height" INT /* i32 */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_crop_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:331
-- pg_image::img_detect
CREATE  FUNCTION "img_detect"(
	"data" bytea, /* &[u8] */
	"model" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"confidence" double precision DEFAULT 0.0 /* f64 */
) RETURNS TABLE (
	"label" TEXT,  /* alloc::string::String */
	"confidence" double precision,  /* f64 */
	"x" double precision,  /* f64 */
	"y" double precision,  /* f64 */
	"width" double precision,  /* f64 */
	"height" double precision  /* f64 */
)

LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_detect_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:379
-- pg_image::img_embed
CREATE  FUNCTION "img_embed"(
	"data" bytea, /* &[u8] */
	"model" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS real[] /* alloc::vec::Vec<f32> */

LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_embed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:396
-- pg_image::img_embed_text
CREATE  FUNCTION "img_embed_text"(
	"text" TEXT, /* &str */
	"model" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS real[] /* alloc::vec::Vec<f32> */

LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_embed_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:121
-- pg_image::img_exif
CREATE  FUNCTION "img_exif"(
	"data" bytea /* core::option::Option<&[u8]> */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_exif_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:127
-- pg_image::img_exif_value
CREATE  FUNCTION "img_exif_value"(
	"data" bytea, /* core::option::Option<&[u8]> */
	"tag" TEXT /* &str */
) RETURNS TEXT /* core::option::Option<alloc::string::String> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_exif_value_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:66
-- pg_image::img_format
CREATE  FUNCTION "img_format"(
	"data" bytea /* &[u8] */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_format_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:173
-- pg_image::img_gps_altitude
CREATE  FUNCTION "img_gps_altitude"(
	"data" bytea /* core::option::Option<&[u8]> */
) RETURNS double precision /* core::option::Option<f64> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_gps_altitude_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:161
-- pg_image::img_gps_lat
CREATE  FUNCTION "img_gps_lat"(
	"data" bytea /* core::option::Option<&[u8]> */
) RETURNS double precision /* core::option::Option<f64> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_gps_lat_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:167
-- pg_image::img_gps_lon
CREATE  FUNCTION "img_gps_lon"(
	"data" bytea /* core::option::Option<&[u8]> */
) RETURNS double precision /* core::option::Option<f64> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_gps_lon_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:261
-- pg_image::img_grayscale
CREATE  FUNCTION "img_grayscale"(
	"data" bytea /* &[u8] */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_grayscale_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:57
-- pg_image::img_height
CREATE  FUNCTION "img_height"(
	"data" bytea /* &[u8] */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_height_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:108
-- pg_image::img_metadata
CREATE  FUNCTION "img_metadata"(
	"data" bytea /* &[u8] */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_metadata_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:151
-- pg_image::img_orientation
CREATE  FUNCTION "img_orientation"(
	"data" bytea /* core::option::Option<&[u8]> */
) RETURNS INT /* core::option::Option<i32> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_orientation_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:301
-- pg_image::img_pixel_hash
CREATE  FUNCTION "img_pixel_hash"(
	"data" bytea /* &[u8] */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_pixel_hash_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:310
-- pg_image::img_pixel_hash_distance
CREATE  FUNCTION "img_pixel_hash_distance"(
	"hash1" TEXT, /* &str */
	"hash2" TEXT /* &str */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_pixel_hash_distance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:225
-- pg_image::img_resize
CREATE  FUNCTION "img_resize"(
	"data" bytea, /* &[u8] */
	"width" INT, /* i32 */
	"height" INT /* i32 */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_resize_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:270
-- pg_image::img_rotate
CREATE  FUNCTION "img_rotate"(
	"data" bytea, /* &[u8] */
	"degrees" INT /* i32 */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_rotate_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:102
-- pg_image::img_size_bytes
CREATE  FUNCTION "img_size_bytes"(
	"data" bytea /* &[u8] */
) RETURNS bigint /* i64 */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_size_bytes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:234
-- pg_image::img_thumbnail
CREATE  FUNCTION "img_thumbnail"(
	"data" bytea, /* &[u8] */
	"max_width" INT, /* i32 */
	"max_height" INT /* i32 */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_thumbnail_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:133
-- pg_image::img_timestamp
CREATE  FUNCTION "img_timestamp"(
	"data" bytea /* core::option::Option<&[u8]> */
) RETURNS timestamp with time zone /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_timestamp_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:288
-- pg_image::img_to_rgb
CREATE  FUNCTION "img_to_rgb"(
	"data" bytea /* &[u8] */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_to_rgb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:48
-- pg_image::img_width
CREATE  FUNCTION "img_width"(
	"data" bytea /* &[u8] */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'img_width_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_image/src/lib.rs:179
-- finalize

DO $bridge$
BEGIN
    -- Only create PostGIS bridge functions if PostGIS is available
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'postgis') THEN
        EXECUTE $fn$
            CREATE OR REPLACE FUNCTION pgimg.img_gps_point(data bytea) RETURNS geometry AS $$
                SELECT CASE
                    WHEN pgimg.img_gps_lon(data) IS NOT NULL AND pgimg.img_gps_lat(data) IS NOT NULL
                    THEN ST_SetSRID(ST_MakePoint(pgimg.img_gps_lon(data), pgimg.img_gps_lat(data)), 4326)
                    ELSE NULL
                END;
            $$ LANGUAGE SQL IMMUTABLE STRICT;
        $fn$;

        EXECUTE $fn$
            CREATE OR REPLACE FUNCTION pgimg.img_gps_pointz(data bytea) RETURNS geometry AS $$
                SELECT CASE
                    WHEN pgimg.img_gps_lon(data) IS NOT NULL AND pgimg.img_gps_lat(data) IS NOT NULL
                    THEN ST_SetSRID(ST_MakePoint(
                        pgimg.img_gps_lon(data),
                        pgimg.img_gps_lat(data),
                        COALESCE(pgimg.img_gps_altitude(data), 0)
                    ), 4326)
                    ELSE NULL
                END;
            $$ LANGUAGE SQL IMMUTABLE STRICT;
        $fn$;

        RAISE NOTICE 'pg_image: PostGIS bridge functions created (img_gps_point, img_gps_pointz)';
    ELSE
        RAISE NOTICE 'pg_image: PostGIS not found, skipping bridge functions. Install PostGIS and run CREATE EXTENSION pg_image again to enable.';
    END IF;
END
$bridge$;
/* </end connected objects> */

