/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:51
-- bootstrap

-- Schema is created by control file (schema = pgortools)

CREATE TABLE IF NOT EXISTS pgortools.problems (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    objective_type TEXT,
    objective_expr TEXT,
    status TEXT DEFAULT 'draft',
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pgortools.variables (
    id SERIAL PRIMARY KEY,
    problem_id INTEGER REFERENCES pgortools.problems(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    var_type TEXT DEFAULT 'int',
    domain_min BIGINT,
    domain_max BIGINT,
    pinned BOOLEAN DEFAULT false,
    UNIQUE(problem_id, name)
);

CREATE TABLE IF NOT EXISTS pgortools.constraints (
    id SERIAL PRIMARY KEY,
    problem_id INTEGER REFERENCES pgortools.problems(id) ON DELETE CASCADE,
    name TEXT,
    expression TEXT,
    constraint_type TEXT,
    constraint_config JSONB
);

CREATE TABLE IF NOT EXISTS pgortools.solutions (
    id SERIAL PRIMARY KEY,
    problem_id INTEGER REFERENCES pgortools.problems(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    objective_value DOUBLE PRECISION,
    variable_values JSONB,
    solve_time_ms INTEGER,
    solved_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pgortools.solve_jobs (
    id BIGSERIAL PRIMARY KEY,
    problem_name TEXT NOT NULL,
    config JSONB DEFAULT '{}',
    state TEXT NOT NULL DEFAULT 'queued'
        CHECK (state IN ('queued', 'solving', 'completed', 'failed', 'cancelled')),
    progress FLOAT DEFAULT 0.0,
    current_step TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    worker_pid INTEGER
);

CREATE INDEX IF NOT EXISTS idx_solve_jobs_state
    ON pgortools.solve_jobs(state) WHERE state = 'queued';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/cpsat.rs:45
-- requires:
--   bootstrap


CREATE TABLE IF NOT EXISTS pgortools.cp_intervals (
    id SERIAL PRIMARY KEY,
    problem_id INTEGER REFERENCES pgortools.problems(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    duration INTEGER NOT NULL,
    earliest_start INTEGER NOT NULL DEFAULT 0,
    latest_end INTEGER NOT NULL,
    UNIQUE(problem_id, name)
);

CREATE TABLE IF NOT EXISTS pgortools.cp_resources (
    id SERIAL PRIMARY KEY,
    problem_id INTEGER REFERENCES pgortools.problems(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    capacity INTEGER NOT NULL,
    UNIQUE(problem_id, name)
);

CREATE TABLE IF NOT EXISTS pgortools.cp_demands (
    id SERIAL PRIMARY KEY,
    problem_id INTEGER REFERENCES pgortools.problems(id) ON DELETE CASCADE,
    resource_name TEXT NOT NULL,
    interval_name TEXT NOT NULL,
    demand INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS pgortools.cp_precedences (
    id SERIAL PRIMARY KEY,
    problem_id INTEGER REFERENCES pgortools.problems(id) ON DELETE CASCADE,
    before_name TEXT NOT NULL,
    after_name TEXT NOT NULL,
    gap INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pgortools.cp_wait_objectives (
    id SERIAL PRIMARY KEY,
    problem_id INTEGER REFERENCES pgortools.problems(id) ON DELETE CASCADE,
    after_name TEXT NOT NULL,
    before_name TEXT NOT NULL,
    weight INTEGER NOT NULL DEFAULT 1
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/eidos_catalog.rs:24

-- ============================================================================
-- pg_ortools eidos_catalog contract — v1
--   Spec: https://github.com/matroidbe/eidos/blob/main/docs/development/eidos-catalog-contract.md
-- ============================================================================

-- Type mapping helper. Mirrors eidos-core's discover.rs::pg_type_to_eidos
-- exactly. Eidos cross-checks each arg/return pg_type → eidos_type at
-- discovery-time; a divergence here fails plugin import.
CREATE OR REPLACE FUNCTION _eidos_pg_to_eidos_type(udt_name TEXT)
RETURNS TEXT LANGUAGE sql IMMUTABLE SET search_path = pgortools, public AS $body$
    SELECT CASE lower(udt_name)
        WHEN 'int2'        THEN 'integer'
        WHEN 'int4'        THEN 'integer'
        WHEN 'int8'        THEN 'integer'
        WHEN 'smallint'    THEN 'integer'
        WHEN 'integer'     THEN 'integer'
        WHEN 'bigint'      THEN 'integer'
        WHEN 'float4'      THEN 'decimal'
        WHEN 'float8'      THEN 'decimal'
        WHEN 'numeric'     THEN 'decimal'
        WHEN 'decimal'     THEN 'decimal'
        WHEN 'real'        THEN 'decimal'
        WHEN 'bool'        THEN 'boolean'
        WHEN 'boolean'     THEN 'boolean'
        WHEN 'text'        THEN 'text'
        WHEN 'varchar'     THEN 'text'
        WHEN 'bpchar'      THEN 'text'
        WHEN 'character'   THEN 'text'
        WHEN 'date'        THEN 'date'
        WHEN 'timestamp'   THEN 'timestamp'
        WHEN 'timestamptz' THEN 'timestamp'
        WHEN 'uuid'        THEN 'uuid'
        WHEN 'jsonb'       THEN 'jsonb'
        WHEN 'json'        THEN 'jsonb'
        WHEN 'money'       THEN 'money'
        WHEN 'bytea'       THEN 'bytea'
        ELSE 'text /* ' || udt_name || ' */'
    END;
$body$;

-- Helper: build the args JSONB for a function from pg_proc so the live
-- signature is the source of truth. Returns NULL if the function doesn't exist
-- (so the catalog fails fast on schema drift), '[]' for a zero-arg function.
CREATE OR REPLACE FUNCTION _eidos_args_for(p_schema TEXT, p_func TEXT, descs JSONB DEFAULT '{}'::jsonb)
RETURNS JSONB LANGUAGE sql STABLE SET search_path = pgortools, public AS $body$
    WITH proc AS (
        SELECT p.oid, p.proargnames, p.proargtypes, p.pronargs, p.pronargdefaults
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = p_schema AND p.proname = p_func
        -- Deterministic on overloaded names: lowest oid = earliest-created.
        ORDER BY p.oid
        LIMIT 1
    ),
    args AS (
        SELECT
            COALESCE(proc.proargnames[i+1], 'arg' || (i+1)::text) AS name,
            format_type(proc.proargtypes[i], NULL)              AS pg_type_full,
            (SELECT typname FROM pg_type WHERE oid = proc.proargtypes[i]) AS udt,
            (i+1) > (proc.pronargs - proc.pronargdefaults)      AS has_default,
            i AS pos
        FROM proc, generate_series(0, proc.pronargs - 1) i
    )
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'name',        a.name,
        'pg_type',     a.pg_type_full,
        'eidos_type',  _eidos_pg_to_eidos_type(a.udt),
        'required',    NOT a.has_default,
        'description', descs->a.name
    ) ORDER BY a.pos), CASE WHEN EXISTS (SELECT 1 FROM proc) THEN '[]'::jsonb END)
    FROM args a;
$body$;

-- Helper: build the returns descriptor from pg_proc.
CREATE OR REPLACE FUNCTION _eidos_returns_for(p_schema TEXT, p_func TEXT, p_shape TEXT DEFAULT 'scalar')
RETURNS JSONB LANGUAGE sql STABLE SET search_path = pgortools, public AS $body$
    WITH proc AS (
        SELECT format_type(p.prorettype, NULL) AS pg_type_full,
               (SELECT typname FROM pg_type WHERE oid = p.prorettype) AS udt
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = p_schema AND p.proname = p_func
        ORDER BY p.oid
        LIMIT 1
    )
    SELECT jsonb_build_object(
        'pg_type',    pg_type_full,
        'eidos_type', _eidos_pg_to_eidos_type(udt),
        'shape',      p_shape
    ) FROM proc;
$body$;

-- ============================================================================
-- eidos_catalog_meta — required
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_meta() RETURNS jsonb
LANGUAGE sql STABLE SET search_path = pgortools, public AS $body$
    SELECT jsonb_build_object(
        'extension',      'pg_ortools',
        -- Read the installed version live so meta can never go stale against
        -- the actual extension.
        'version',        COALESCE((SELECT extversion FROM pg_extension WHERE extname = 'pg_ortools'), '0.0.0'),
        'eidos_protocol', '1',
        'display_name',   'OR-Tools',
        'description',    'Constraint optimization: MIP + CP-SAT solvers over a named-problem API',
        'icon',           'sigma',
        'primary_color',  '#0ea5e9',
        'domains',        ARRAY['optimization']
    );
$body$;

-- ============================================================================
-- eidos_catalog_entities — required, but pg_ortools is a compute extension:
-- it exposes no domain entities. Return zero rows.
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_entities() RETURNS TABLE (
    name              text,
    schema_name       text,
    table_name        text,
    primary_key       text[],
    columns           jsonb,
    domain            text,
    display_name      text,
    icon              text,
    read_only         boolean,
    fsm_machine       text,
    default_sort      text,
    search_columns    text[]
) LANGUAGE sql STABLE SET search_path = pgortools, public AS $body$
    SELECT NULL::text, NULL::text, NULL::text, NULL::text[], NULL::jsonb,
           NULL::text, NULL::text, NULL::text, NULL::boolean, NULL::text,
           NULL::text, NULL::text[]
    WHERE false;
$body$;

-- ============================================================================
-- eidos_catalog_functions — required
--
-- The curated public solver surface. SIGNATURES come from pg_proc via
-- _eidos_args_for / _eidos_returns_for (no drift possible); the side-effect
-- class + display metadata are authored here.
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_functions() RETURNS TABLE (
    name              text,
    schema_name       text,
    args              jsonb,
    returns           jsonb,
    side_effects      text,
    fsm_event         jsonb,
    suggested_roles   text[],
    domain            text,
    display_name      text,
    icon              text,
    danger            boolean
) LANGUAGE sql STABLE SET search_path = pgortools, public AS $body$
    WITH defs(name, side_effects, domain, display_name, icon, danger, return_shape) AS (
        VALUES
            ('create_problem', 'mutates', 'optimization', 'Create problem',     'plus-circle',  false, 'scalar'),
            ('add_int_var',    'mutates', 'optimization', 'Add integer var',    'variable',     false, 'scalar'),
            ('add_bool_var',   'mutates', 'optimization', 'Add boolean var',    'toggle-left',  false, 'scalar'),
            ('add_constraint', 'mutates', 'optimization', 'Add constraint',     'ruler',        false, 'scalar'),
            ('minimize',       'mutates', 'optimization', 'Set minimize',       'trending-down',false, 'scalar'),
            ('maximize',       'mutates', 'optimization', 'Set maximize',       'trending-up',  false, 'scalar'),
            ('solve',          'mutates', 'optimization', 'Solve (async)',      'play',         false, 'scalar'),
            ('solve_sync',     'mutates', 'optimization', 'Solve (blocking)',   'play-circle',  false, 'jsonb'),
            ('get_solution',   'query',   'optimization', 'Get solution',       'eye',          false, 'jsonb'),
            ('drop_problem',   'mutates', 'optimization', 'Drop problem',       'trash-2',      true,  'scalar'),
            ('cancel_solve',   'mutates', 'optimization', 'Cancel solve',       'x-circle',     true,  'scalar')
    )
    SELECT
        d.name,
        'pgortools'::text                                          AS schema_name,
        _eidos_args_for('pgortools', d.name)                       AS args,
        _eidos_returns_for('pgortools', d.name, d.return_shape)    AS returns,
        d.side_effects,
        NULL::jsonb                                                AS fsm_event,
        ARRAY['admin']::text[]                                     AS suggested_roles,
        d.domain,
        d.display_name,
        d.icon,
        d.danger
    FROM defs d;
$body$;

GRANT EXECUTE ON FUNCTION _eidos_pg_to_eidos_type(text)       TO PUBLIC;
GRANT EXECUTE ON FUNCTION _eidos_args_for(text, text, jsonb)  TO PUBLIC;
GRANT EXECUTE ON FUNCTION _eidos_returns_for(text, text, text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_meta()                TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_entities()            TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_functions()           TO PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:183
-- pg_ortools::add_bool_var
CREATE  FUNCTION "add_bool_var"(
	"problem" TEXT, /* &str */
	"var_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_bool_var_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:199
-- pg_ortools::add_constraint
CREATE  FUNCTION "add_constraint"(
	"problem" TEXT, /* &str */
	"expression" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_constraint_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/cpsat.rs:142
-- pg_ortools::cpsat::add_demand
CREATE  FUNCTION "add_demand"(
	"problem" TEXT, /* &str */
	"resource" TEXT, /* &str */
	"interval" TEXT, /* &str */
	"demand" INT DEFAULT 1 /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_demand_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:162
-- pg_ortools::add_int_var
CREATE  FUNCTION "add_int_var"(
	"problem" TEXT, /* &str */
	"var_name" TEXT, /* &str */
	"domain_min" bigint, /* i64 */
	"domain_max" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_int_var_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/cpsat.rs:100
-- pg_ortools::cpsat::add_interval_var
CREATE  FUNCTION "add_interval_var"(
	"problem" TEXT, /* &str */
	"name" TEXT, /* &str */
	"duration" INT, /* i32 */
	"earliest_start" INT, /* i32 */
	"latest_end" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_interval_var_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/cpsat.rs:162
-- pg_ortools::cpsat::add_precedence
CREATE  FUNCTION "add_precedence"(
	"problem" TEXT, /* &str */
	"before" TEXT, /* &str */
	"after" TEXT, /* &str */
	"gap" INT DEFAULT 0 /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_precedence_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/cpsat.rs:128
-- pg_ortools::cpsat::add_resource
CREATE  FUNCTION "add_resource"(
	"problem" TEXT, /* &str */
	"name" TEXT, /* &str */
	"capacity" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_resource_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:365
-- pg_ortools::add_typed_constraint
CREATE  FUNCTION "add_typed_constraint"(
	"problem" TEXT, /* &str */
	"constraint_type" TEXT, /* &str */
	"config" jsonb /* pgrx::datum::json::JsonB */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_typed_constraint_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:473
-- pg_ortools::cancel_solve
CREATE  FUNCTION "cancel_solve"(
	"job_id" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cancel_solve_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:135
-- pg_ortools::create_problem
CREATE  FUNCTION "create_problem"(
	"name" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_problem_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:150
-- pg_ortools::drop_problem
CREATE  FUNCTION "drop_problem"(
	"name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_problem_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:28
-- pg_ortools::extension_docs
CREATE  FUNCTION "extension_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'extension_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:482
-- pg_ortools::get_solution
CREATE  FUNCTION "get_solution"(
	"problem" TEXT /* &str */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_solution_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:215
-- pg_ortools::maximize
CREATE  FUNCTION "maximize"(
	"problem" TEXT, /* &str */
	"expression" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'maximize_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:231
-- pg_ortools::minimize
CREATE  FUNCTION "minimize"(
	"problem" TEXT, /* &str */
	"expression" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'minimize_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/cpsat.rs:177
-- pg_ortools::cpsat::minimize_wait
CREATE  FUNCTION "minimize_wait"(
	"problem" TEXT, /* &str */
	"after" TEXT, /* &str */
	"before" TEXT, /* &str */
	"weight" INT DEFAULT 1 /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'minimize_wait_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:650
-- pg_ortools::parse_assignment
CREATE  FUNCTION "parse_assignment"(
	"solution" jsonb /* pgrx::datum::json::JsonB */
) RETURNS TABLE (
	"resource" TEXT,  /* alloc::string::String */
	"target" TEXT,  /* alloc::string::String */
	"assigned" bool  /* bool */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'parse_assignment_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:391
-- pg_ortools::pin_variable
CREATE  FUNCTION "pin_variable"(
	"problem" TEXT, /* &str */
	"var_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pin_variable_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/worker.rs:380
-- pg_ortools::worker::reset_workers
CREATE  FUNCTION "reset_workers"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reset_workers_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:252
-- pg_ortools::solve
CREATE  FUNCTION "solve"(
	"problem" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solve_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:508
-- pg_ortools::solve_assignment
CREATE  FUNCTION "solve_assignment"(
	"problem_name" TEXT, /* &str */
	"resources_table" TEXT, /* &str */
	"resource_name_col" TEXT, /* &str */
	"resource_group_col" TEXT, /* &str */
	"resource_cost_col" TEXT, /* &str */
	"targets_table" TEXT, /* &str */
	"target_name_col" TEXT, /* &str */
	"group_per_target" INT, /* i32 */
	"objective" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solve_assignment_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:322
-- pg_ortools::solve_auto
CREATE  FUNCTION "solve_auto"(
	"problem" TEXT, /* &str */
	"time_limit_seconds" INT DEFAULT 60 /* i32 */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solve_auto_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/cpsat.rs:218
-- pg_ortools::cpsat::solve_cp
CREATE  FUNCTION "solve_cp"(
	"problem" TEXT, /* &str */
	"time_limit_seconds" INT DEFAULT NULL /* core::option::Option<i32> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solve_cp_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/cpsat.rs:198
-- pg_ortools::cpsat::solve_cp_sync
CREATE  FUNCTION "solve_cp_sync"(
	"problem" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solve_cp_sync_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:293
-- pg_ortools::solve_greedy
CREATE  FUNCTION "solve_greedy"(
	"problem" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solve_greedy_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:303
-- pg_ortools::solve_local
CREATE  FUNCTION "solve_local"(
	"problem" TEXT, /* &str */
	"algorithm" TEXT DEFAULT 'late_acceptance', /* &str */
	"time_limit_seconds" INT DEFAULT 30 /* i32 */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solve_local_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:437
-- pg_ortools::solve_status
CREATE  FUNCTION "solve_status"(
	"job_id" bigint /* i64 */
) RETURNS TABLE (
	"job_id" bigint,  /* i64 */
	"problem_name" TEXT,  /* alloc::string::String */
	"state" TEXT,  /* alloc::string::String */
	"progress" double precision,  /* f64 */
	"current_step" TEXT,  /* core::option::Option<alloc::string::String> */
	"error_message" TEXT,  /* core::option::Option<alloc::string::String> */
	"started_at" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"completed_at" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"elapsed_seconds" double precision  /* core::option::Option<f64> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solve_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:283
-- pg_ortools::solve_sync
CREATE  FUNCTION "solve_sync"(
	"problem" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solve_sync_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:265
-- pg_ortools::solve_with_strategy
CREATE  FUNCTION "solve_with_strategy"(
	"problem" TEXT, /* &str */
	"strategy" TEXT, /* &str */
	"time_limit_seconds" INT DEFAULT 30 /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solve_with_strategy_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:414
-- pg_ortools::unpin_variable
CREATE  FUNCTION "unpin_variable"(
	"problem" TEXT, /* &str */
	"var_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unpin_variable_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/worker.rs:380
-- pg_ortools::worker::worker_status
CREATE  FUNCTION "worker_status"() RETURNS TABLE (
	"worker" INT,  /* i32 */
	"name" TEXT,  /* alloc::string::String */
	"state" TEXT,  /* alloc::string::String */
	"failures" INT,  /* i32 */
	"restarts" INT,  /* i32 */
	"pid" INT,  /* i32 */
	"since" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"last_failure" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'worker_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ortools/src/lib.rs:120
-- finalize

GRANT USAGE ON SCHEMA pgortools TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA pgortools TO PUBLIC;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA pgortools TO PUBLIC;
/* </end connected objects> */

