/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/eidos_catalog.rs:24

-- ============================================================================
-- pg_prob eidos_catalog contract — v1
--   Spec: https://github.com/matroidbe/eidos/blob/main/docs/development/eidos-catalog-contract.md
-- ============================================================================

-- Type mapping helper. Mirrors eidos-core's discover.rs::pg_type_to_eidos
-- exactly. Eidos cross-checks each arg/return pg_type → eidos_type at
-- discovery-time; a divergence here fails plugin import.
CREATE OR REPLACE FUNCTION _eidos_pg_to_eidos_type(udt_name TEXT)
RETURNS TEXT LANGUAGE sql IMMUTABLE SET search_path = pgprob, public AS $body$
    SELECT CASE lower(udt_name)
        WHEN 'int2'        THEN 'integer'
        WHEN 'int4'        THEN 'integer'
        WHEN 'int8'        THEN 'integer'
        WHEN 'smallint'    THEN 'integer'
        WHEN 'integer'     THEN 'integer'
        WHEN 'bigint'      THEN 'integer'
        WHEN 'float4'      THEN 'decimal'
        WHEN 'float8'      THEN 'decimal'
        WHEN 'numeric'     THEN 'decimal'
        WHEN 'decimal'     THEN 'decimal'
        WHEN 'real'        THEN 'decimal'
        WHEN 'bool'        THEN 'boolean'
        WHEN 'boolean'     THEN 'boolean'
        WHEN 'text'        THEN 'text'
        WHEN 'varchar'     THEN 'text'
        WHEN 'bpchar'      THEN 'text'
        WHEN 'character'   THEN 'text'
        WHEN 'date'        THEN 'date'
        WHEN 'timestamp'   THEN 'timestamp'
        WHEN 'timestamptz' THEN 'timestamp'
        WHEN 'uuid'        THEN 'uuid'
        WHEN 'jsonb'       THEN 'jsonb'
        WHEN 'json'        THEN 'jsonb'
        WHEN 'money'       THEN 'money'
        WHEN 'bytea'       THEN 'bytea'
        ELSE 'text /* ' || udt_name || ' */'
    END;
$body$;

-- Helper: build the args JSONB for a function from pg_proc so the live
-- signature is the source of truth. Returns NULL if the function doesn't exist
-- (so the catalog fails fast on schema drift), '[]' for a zero-arg function.
CREATE OR REPLACE FUNCTION _eidos_args_for(p_schema TEXT, p_func TEXT, descs JSONB DEFAULT '{}'::jsonb)
RETURNS JSONB LANGUAGE sql STABLE SET search_path = pgprob, public AS $body$
    WITH proc AS (
        SELECT p.oid, p.proargnames, p.proargtypes, p.pronargs, p.pronargdefaults
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = p_schema AND p.proname = p_func
        -- Deterministic on overloaded names: lowest oid = earliest-created.
        ORDER BY p.oid
        LIMIT 1
    ),
    args AS (
        SELECT
            COALESCE(proc.proargnames[i+1], 'arg' || (i+1)::text) AS name,
            format_type(proc.proargtypes[i], NULL)              AS pg_type_full,
            (SELECT typname FROM pg_type WHERE oid = proc.proargtypes[i]) AS udt,
            (i+1) > (proc.pronargs - proc.pronargdefaults)      AS has_default,
            i AS pos
        FROM proc, generate_series(0, proc.pronargs - 1) i
    )
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'name',        a.name,
        'pg_type',     a.pg_type_full,
        'eidos_type',  _eidos_pg_to_eidos_type(a.udt),
        'required',    NOT a.has_default,
        'description', descs->a.name
    ) ORDER BY a.pos), CASE WHEN EXISTS (SELECT 1 FROM proc) THEN '[]'::jsonb END)
    FROM args a;
$body$;

-- Helper: build the returns descriptor from pg_proc.
CREATE OR REPLACE FUNCTION _eidos_returns_for(p_schema TEXT, p_func TEXT, p_shape TEXT DEFAULT 'scalar')
RETURNS JSONB LANGUAGE sql STABLE SET search_path = pgprob, public AS $body$
    WITH proc AS (
        SELECT format_type(p.prorettype, NULL) AS pg_type_full,
               (SELECT typname FROM pg_type WHERE oid = p.prorettype) AS udt
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = p_schema AND p.proname = p_func
        ORDER BY p.oid
        LIMIT 1
    )
    SELECT jsonb_build_object(
        'pg_type',    pg_type_full,
        'eidos_type', _eidos_pg_to_eidos_type(udt),
        'shape',      p_shape
    ) FROM proc;
$body$;

-- ============================================================================
-- eidos_catalog_meta — required
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_meta() RETURNS jsonb
LANGUAGE sql STABLE SET search_path = pgprob, public AS $body$
    SELECT jsonb_build_object(
        'extension',      'pg_prob',
        -- Read the installed version live so meta can never go stale against
        -- the actual extension.
        'version',        COALESCE((SELECT extversion FROM pg_extension WHERE extname = 'pg_prob'), '0.0.0'),
        'eidos_protocol', '1',
        'display_name',   'Probabilistic Types',
        'description',    'Uncertain values as distributions; arithmetic propagates uncertainty via Monte Carlo',
        'icon',           'bar-chart-3',
        'primary_color',  '#8b5cf6',
        'domains',        ARRAY['statistics']
    );
$body$;

-- ============================================================================
-- eidos_catalog_entities — required
-- pg_prob is a compute extension: no domain entities. Return zero rows.
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_entities() RETURNS TABLE (
    name              text,
    schema_name       text,
    table_name        text,
    primary_key       text[],
    columns           jsonb,
    domain            text,
    display_name      text,
    icon              text,
    read_only         boolean,
    fsm_machine       text,
    default_sort      text,
    search_columns    text[]
) LANGUAGE sql STABLE SET search_path = pgprob, public AS $body$
    SELECT NULL::text, NULL::text, NULL::text, NULL::text[], NULL::jsonb,
           NULL::text, NULL::text, NULL::text, NULL::boolean, NULL::text,
           NULL::text, NULL::text[]
    WHERE false;
$body$;

-- ============================================================================
-- eidos_catalog_functions — required
--
-- The curated public surface. SIGNATURES come from pg_proc via
-- _eidos_args_for / _eidos_returns_for (no drift possible); the side-effect
-- class + display metadata are authored here.
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_functions() RETURNS TABLE (
    name              text,
    schema_name       text,
    args              jsonb,
    returns           jsonb,
    side_effects      text,
    fsm_event         jsonb,
    suggested_roles   text[],
    domain            text,
    display_name      text,
    icon              text,
    danger            boolean
) LANGUAGE sql STABLE SET search_path = pgprob, public AS $body$
    WITH defs(name, side_effects, domain, display_name, icon, danger, return_shape) AS (
        VALUES
            ('literal'     , 'query'  , 'statistics', 'Literal'      , 'hash'         , false, 'scalar'),
            ('normal'      , 'query'  , 'statistics', 'Normal'       , 'bell-curve'   , false, 'scalar'),
            ('uniform'     , 'query'  , 'statistics', 'Uniform'      , 'minus'        , false, 'scalar'),
            ('triangular'  , 'query'  , 'statistics', 'Triangular'   , 'triangle'     , false, 'scalar'),
            ('beta'        , 'query'  , 'statistics', 'Beta'         , 'activity'     , false, 'scalar'),
            ('lognormal'   , 'query'  , 'statistics', 'Lognormal'    , 'trending-up'  , false, 'scalar'),
            ('pert'        , 'query'  , 'statistics', 'PERT'         , 'git-commit'   , false, 'scalar'),
            ('poisson'     , 'query'  , 'statistics', 'Poisson'      , 'zap'          , false, 'scalar'),
            ('exponential' , 'query'  , 'statistics', 'Exponential'  , 'trending-down', false, 'scalar'),
            ('mean'        , 'query'  , 'statistics', 'Mean'         , 'sigma'        , false, 'scalar'),
            ('variance'    , 'query'  , 'statistics', 'Variance'     , 'move-diagonal', false, 'scalar'),
            ('stddev'      , 'query'  , 'statistics', 'Std deviation', 'move-vertical', false, 'scalar'),
            ('percentile'  , 'query'  , 'statistics', 'Percentile'   , 'percent'      , false, 'scalar'),
            ('prob_below'  , 'query'  , 'statistics', 'P(X < x)'     , 'chevron-left' , false, 'scalar'),
            ('prob_above'  , 'query'  , 'statistics', 'P(X > x)'     , 'chevron-right', false, 'scalar'),
            ('prob_between', 'query'  , 'statistics', 'P(a < X < b)' , 'code'         , false, 'scalar'),
            ('sample'      , 'query'  , 'statistics', 'Sample'       , 'dice-5'       , false, 'scalar'),
            ('summarize'   , 'query'  , 'statistics', 'Summarize'    , 'list'         , false, 'jsonb'),
            ('dist_abs'    , 'query'  , 'statistics', 'Absolute'     , 'plus-minus'   , false, 'scalar'),
            ('dist_sqrt'   , 'query'  , 'statistics', 'Square root'  , 'radical'      , false, 'scalar'),
            ('dist_exp'    , 'query'  , 'statistics', 'Exponential'  , 'superscript'  , false, 'scalar'),
            ('dist_ln'     , 'query'  , 'statistics', 'Natural log'  , 'subscript'    , false, 'scalar')
    )
    SELECT
        d.name,
        'pgprob'::text                                           AS schema_name,
        _eidos_args_for('pgprob', d.name)                        AS args,
        _eidos_returns_for('pgprob', d.name, d.return_shape)     AS returns,
        d.side_effects,
        NULL::jsonb                                                AS fsm_event,
        ARRAY['admin']::text[]                                     AS suggested_roles,
        d.domain,
        d.display_name,
        d.icon,
        d.danger
    FROM defs d;
$body$;

GRANT EXECUTE ON FUNCTION _eidos_pg_to_eidos_type(text)        TO PUBLIC;
GRANT EXECUTE ON FUNCTION _eidos_args_for(text, text, jsonb)   TO PUBLIC;
GRANT EXECUTE ON FUNCTION _eidos_returns_for(text, text, text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_meta()                 TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_entities()             TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_functions()            TO PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:24
-- pg_prob::distribution::Dist
CREATE TYPE Dist;

-- extensions/pg_prob/src/distribution.rs:24
-- pg_prob::distribution::dist_in
CREATE  FUNCTION "dist_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS Dist /* core::option::Option<pg_prob::distribution::Dist> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_in_wrapper';

-- extensions/pg_prob/src/distribution.rs:24
-- pg_prob::distribution::dist_out
CREATE  FUNCTION "dist_out"(
	"input" Dist /* pg_prob::distribution::Dist */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_out_wrapper';

-- extensions/pg_prob/src/distribution.rs:24
-- pg_prob::distribution::Dist
CREATE TYPE Dist (
	INTERNALLENGTH = variable,
	INPUT = dist_in, /* pg_prob::distribution::dist_in */
	OUTPUT = dist_out, /* pg_prob::distribution::dist_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:208
-- pg_prob::distribution::DistAvgState
CREATE TYPE DistAvgState;

-- extensions/pg_prob/src/distribution.rs:208
-- pg_prob::distribution::distavgstate_in
CREATE  FUNCTION "distavgstate_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS DistAvgState /* core::option::Option<pg_prob::distribution::DistAvgState> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'distavgstate_in_wrapper';

-- extensions/pg_prob/src/distribution.rs:208
-- pg_prob::distribution::distavgstate_out
CREATE  FUNCTION "distavgstate_out"(
	"input" DistAvgState /* pg_prob::distribution::DistAvgState */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'distavgstate_out_wrapper';

-- extensions/pg_prob/src/distribution.rs:208
-- pg_prob::distribution::DistAvgState
CREATE TYPE DistAvgState (
	INTERNALLENGTH = variable,
	INPUT = distavgstate_in, /* pg_prob::distribution::distavgstate_in */
	OUTPUT = distavgstate_out, /* pg_prob::distribution::distavgstate_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/fitting.rs:115
-- pg_prob::fitting::FitCorrState
CREATE TYPE FitCorrState;

-- extensions/pg_prob/src/fitting.rs:115
-- pg_prob::fitting::fitcorrstate_in
CREATE  FUNCTION "fitcorrstate_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS FitCorrState /* core::option::Option<pg_prob::fitting::FitCorrState> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fitcorrstate_in_wrapper';

-- extensions/pg_prob/src/fitting.rs:115
-- pg_prob::fitting::fitcorrstate_out
CREATE  FUNCTION "fitcorrstate_out"(
	"input" FitCorrState /* pg_prob::fitting::FitCorrState */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fitcorrstate_out_wrapper';

-- extensions/pg_prob/src/fitting.rs:115
-- pg_prob::fitting::FitCorrState
CREATE TYPE FitCorrState (
	INTERNALLENGTH = variable,
	INPUT = fitcorrstate_in, /* pg_prob::fitting::fitcorrstate_in */
	OUTPUT = fitcorrstate_out, /* pg_prob::fitting::fitcorrstate_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/fitting.rs:22
-- pg_prob::fitting::FitState
CREATE TYPE FitState;

-- extensions/pg_prob/src/fitting.rs:22
-- pg_prob::fitting::fitstate_in
CREATE  FUNCTION "fitstate_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS FitState /* core::option::Option<pg_prob::fitting::FitState> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fitstate_in_wrapper';

-- extensions/pg_prob/src/fitting.rs:22
-- pg_prob::fitting::fitstate_out
CREATE  FUNCTION "fitstate_out"(
	"input" FitState /* pg_prob::fitting::FitState */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fitstate_out_wrapper';

-- extensions/pg_prob/src/fitting.rs:22
-- pg_prob::fitting::FitState
CREATE TYPE FitState (
	INTERNALLENGTH = variable,
	INPUT = fitstate_in, /* pg_prob::fitting::fitstate_in */
	OUTPUT = fitstate_out, /* pg_prob::fitting::fitstate_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:131
-- pg_prob::distribution::beta
CREATE  FUNCTION "beta"(
	"alpha" double precision, /* f64 */
	"beta_param" double precision, /* f64 */
	"min" double precision DEFAULT 0.0, /* f64 */
	"max" double precision DEFAULT 1.0 /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'beta_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:250
-- pg_prob::operators::coalesce
CREATE  FUNCTION "coalesce"(
	"a" Dist, /* core::option::Option<pg_prob::distribution::Dist> */
	"b" Dist /* core::option::Option<pg_prob::distribution::Dist> */
) RETURNS Dist /* core::option::Option<pg_prob::distribution::Dist> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'coalesce2_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:256
-- pg_prob::operators::coalesce
CREATE  FUNCTION "coalesce"(
	"a" Dist, /* core::option::Option<pg_prob::distribution::Dist> */
	"b" Dist, /* core::option::Option<pg_prob::distribution::Dist> */
	"c" Dist /* core::option::Option<pg_prob::distribution::Dist> */
) RETURNS Dist /* core::option::Option<pg_prob::distribution::Dist> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'coalesce3_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:262
-- pg_prob::operators::coalesce
CREATE  FUNCTION "coalesce"(
	"a" Dist, /* core::option::Option<pg_prob::distribution::Dist> */
	"b" Dist, /* core::option::Option<pg_prob::distribution::Dist> */
	"c" Dist, /* core::option::Option<pg_prob::distribution::Dist> */
	"d" Dist /* core::option::Option<pg_prob::distribution::Dist> */
) RETURNS Dist /* core::option::Option<pg_prob::distribution::Dist> */
IMMUTABLE PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'coalesce4_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/correlation.rs:69
-- pg_prob::correlation::correlated_pair
CREATE  FUNCTION "correlated_pair"(
	"dist1" Dist, /* pg_prob::distribution::Dist */
	"dist2" Dist, /* pg_prob::distribution::Dist */
	"rho" double precision, /* f64 */
	"n" INT DEFAULT 1000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS TABLE (
	"val1" double precision,  /* f64 */
	"val2" double precision  /* f64 */
)
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'correlated_pair_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/correlation.rs:130
-- pg_prob::correlation::correlated_sample
CREATE  FUNCTION "correlated_sample"(
	"dists" Dist[], /* alloc::vec::Vec<pg_prob::distribution::Dist> */
	"correlations" double precision[], /* alloc::vec::Vec<f64> */
	"n" INT DEFAULT 1000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS TABLE (
	"sample_idx" INT,  /* i32 */
	"values" double precision[]  /* alloc::vec::Vec<f64> */
)
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'correlated_sample_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:163
-- pg_prob::sampling::correlation
CREATE  FUNCTION "correlation"(
	"dist1" Dist, /* pg_prob::distribution::Dist */
	"dist2" Dist, /* pg_prob::distribution::Dist */
	"n" INT DEFAULT 10000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS double precision /* f64 */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'correlation_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:142
-- pg_prob::sampling::covariance
CREATE  FUNCTION "covariance"(
	"dist1" Dist, /* pg_prob::distribution::Dist */
	"dist2" Dist, /* pg_prob::distribution::Dist */
	"n" INT DEFAULT 10000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS double precision /* f64 */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'covariance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:102
-- pg_prob::operators::dist_abs
CREATE  FUNCTION "dist_abs"(
	"dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_abs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:16
-- pg_prob::operators::dist_add
CREATE  FUNCTION "dist_add"(
	"left" Dist, /* pg_prob::distribution::Dist */
	"right" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_add_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:68
-- pg_prob::operators::dist_add_scalar
CREATE  FUNCTION "dist_add_scalar"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"scalar" double precision /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_add_scalar_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:359
-- pg_prob::operators::dist_avg_final
CREATE  FUNCTION "dist_avg_final"(
	"state" DistAvgState /* core::option::Option<pg_prob::distribution::DistAvgState> */
) RETURNS Dist /* core::option::Option<pg_prob::distribution::Dist> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_avg_final_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:353
-- pg_prob::operators::dist_avg_state
CREATE  FUNCTION "dist_avg_state"(
	"state" DistAvgState, /* core::option::Option<pg_prob::distribution::DistAvgState> */
	"value" Dist /* core::option::Option<pg_prob::distribution::Dist> */
) RETURNS DistAvgState /* core::option::Option<pg_prob::distribution::DistAvgState> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_avg_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:364
-- requires:
--   dist_avg_state
--   dist_avg_final


CREATE AGGREGATE @extschema@.avg(@extschema@.dist) (
    SFUNC = @extschema@.dist_avg_state,
    STYPE = @extschema@.DistAvgState,
    FINALFUNC = @extschema@.dist_avg_final
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:34
-- pg_prob::operators::dist_div
CREATE  FUNCTION "dist_div"(
	"left" Dist, /* pg_prob::distribution::Dist */
	"right" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_div_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:56
-- pg_prob::operators::dist_div_scalar
CREATE  FUNCTION "dist_div_scalar"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"scalar" double precision /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_div_scalar_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:114
-- pg_prob::operators::dist_exp
CREATE  FUNCTION "dist_exp"(
	"dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_exp_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:261
-- pg_prob::distribution::dist_from_text
CREATE  FUNCTION "dist_from_text"(
	"input" TEXT /* &str */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_from_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:266
-- requires:
--   dist_from_text


CREATE CAST (text AS @extschema@.dist)
    WITH FUNCTION @extschema@.dist_from_text(text)
    AS IMPLICIT;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:120
-- pg_prob::operators::dist_ln
CREATE  FUNCTION "dist_ln"(
	"dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_ln_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:326
-- pg_prob::operators::dist_max_op
CREATE  FUNCTION "dist_max_op"(
	"left" Dist, /* pg_prob::distribution::Dist */
	"right" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_max_op_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:332
-- pg_prob::operators::dist_max_state
CREATE  FUNCTION "dist_max_state"(
	"state" Dist, /* core::option::Option<pg_prob::distribution::Dist> */
	"value" Dist /* core::option::Option<pg_prob::distribution::Dist> */
) RETURNS Dist /* core::option::Option<pg_prob::distribution::Dist> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_max_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:337
-- requires:
--   dist_max_state


CREATE AGGREGATE @extschema@.max(@extschema@.dist) (
    SFUNC = @extschema@.dist_max_state,
    STYPE = @extschema@.dist
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:299
-- pg_prob::operators::dist_min_op
CREATE  FUNCTION "dist_min_op"(
	"left" Dist, /* pg_prob::distribution::Dist */
	"right" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_min_op_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:305
-- pg_prob::operators::dist_min_state
CREATE  FUNCTION "dist_min_state"(
	"state" Dist, /* core::option::Option<pg_prob::distribution::Dist> */
	"value" Dist /* core::option::Option<pg_prob::distribution::Dist> */
) RETURNS Dist /* core::option::Option<pg_prob::distribution::Dist> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_min_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:310
-- requires:
--   dist_min_state


CREATE AGGREGATE @extschema@.min(@extschema@.dist) (
    SFUNC = @extschema@.dist_min_state,
    STYPE = @extschema@.dist
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:28
-- pg_prob::operators::dist_mul
CREATE  FUNCTION "dist_mul"(
	"left" Dist, /* pg_prob::distribution::Dist */
	"right" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_mul_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:44
-- pg_prob::operators::dist_mul_scalar
CREATE  FUNCTION "dist_mul_scalar"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"scalar" double precision /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_mul_scalar_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:96
-- pg_prob::operators::dist_neg
CREATE  FUNCTION "dist_neg"(
	"dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_neg_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:108
-- pg_prob::operators::dist_sqrt
CREATE  FUNCTION "dist_sqrt"(
	"dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_sqrt_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:22
-- pg_prob::operators::dist_sub
CREATE  FUNCTION "dist_sub"(
	"left" Dist, /* pg_prob::distribution::Dist */
	"right" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_sub_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:80
-- pg_prob::operators::dist_sub_scalar
CREATE  FUNCTION "dist_sub_scalar"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"scalar" double precision /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_sub_scalar_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:278
-- pg_prob::operators::dist_sum_state
CREATE  FUNCTION "dist_sum_state"(
	"state" Dist, /* core::option::Option<pg_prob::distribution::Dist> */
	"value" Dist /* core::option::Option<pg_prob::distribution::Dist> */
) RETURNS Dist /* core::option::Option<pg_prob::distribution::Dist> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dist_sum_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:283
-- requires:
--   dist_sum_state


CREATE AGGREGATE @extschema@.sum(@extschema@.dist) (
    SFUNC = @extschema@.dist_sum_state,
    STYPE = @extschema@.dist
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:161
-- pg_prob::distribution::exponential
CREATE  FUNCTION "exponential"(
	"lambda" double precision /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'exponential_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/lib.rs:37
-- pg_prob::extension_docs
CREATE  FUNCTION "extension_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'extension_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/fitting.rs:146
-- pg_prob::fitting::fit_corr_final
CREATE  FUNCTION "fit_corr_final"(
	"state" FitCorrState /* core::option::Option<pg_prob::fitting::FitCorrState> */
) RETURNS double precision /* core::option::Option<f64> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fit_corr_final_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/fitting.rs:136
-- pg_prob::fitting::fit_corr_state
CREATE  FUNCTION "fit_corr_state"(
	"state" FitCorrState, /* core::option::Option<pg_prob::fitting::FitCorrState> */
	"x" double precision, /* core::option::Option<f64> */
	"y" double precision /* core::option::Option<f64> */
) RETURNS FitCorrState /* core::option::Option<pg_prob::fitting::FitCorrState> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fit_corr_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/fitting.rs:151
-- requires:
--   fit_corr_state
--   fit_corr_final


CREATE AGGREGATE @extschema@.fit_correlation(float8, float8) (
    SFUNC = @extschema@.fit_corr_state,
    STYPE = @extschema@.FitCorrState,
    FINALFUNC = @extschema@.fit_corr_final
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/fitting.rs:71
-- pg_prob::fitting::fit_lognormal_final
CREATE  FUNCTION "fit_lognormal_final"(
	"state" FitState /* core::option::Option<pg_prob::fitting::FitState> */
) RETURNS Dist /* core::option::Option<pg_prob::distribution::Dist> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fit_lognormal_final_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/fitting.rs:57
-- pg_prob::fitting::fit_normal_final
CREATE  FUNCTION "fit_normal_final"(
	"state" FitState /* core::option::Option<pg_prob::fitting::FitState> */
) RETURNS Dist /* core::option::Option<pg_prob::distribution::Dist> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fit_normal_final_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/fitting.rs:47
-- pg_prob::fitting::fit_state
CREATE  FUNCTION "fit_state"(
	"state" FitState, /* core::option::Option<pg_prob::fitting::FitState> */
	"value" double precision /* core::option::Option<f64> */
) RETURNS FitState /* core::option::Option<pg_prob::fitting::FitState> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fit_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/fitting.rs:65
-- pg_prob::fitting::fit_uniform_final
CREATE  FUNCTION "fit_uniform_final"(
	"state" FitState /* core::option::Option<pg_prob::fitting::FitState> */
) RETURNS Dist /* core::option::Option<pg_prob::distribution::Dist> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fit_uniform_final_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/fitting.rs:80
-- requires:
--   fit_state
--   fit_normal_final
--   fit_uniform_final
--   fit_lognormal_final


CREATE AGGREGATE @extschema@.fit_normal(float8) (
    SFUNC = @extschema@.fit_state,
    STYPE = @extschema@.FitState,
    FINALFUNC = @extschema@.fit_normal_final
);

CREATE AGGREGATE @extschema@.fit_uniform(float8) (
    SFUNC = @extschema@.fit_state,
    STYPE = @extschema@.FitState,
    FINALFUNC = @extschema@.fit_uniform_final
);

CREATE AGGREGATE @extschema@.fit_lognormal(float8) (
    SFUNC = @extschema@.fit_state,
    STYPE = @extschema@.FitState,
    FINALFUNC = @extschema@.fit_lognormal_final
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:171
-- pg_prob::distribution::if_above
CREATE  FUNCTION "if_above"(
	"test_dist" Dist, /* pg_prob::distribution::Dist */
	"threshold" double precision, /* f64 */
	"then_dist" Dist, /* pg_prob::distribution::Dist */
	"else_dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'if_above_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:182
-- pg_prob::distribution::if_below
CREATE  FUNCTION "if_below"(
	"test_dist" Dist, /* pg_prob::distribution::Dist */
	"threshold" double precision, /* f64 */
	"then_dist" Dist, /* pg_prob::distribution::Dist */
	"else_dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'if_below_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:193
-- pg_prob::distribution::if_then
CREATE  FUNCTION "if_then"(
	"probability" double precision, /* f64 */
	"then_dist" Dist, /* pg_prob::distribution::Dist */
	"else_dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'if_then_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:90
-- pg_prob::distribution::literal
CREATE  FUNCTION "literal"(
	"value" real /* f32 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'literal_f32_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:79
-- pg_prob::distribution::literal
CREATE  FUNCTION "literal"(
	"value" double precision /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'literal_f64_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:96
-- pg_prob::distribution::literal
CREATE  FUNCTION "literal"(
	"value" INT /* i32 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'literal_i32_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:102
-- pg_prob::distribution::literal
CREATE  FUNCTION "literal"(
	"value" NUMERIC /* pgrx::datum::numeric::AnyNumeric */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'literal_numeric_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:232
-- requires:
--   literal_f64
--   literal_f32
--   literal_i32
--   literal_numeric


CREATE CAST (float8 AS @extschema@.dist)
    WITH FUNCTION @extschema@.literal(float8)
    AS IMPLICIT;

CREATE CAST (float4 AS @extschema@.dist)
    WITH FUNCTION @extschema@.literal(float4)
    AS IMPLICIT;

CREATE CAST (integer AS @extschema@.dist)
    WITH FUNCTION @extschema@.literal(integer)
    AS IMPLICIT;

CREATE CAST (numeric AS @extschema@.dist)
    WITH FUNCTION @extschema@.literal(numeric)
    AS IMPLICIT;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:140
-- pg_prob::distribution::lognormal
CREATE  FUNCTION "lognormal"(
	"mu" double precision, /* f64 */
	"sigma" double precision /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'lognormal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:104
-- pg_prob::sampling::mean
CREATE  FUNCTION "mean"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"n" INT DEFAULT 10000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS double precision /* f64 */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mean_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:111
-- pg_prob::distribution::normal
CREATE  FUNCTION "normal"(
	"mu" double precision, /* f64 */
	"sigma" double precision /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'normal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:268
-- pg_prob::operators::nvl
CREATE  FUNCTION "nvl"(
	"dist" Dist, /* core::option::Option<pg_prob::distribution::Dist> */
	"default" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nvl_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:110
-- pg_prob::sampling::percentile
CREATE  FUNCTION "percentile"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"p" double precision, /* f64 */
	"n" INT DEFAULT 10000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS double precision /* f64 */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'percentile_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:147
-- pg_prob::distribution::pert
CREATE  FUNCTION "pert"(
	"min" double precision, /* f64 */
	"mode" double precision, /* f64 */
	"max" double precision, /* f64 */
	"lambda" double precision DEFAULT 4.0 /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'pert_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:155
-- pg_prob::distribution::poisson
CREATE  FUNCTION "poisson"(
	"lambda" double precision /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poisson_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:75
-- pg_prob::sampling::prob_above
CREATE  FUNCTION "prob_above"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"threshold" double precision, /* f64 */
	"n" INT DEFAULT 10000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS double precision /* f64 */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prob_above_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:64
-- pg_prob::sampling::prob_below
CREATE  FUNCTION "prob_below"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"threshold" double precision, /* f64 */
	"n" INT DEFAULT 10000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS double precision /* f64 */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prob_below_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:86
-- pg_prob::sampling::prob_between
CREATE  FUNCTION "prob_between"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"lower" double precision, /* f64 */
	"upper" double precision, /* f64 */
	"n" INT DEFAULT 10000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS double precision /* f64 */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prob_between_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:30
-- pg_prob::sampling::sample
CREATE  FUNCTION "sample"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS double precision /* f64 */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'sample_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:40
-- pg_prob::sampling::samples
CREATE  FUNCTION "samples"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"n" INT, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS double precision[] /* alloc::vec::Vec<f64> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'samples_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:74
-- pg_prob::operators::scalar_add_dist
CREATE  FUNCTION "scalar_add_dist"(
	"scalar" double precision, /* f64 */
	"dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'scalar_add_dist_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:62
-- pg_prob::operators::scalar_div_dist
CREATE  FUNCTION "scalar_div_dist"(
	"scalar" double precision, /* f64 */
	"dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'scalar_div_dist_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:50
-- pg_prob::operators::scalar_mul_dist
CREATE  FUNCTION "scalar_mul_dist"(
	"scalar" double precision, /* f64 */
	"dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'scalar_mul_dist_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:86
-- pg_prob::operators::scalar_sub_dist
CREATE  FUNCTION "scalar_sub_dist"(
	"scalar" double precision, /* f64 */
	"dist" Dist /* pg_prob::distribution::Dist */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'scalar_sub_dist_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/operators.rs:129
-- requires:
--   dist_add
--   dist_sub
--   dist_mul
--   dist_div
--   dist_mul_scalar
--   scalar_mul_dist
--   dist_div_scalar
--   scalar_div_dist
--   dist_add_scalar
--   scalar_add_dist
--   dist_sub_scalar
--   scalar_sub_dist
--   dist_neg


-- Distribution + Distribution
CREATE OPERATOR @extschema@.+ (
    LEFTARG = @extschema@.dist,
    RIGHTARG = @extschema@.dist,
    FUNCTION = @extschema@.dist_add,
    COMMUTATOR = +
);

-- Distribution - Distribution
CREATE OPERATOR @extschema@.- (
    LEFTARG = @extschema@.dist,
    RIGHTARG = @extschema@.dist,
    FUNCTION = @extschema@.dist_sub
);

-- Distribution * Distribution
CREATE OPERATOR @extschema@.* (
    LEFTARG = @extschema@.dist,
    RIGHTARG = @extschema@.dist,
    FUNCTION = @extschema@.dist_mul,
    COMMUTATOR = *
);

-- Distribution / Distribution
CREATE OPERATOR @extschema@./ (
    LEFTARG = @extschema@.dist,
    RIGHTARG = @extschema@.dist,
    FUNCTION = @extschema@.dist_div
);

-- Distribution * float8
CREATE OPERATOR @extschema@.* (
    LEFTARG = @extschema@.dist,
    RIGHTARG = float8,
    FUNCTION = @extschema@.dist_mul_scalar,
    COMMUTATOR = *
);

-- float8 * Distribution
CREATE OPERATOR @extschema@.* (
    LEFTARG = float8,
    RIGHTARG = @extschema@.dist,
    FUNCTION = @extschema@.scalar_mul_dist,
    COMMUTATOR = *
);

-- Distribution / float8
CREATE OPERATOR @extschema@./ (
    LEFTARG = @extschema@.dist,
    RIGHTARG = float8,
    FUNCTION = @extschema@.dist_div_scalar
);

-- float8 / Distribution
CREATE OPERATOR @extschema@./ (
    LEFTARG = float8,
    RIGHTARG = @extschema@.dist,
    FUNCTION = @extschema@.scalar_div_dist
);

-- Distribution + float8
CREATE OPERATOR @extschema@.+ (
    LEFTARG = @extschema@.dist,
    RIGHTARG = float8,
    FUNCTION = @extschema@.dist_add_scalar,
    COMMUTATOR = +
);

-- float8 + Distribution
CREATE OPERATOR @extschema@.+ (
    LEFTARG = float8,
    RIGHTARG = @extschema@.dist,
    FUNCTION = @extschema@.scalar_add_dist,
    COMMUTATOR = +
);

-- Distribution - float8
CREATE OPERATOR @extschema@.- (
    LEFTARG = @extschema@.dist,
    RIGHTARG = float8,
    FUNCTION = @extschema@.dist_sub_scalar
);

-- float8 - Distribution
CREATE OPERATOR @extschema@.- (
    LEFTARG = float8,
    RIGHTARG = @extschema@.dist,
    FUNCTION = @extschema@.scalar_sub_dist
);

-- Unary minus
CREATE OPERATOR @extschema@.- (
    RIGHTARG = @extschema@.dist,
    FUNCTION = @extschema@.dist_neg
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/simulate.rs:354
-- pg_prob::simulate::simulate
CREATE  FUNCTION "simulate"(
	"source_table" TEXT, /* &str */
	"columns" TEXT[], /* alloc::vec::Vec<alloc::string::String> */
	"n" INT DEFAULT 1000, /* i32 */
	"seed" bigint DEFAULT NULL, /* core::option::Option<i64> */
	"dist_type" TEXT DEFAULT 'normal' /* &str */
) RETURNS TABLE (
	"sample_idx" INT,  /* i32 */
	"values" jsonb  /* pgrx::datum::json::JsonB */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'simulate_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:131
-- pg_prob::sampling::stddev
CREATE  FUNCTION "stddev"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"n" INT DEFAULT 10000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS double precision /* f64 */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stddev_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:50
-- pg_prob::sampling::summarize
CREATE  FUNCTION "summarize"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"n" INT DEFAULT 10000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'summarize_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:123
-- pg_prob::distribution::triangular
CREATE  FUNCTION "triangular"(
	"min" double precision, /* f64 */
	"mode" double precision, /* f64 */
	"max" double precision /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'triangular_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/distribution.rs:117
-- pg_prob::distribution::uniform
CREATE  FUNCTION "uniform"(
	"min" double precision, /* f64 */
	"max" double precision /* f64 */
) RETURNS Dist /* pg_prob::distribution::Dist */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'uniform_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_prob/src/sampling.rs:125
-- pg_prob::sampling::variance
CREATE  FUNCTION "variance"(
	"dist" Dist, /* pg_prob::distribution::Dist */
	"n" INT DEFAULT 10000, /* i32 */
	"seed" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS double precision /* f64 */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'variance_wrapper';
/* </end connected objects> */

