/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/schema.rs:3
-- bootstrap

-- =============================================================================
-- Composite type for rule entries
-- =============================================================================
CREATE TYPE @extschema@.rule_entry AS (
    side        TEXT,
    account     TEXT,
    amount_expr TEXT
);

-- =============================================================================
-- Journal header: groups entries from a single event
-- =============================================================================
CREATE TABLE @extschema@.journal (
    id              BIGSERIAL PRIMARY KEY,
    xact_id         XID8 NOT NULL,
    posted_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    fiscal_period   TEXT,
    source_table    TEXT,
    source_id       TEXT,
    description     TEXT,
    created_by      TEXT DEFAULT current_user
);

CREATE INDEX idx_journal_xact_id ON @extschema@.journal(xact_id);
CREATE INDEX idx_journal_posted_at ON @extschema@.journal(posted_at);

-- =============================================================================
-- Journal entry: individual debit/credit lines
-- =============================================================================
CREATE TABLE @extschema@.journal_entry (
    id              BIGSERIAL PRIMARY KEY,
    journal_id      BIGINT NOT NULL REFERENCES @extschema@.journal(id),
    account         TEXT NOT NULL,
    debit           NUMERIC(19,4) NOT NULL DEFAULT 0,
    credit          NUMERIC(19,4) NOT NULL DEFAULT 0,
    currency        TEXT NOT NULL DEFAULT 'USD',
    base_amount     NUMERIC(19,4),
    CONSTRAINT single_side CHECK (
        (debit > 0 AND credit = 0) OR
        (credit > 0 AND debit = 0) OR
        (debit = 0 AND credit = 0)
    )
);

CREATE INDEX idx_je_journal_id ON @extschema@.journal_entry(journal_id);
CREATE INDEX idx_je_account ON @extschema@.journal_entry(account);

-- =============================================================================
-- Immutability: prevent UPDATE/DELETE on journal tables
-- =============================================================================
CREATE FUNCTION @extschema@.prevent_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'pg_ledger: journal entries are immutable. Use pgledger.reverse() for corrections.';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER journal_immutable
    BEFORE UPDATE OR DELETE ON @extschema@.journal
    FOR EACH ROW EXECUTE FUNCTION @extschema@.prevent_mutation();

CREATE TRIGGER journal_entry_immutable
    BEFORE UPDATE OR DELETE ON @extschema@.journal_entry
    FOR EACH ROW EXECUTE FUNCTION @extschema@.prevent_mutation();

-- =============================================================================
-- Fiscal period: open/close accounting periods
-- =============================================================================
CREATE TABLE @extschema@.fiscal_period (
    period      TEXT PRIMARY KEY,
    status      TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    closed_at   TIMESTAMPTZ,
    closed_by   TEXT
);

-- =============================================================================
-- Exchange rate: currency conversion
-- =============================================================================
CREATE TABLE @extschema@.exchange_rate (
    from_currency   TEXT NOT NULL,
    to_currency     TEXT NOT NULL,
    valid_from      DATE NOT NULL,
    rate            NUMERIC(19,10) NOT NULL,
    valid_to        DATE,
    PRIMARY KEY (from_currency, to_currency, valid_from)
);

-- =============================================================================
-- Rule: account determination rules
-- =============================================================================
CREATE TABLE @extschema@.rule (
    id              SERIAL PRIMARY KEY,
    source_table    TEXT NOT NULL,
    source_column   TEXT NOT NULL,
    entries         @extschema@.rule_entry[] NOT NULL,
    priority        INT NOT NULL DEFAULT 0,
    condition       TEXT,
    description     TEXT,
    currency_column TEXT,
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      TEXT DEFAULT current_user
);

CREATE INDEX idx_rule_source ON @extschema@.rule(source_table, source_column);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:21
-- pg_ledger::types::LedgerAmount
CREATE TYPE LedgerAmount;

-- extensions/pg_ledger/src/types.rs:21
-- pg_ledger::types::ledgeramount_in
CREATE  FUNCTION "ledgeramount_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS LedgerAmount /* core::option::Option<pg_ledger::types::LedgerAmount> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledgeramount_in_wrapper';

-- extensions/pg_ledger/src/types.rs:21
-- pg_ledger::types::ledgeramount_out
CREATE  FUNCTION "ledgeramount_out"(
	"input" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledgeramount_out_wrapper';

-- extensions/pg_ledger/src/types.rs:21
-- pg_ledger::types::LedgerAmount
CREATE TYPE LedgerAmount (
	INTERNALLENGTH = variable,
	INPUT = ledgeramount_in, /* pg_ledger::types::ledgeramount_in */
	OUTPUT = ledgeramount_out, /* pg_ledger::types::ledgeramount_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/queries.rs:5
-- pg_ledger::queries::account_balance
CREATE  FUNCTION "account_balance"(
	"account" TEXT, /* &str */
	"as_of" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"currency" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS NUMERIC /* pgrx::datum::numeric::AnyNumeric */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'account_balance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:292
-- pg_ledger::types::bigint_to_ledger
CREATE  FUNCTION "bigint_to_ledger"(
	"val" bigint /* i64 */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bigint_to_ledger_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/balance.rs:122
-- pg_ledger::balance::check_balance
CREATE  FUNCTION "check_balance"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'check_balance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/fiscal.rs:19
-- pg_ledger::fiscal::close_period
CREATE  FUNCTION "close_period"(
	"period" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'close_period_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/currency.rs:36
-- pg_ledger::currency::convert
CREATE  FUNCTION "convert"(
	"amount" double precision, /* f64 */
	"from_currency" TEXT, /* &str */
	"to_currency" TEXT, /* &str */
	"as_of" date DEFAULT NULL /* core::option::Option<pgrx::datum::date::Date> */
) RETURNS double precision /* f64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'convert_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/rules.rs:5
-- pg_ledger::rules::create_rule
CREATE  FUNCTION "create_rule"(
	"source_table" TEXT, /* &str */
	"source_column" TEXT, /* &str */
	"entries" jsonb, /* pgrx::datum::json::JsonB */
	"condition" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"priority" INT DEFAULT NULL, /* core::option::Option<i32> */
	"description" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"currency_column" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_rule_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/journal.rs:71
-- pg_ledger::journal::credit
CREATE  FUNCTION "credit"(
	"account" TEXT, /* &str */
	"amount" double precision, /* f64 */
	"description" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"currency" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'credit_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/journal.rs:50
-- pg_ledger::journal::debit
CREATE  FUNCTION "debit"(
	"account" TEXT, /* &str */
	"amount" double precision, /* f64 */
	"description" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"currency" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'debit_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/rules.rs:130
-- pg_ledger::rules::disable_rule
CREATE  FUNCTION "disable_rule"(
	"rule_id" INT /* i32 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'disable_rule_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/rules.rs:106
-- pg_ledger::rules::drop_rule
CREATE  FUNCTION "drop_rule"(
	"rule_id" INT /* i32 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_rule_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/rules.rs:120
-- pg_ledger::rules::enable_rule
CREATE  FUNCTION "enable_rule"(
	"rule_id" INT /* i32 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'enable_rule_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/journal.rs:92
-- pg_ledger::journal::entry
CREATE  FUNCTION "entry"(
	"account" TEXT, /* &str */
	"amount" double precision, /* f64 */
	"side" TEXT, /* &str */
	"description" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"currency" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'entry_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:244
-- pg_ledger::types::int_mul_ledger
CREATE  FUNCTION "int_mul_ledger"(
	"a" INT, /* i32 */
	"b" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'int_mul_ledger_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:285
-- pg_ledger::types::int_to_ledger
CREATE  FUNCTION "int_to_ledger"(
	"val" INT /* i32 */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'int_to_ledger_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/queries.rs:114
-- pg_ledger::queries::journal_entries
CREATE  FUNCTION "journal_entries"(
	"from_date" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"to_date" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"account_filter" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"source_table_filter" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TABLE (
	"journal_id" bigint,  /* i64 */
	"posted_at" timestamp with time zone,  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"account" TEXT,  /* alloc::string::String */
	"debit" NUMERIC,  /* pgrx::datum::numeric::AnyNumeric */
	"credit" NUMERIC,  /* pgrx::datum::numeric::AnyNumeric */
	"currency" TEXT,  /* alloc::string::String */
	"description" TEXT,  /* core::option::Option<alloc::string::String> */
	"source_table" TEXT  /* core::option::Option<alloc::string::String> */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'journal_entries_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:221
-- pg_ledger::types::ledger_add
CREATE  FUNCTION "ledger_add"(
	"a" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"b" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_add_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:262
-- pg_ledger::types::ledger_div_int
CREATE  FUNCTION "ledger_div_int"(
	"a" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"b" INT /* i32 */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_div_int_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:268
-- pg_ledger::types::ledger_div_numeric
CREATE  FUNCTION "ledger_div_numeric"(
	"a" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"b" double precision /* f64 */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_div_numeric_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:345
-- pg_ledger::types::ledger_max_state
CREATE  FUNCTION "ledger_max_state"(
	"state" LedgerAmount, /* core::option::Option<pg_ledger::types::LedgerAmount> */
	"value" LedgerAmount /* core::option::Option<pg_ledger::types::LedgerAmount> */
) RETURNS LedgerAmount /* core::option::Option<pg_ledger::types::LedgerAmount> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_max_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:326
-- pg_ledger::types::ledger_min_state
CREATE  FUNCTION "ledger_min_state"(
	"state" LedgerAmount, /* core::option::Option<pg_ledger::types::LedgerAmount> */
	"value" LedgerAmount /* core::option::Option<pg_ledger::types::LedgerAmount> */
) RETURNS LedgerAmount /* core::option::Option<pg_ledger::types::LedgerAmount> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_min_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:238
-- pg_ledger::types::ledger_mul_int
CREATE  FUNCTION "ledger_mul_int"(
	"a" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"b" INT /* i32 */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_mul_int_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:250
-- pg_ledger::types::ledger_mul_numeric
CREATE  FUNCTION "ledger_mul_numeric"(
	"a" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"b" double precision /* f64 */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_mul_numeric_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:233
-- pg_ledger::types::ledger_neg
CREATE  FUNCTION "ledger_neg"(
	"a" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_neg_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:227
-- pg_ledger::types::ledger_sub
CREATE  FUNCTION "ledger_sub"(
	"a" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"b" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_sub_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:313
-- pg_ledger::types::ledger_sum_state
CREATE  FUNCTION "ledger_sum_state"(
	"state" LedgerAmount, /* core::option::Option<pg_ledger::types::LedgerAmount> */
	"value" LedgerAmount /* core::option::Option<pg_ledger::types::LedgerAmount> */
) RETURNS LedgerAmount /* core::option::Option<pg_ledger::types::LedgerAmount> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_sum_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:299
-- pg_ledger::types::ledger_to_numeric
CREATE  FUNCTION "ledger_to_numeric"(
	"val" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_to_numeric_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:304
-- pg_ledger::types::ledger_to_text
CREATE  FUNCTION "ledger_to_text"(
	"val" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_to_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:23
-- pg_ledger::types::ledgeramount_cmp
CREATE  FUNCTION "ledgeramount_cmp"(
	"left" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"right" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledgeramount_cmp_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:22
-- pg_ledger::types::ledgeramount_eq
CREATE  FUNCTION "ledgeramount_eq"(
	"left" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"right" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledgeramount_eq_wrapper';

-- extensions/pg_ledger/src/types.rs:22
-- pg_ledger::types::ledgeramount_eq
CREATE OPERATOR = (
	PROCEDURE="ledgeramount_eq",
	LEFTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	RIGHTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	COMMUTATOR = =,
	NEGATOR = <>,
	RESTRICT = eqsel,
	JOIN = eqjoinsel,
	HASHES,
	MERGES
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:23
-- pg_ledger::types::ledgeramount_ge
CREATE  FUNCTION "ledgeramount_ge"(
	"left" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"right" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledgeramount_ge_wrapper';

-- extensions/pg_ledger/src/types.rs:23
-- pg_ledger::types::ledgeramount_ge
CREATE OPERATOR >= (
	PROCEDURE="ledgeramount_ge",
	LEFTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	RIGHTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	COMMUTATOR = <=,
	NEGATOR = <,
	RESTRICT = scalargesel,
	JOIN = scalargejoinsel
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:23
-- pg_ledger::types::ledgeramount_gt
CREATE  FUNCTION "ledgeramount_gt"(
	"left" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"right" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledgeramount_gt_wrapper';

-- extensions/pg_ledger/src/types.rs:23
-- pg_ledger::types::ledgeramount_gt
CREATE OPERATOR > (
	PROCEDURE="ledgeramount_gt",
	LEFTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	RIGHTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	COMMUTATOR = <,
	NEGATOR = <=,
	RESTRICT = scalargtsel,
	JOIN = scalargtjoinsel
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:24
-- pg_ledger::types::ledgeramount_hash
CREATE  FUNCTION "ledgeramount_hash"(
	"value" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledgeramount_hash_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:23
-- pg_ledger::types::ledgeramount_le
CREATE  FUNCTION "ledgeramount_le"(
	"left" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"right" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledgeramount_le_wrapper';

-- extensions/pg_ledger/src/types.rs:23
-- pg_ledger::types::ledgeramount_le
CREATE OPERATOR <= (
	PROCEDURE="ledgeramount_le",
	LEFTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	RIGHTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	COMMUTATOR = >=,
	NEGATOR = >,
	RESTRICT = scalarlesel,
	JOIN = scalarlejoinsel
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:23
-- pg_ledger::types::ledgeramount_lt
CREATE  FUNCTION "ledgeramount_lt"(
	"left" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"right" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledgeramount_lt_wrapper';

-- extensions/pg_ledger/src/types.rs:23
-- pg_ledger::types::ledgeramount_lt
CREATE OPERATOR < (
	PROCEDURE="ledgeramount_lt",
	LEFTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	RIGHTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	COMMUTATOR = >,
	NEGATOR = >=,
	RESTRICT = scalarltsel,
	JOIN = scalarltjoinsel
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:22
-- pg_ledger::types::ledgeramount_ne
CREATE  FUNCTION "ledgeramount_ne"(
	"left" LedgerAmount, /* pg_ledger::types::LedgerAmount */
	"right" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledgeramount_ne_wrapper';

-- extensions/pg_ledger/src/types.rs:22
-- pg_ledger::types::ledgeramount_ne
CREATE OPERATOR <> (
	PROCEDURE="ledgeramount_ne",
	LEFTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	RIGHTARG=LedgerAmount, /* pg_ledger::types::LedgerAmount */
	COMMUTATOR = <>,
	NEGATOR = =,
	RESTRICT = neqsel,
	JOIN = neqjoinsel
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:256
-- pg_ledger::types::numeric_mul_ledger
CREATE  FUNCTION "numeric_mul_ledger"(
	"a" double precision, /* f64 */
	"b" LedgerAmount /* pg_ledger::types::LedgerAmount */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'numeric_mul_ledger_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:278
-- pg_ledger::types::numeric_to_ledger
CREATE  FUNCTION "numeric_to_ledger"(
	"val" double precision /* f64 */
) RETURNS LedgerAmount /* pg_ledger::types::LedgerAmount */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'numeric_to_ledger_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:368
-- requires:
--   ledger_add
--   ledger_sub
--   ledger_neg
--   ledger_mul_int
--   int_mul_ledger
--   ledger_mul_numeric
--   numeric_mul_ledger
--   ledger_div_int
--   ledger_div_numeric
--   numeric_to_ledger
--   int_to_ledger
--   bigint_to_ledger
--   ledger_to_numeric
--   ledger_to_text
--   ledger_sum_state
--   ledger_min_state
--   ledger_max_state


-- ledger_amount + ledger_amount
CREATE OPERATOR @extschema@.+ (
    LEFTARG = @extschema@.LedgerAmount,
    RIGHTARG = @extschema@.LedgerAmount,
    FUNCTION = @extschema@.ledger_add,
    COMMUTATOR = +
);

-- ledger_amount - ledger_amount
CREATE OPERATOR @extschema@.- (
    LEFTARG = @extschema@.LedgerAmount,
    RIGHTARG = @extschema@.LedgerAmount,
    FUNCTION = @extschema@.ledger_sub
);

-- Unary minus
CREATE OPERATOR @extschema@.- (
    RIGHTARG = @extschema@.LedgerAmount,
    FUNCTION = @extschema@.ledger_neg
);

-- ledger_amount * int4
CREATE OPERATOR @extschema@.* (
    LEFTARG = @extschema@.LedgerAmount,
    RIGHTARG = int4,
    FUNCTION = @extschema@.ledger_mul_int,
    COMMUTATOR = *
);

-- int4 * ledger_amount
CREATE OPERATOR @extschema@.* (
    LEFTARG = int4,
    RIGHTARG = @extschema@.LedgerAmount,
    FUNCTION = @extschema@.int_mul_ledger,
    COMMUTATOR = *
);

-- ledger_amount * float8
CREATE OPERATOR @extschema@.* (
    LEFTARG = @extschema@.LedgerAmount,
    RIGHTARG = float8,
    FUNCTION = @extschema@.ledger_mul_numeric
);

-- float8 * ledger_amount
CREATE OPERATOR @extschema@.* (
    LEFTARG = float8,
    RIGHTARG = @extschema@.LedgerAmount,
    FUNCTION = @extschema@.numeric_mul_ledger
);

-- ledger_amount / int4
CREATE OPERATOR @extschema@./ (
    LEFTARG = @extschema@.LedgerAmount,
    RIGHTARG = int4,
    FUNCTION = @extschema@.ledger_div_int
);

-- ledger_amount / float8
CREATE OPERATOR @extschema@./ (
    LEFTARG = @extschema@.LedgerAmount,
    RIGHTARG = float8,
    FUNCTION = @extschema@.ledger_div_numeric
);

-- Explicit casts
CREATE CAST (float8 AS @extschema@.LedgerAmount)
    WITH FUNCTION @extschema@.numeric_to_ledger(float8);

CREATE CAST (int4 AS @extschema@.LedgerAmount)
    WITH FUNCTION @extschema@.int_to_ledger(int4);

CREATE CAST (int8 AS @extschema@.LedgerAmount)
    WITH FUNCTION @extschema@.bigint_to_ledger(int8);

CREATE CAST (@extschema@.LedgerAmount AS float8)
    WITH FUNCTION @extschema@.ledger_to_numeric(@extschema@.LedgerAmount);

CREATE CAST (@extschema@.LedgerAmount AS text)
    WITH FUNCTION @extschema@.ledger_to_text(@extschema@.LedgerAmount);

-- Aggregates
CREATE AGGREGATE @extschema@.sum(@extschema@.LedgerAmount) (
    SFUNC = @extschema@.ledger_sum_state,
    STYPE = @extschema@.LedgerAmount
);

CREATE AGGREGATE @extschema@.min(@extschema@.LedgerAmount) (
    SFUNC = @extschema@.ledger_min_state,
    STYPE = @extschema@.LedgerAmount
);

CREATE AGGREGATE @extschema@.max(@extschema@.LedgerAmount) (
    SFUNC = @extschema@.ledger_max_state,
    STYPE = @extschema@.LedgerAmount
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/fiscal.rs:5
-- pg_ledger::fiscal::open_period
CREATE  FUNCTION "open_period"(
	"period" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'open_period_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/fiscal.rs:48
-- pg_ledger::fiscal::period_status
CREATE  FUNCTION "period_status"() RETURNS TABLE (
	"period" TEXT,  /* alloc::string::String */
	"status" TEXT,  /* alloc::string::String */
	"closed_at" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"closed_by" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'period_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/journal.rs:167
-- pg_ledger::journal::post_journal
CREATE  FUNCTION "post_journal"(
	"description" TEXT, /* &str */
	"debit_account" TEXT, /* &str */
	"credit_account" TEXT, /* &str */
	"amount" double precision, /* f64 */
	"currency" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"source_ref_type" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"source_ref_id" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'post_journal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/triggers.rs:72
-- pg_ledger::triggers::process_row
CREATE  FUNCTION "process_row"(
	"table_name" TEXT, /* &str */
	"operation" TEXT, /* &str */
	"new_row" jsonb, /* core::option::Option<pgrx::datum::json::JsonB> */
	"old_row" jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'process_row_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/journal.rs:109
-- pg_ledger::journal::reverse
CREATE  FUNCTION "reverse"(
	"journal_id" bigint, /* i64 */
	"reason" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reverse_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/currency.rs:5
-- pg_ledger::currency::set_exchange_rate
CREATE  FUNCTION "set_exchange_rate"(
	"from_currency" TEXT, /* &str */
	"to_currency" TEXT, /* &str */
	"rate" double precision, /* f64 */
	"valid_from" date DEFAULT NULL, /* core::option::Option<pgrx::datum::date::Date> */
	"valid_to" date DEFAULT NULL /* core::option::Option<pgrx::datum::date::Date> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_exchange_rate_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/queries.rs:53
-- pg_ledger::queries::trial_balance
CREATE  FUNCTION "trial_balance"(
	"as_of" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"account_like" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TABLE (
	"account" TEXT,  /* alloc::string::String */
	"total_debit" NUMERIC,  /* pgrx::datum::numeric::AnyNumeric */
	"total_credit" NUMERIC,  /* pgrx::datum::numeric::AnyNumeric */
	"balance" NUMERIC  /* pgrx::datum::numeric::AnyNumeric */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'trial_balance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:23
-- pg_ledger::types::LedgerAmount
CREATE OPERATOR FAMILY LedgerAmount_btree_ops USING btree;
CREATE OPERATOR CLASS LedgerAmount_btree_ops DEFAULT FOR TYPE LedgerAmount USING btree FAMILY LedgerAmount_btree_ops AS
	OPERATOR 1 <,
	OPERATOR 2 <=,
	OPERATOR 3 =,
	OPERATOR 4 >=,
	OPERATOR 5 >,
	FUNCTION 1 ledgeramount_cmp(LedgerAmount, LedgerAmount);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ledger/src/types.rs:24
-- pg_ledger::types::LedgerAmount
CREATE OPERATOR FAMILY LedgerAmount_hash_ops USING hash;
CREATE OPERATOR CLASS LedgerAmount_hash_ops DEFAULT FOR TYPE LedgerAmount USING hash FAMILY LedgerAmount_hash_ops AS
	OPERATOR    1   =  (LedgerAmount, LedgerAmount),
	FUNCTION    1   ledgeramount_hash(LedgerAmount);
/* </end connected objects> */

