/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/schema.rs:3
-- bootstrap

-- =============================================================================
-- currency: ISO 4217 currency master data
-- =============================================================================
CREATE TABLE @extschema@.currency (
    code            TEXT PRIMARY KEY CHECK (length(code) = 3),
    name            TEXT NOT NULL,
    symbol          TEXT,
    decimal_places  SMALLINT NOT NULL DEFAULT 2 CHECK (decimal_places BETWEEN 0 AND 4),
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- exchange_rate: rates relative to base currency (Odoo-inspired model)
-- rate meaning: 1 unit of base currency = rate units of this currency
-- =============================================================================
CREATE TABLE @extschema@.exchange_rate (
    id              BIGSERIAL PRIMARY KEY,
    currency_code   TEXT NOT NULL REFERENCES @extschema@.currency(code) ON DELETE CASCADE,
    rate            NUMERIC(20, 10) NOT NULL CHECK (rate > 0),
    valid_from      DATE NOT NULL DEFAULT CURRENT_DATE,
    rate_type       TEXT DEFAULT NULL,
    source          TEXT DEFAULT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_rate_unique ON @extschema@.exchange_rate(currency_code, valid_from, COALESCE(rate_type, ''));
CREATE INDEX idx_rate_lookup ON @extschema@.exchange_rate(currency_code, valid_from DESC);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/currency.rs:4
-- pg_currency::currency::add_currency
CREATE  FUNCTION "add_currency"(
	"code" TEXT, /* &str */
	"name" TEXT, /* &str */
	"symbol" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"decimal_places" INT DEFAULT 2, /* core::option::Option<i32> */
	"active" bool DEFAULT true /* core::option::Option<bool> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_currency_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/convert.rs:22
-- pg_currency::convert::convert
CREATE  FUNCTION "convert"(
	"amount" NUMERIC, /* pgrx::datum::numeric::AnyNumeric */
	"from_currency" TEXT, /* &str */
	"to_currency" TEXT, /* &str */
	"as_of" date DEFAULT NULL, /* core::option::Option<pgrx::datum::date::Date> */
	"rate_type" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"round" bool DEFAULT true /* core::option::Option<bool> */
) RETURNS NUMERIC /* pgrx::datum::numeric::AnyNumeric */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'convert_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/currency.rs:32
-- pg_currency::currency::drop_currency
CREATE  FUNCTION "drop_currency"(
	"code" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_currency_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/rate.rs:59
-- pg_currency::rate::get_rate
CREATE  FUNCTION "get_rate"(
	"from_currency" TEXT, /* &str */
	"to_currency" TEXT, /* &str */
	"as_of" date DEFAULT NULL, /* core::option::Option<pgrx::datum::date::Date> */
	"rate_type" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS NUMERIC /* pgrx::datum::numeric::AnyNumeric */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_rate_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/queries.rs:5
-- pg_currency::queries::list_currencies
CREATE  FUNCTION "list_currencies"(
	"active_only" bool DEFAULT false /* core::option::Option<bool> */
) RETURNS TABLE (
	"code" TEXT,  /* alloc::string::String */
	"name" TEXT,  /* alloc::string::String */
	"symbol" TEXT,  /* core::option::Option<alloc::string::String> */
	"decimal_places" smallint,  /* i16 */
	"active" bool  /* bool */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_currencies_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/queries.rs:89
-- pg_currency::queries::rate_history
CREATE  FUNCTION "rate_history"(
	"currency_code" TEXT, /* &str */
	"from_date" date DEFAULT NULL, /* core::option::Option<pgrx::datum::date::Date> */
	"to_date" date DEFAULT NULL /* core::option::Option<pgrx::datum::date::Date> */
) RETURNS TABLE (
	"rate" NUMERIC,  /* pgrx::datum::numeric::AnyNumeric */
	"valid_from" date,  /* pgrx::datum::date::Date */
	"rate_type" TEXT,  /* core::option::Option<alloc::string::String> */
	"source" TEXT  /* core::option::Option<alloc::string::String> */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rate_history_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/queries.rs:46
-- pg_currency::queries::rates_as_of
CREATE  FUNCTION "rates_as_of"(
	"as_of" date DEFAULT NULL, /* core::option::Option<pgrx::datum::date::Date> */
	"rate_type" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TABLE (
	"currency_code" TEXT,  /* alloc::string::String */
	"rate" NUMERIC,  /* pgrx::datum::numeric::AnyNumeric */
	"valid_from" date,  /* pgrx::datum::date::Date */
	"source" TEXT  /* core::option::Option<alloc::string::String> */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rates_as_of_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/convert.rs:7
-- pg_currency::convert::round_to_currency
CREATE  FUNCTION "round_to_currency"(
	"amount" NUMERIC, /* pgrx::datum::numeric::AnyNumeric */
	"currency_code" TEXT /* &str */
) RETURNS NUMERIC /* pgrx::datum::numeric::AnyNumeric */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'round_to_currency_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/seed.rs:5
-- pg_currency::seed::seed_iso
CREATE  FUNCTION "seed_iso"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seed_iso_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/currency.rs:48
-- pg_currency::currency::set_active
CREATE  FUNCTION "set_active"(
	"code" TEXT, /* &str */
	"active" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_active_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_currency/src/rate.rs:4
-- pg_currency::rate::set_rate
CREATE  FUNCTION "set_rate"(
	"currency_code" TEXT, /* &str */
	"rate" NUMERIC, /* pgrx::datum::numeric::AnyNumeric */
	"valid_from" date DEFAULT NULL, /* core::option::Option<pgrx::datum::date::Date> */
	"rate_type" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"source" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_rate_wrapper';
/* </end connected objects> */

