/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:29
-- bootstrap

-- Core schema storage table
CREATE TABLE pgregistry.schemas (
    id SERIAL PRIMARY KEY,
    subject TEXT NOT NULL,
    version INT NOT NULL DEFAULT 1,
    schema_def JSONB NOT NULL,
    fingerprint TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (subject, version),
    UNIQUE (subject, fingerprint)
);

CREATE INDEX idx_schemas_subject ON pgregistry.schemas(subject);
CREATE INDEX idx_schemas_fingerprint ON pgregistry.schemas(fingerprint);

-- Schema-to-topic binding table
CREATE TABLE pgregistry.topic_schemas (
    id SERIAL PRIMARY KEY,
    topic_name TEXT NOT NULL,
    schema_type TEXT NOT NULL CHECK (schema_type IN ('key', 'value')),
    schema_id INT NOT NULL REFERENCES pgregistry.schemas(id) ON DELETE CASCADE,
    validation_mode TEXT NOT NULL DEFAULT 'STRICT' CHECK (validation_mode IN ('STRICT', 'LOG')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (topic_name, schema_type)
);

CREATE INDEX idx_topic_schemas_topic ON pgregistry.topic_schemas(topic_name);

-- Table-to-topic binding table for bidirectional Kafka integration
CREATE TABLE pgregistry.table_topic_bindings (
    id SERIAL PRIMARY KEY,
    table_name TEXT NOT NULL UNIQUE,
    schema_id INT REFERENCES pgregistry.schemas(id) ON DELETE SET NULL,
    kafka_topic TEXT NOT NULL,
    mode TEXT NOT NULL CHECK (mode IN ('stream', 'table')),
    key_column TEXT,           -- For table mode: which column is the primary key (from Kafka key)
    offset_column TEXT,        -- For stream mode: auto-increment column for offsets
    kafka_offset_column TEXT,  -- For table mode: column tracking latest kafka offset
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_table_topic_bindings_topic ON pgregistry.table_topic_bindings(kafka_topic);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:135
-- pg_registry::bind_schema_to_topic
CREATE  FUNCTION "bind_schema_to_topic"(
	"topic_name" TEXT, /* &str */
	"schema_id" INT, /* i32 */
	"schema_type" TEXT DEFAULT 'value', /* &str */
	"validation_mode" TEXT DEFAULT 'STRICT' /* &str */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bind_schema_to_topic_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:288
-- pg_registry::bind_table_to_topic
CREATE  FUNCTION "bind_table_to_topic"(
	"table_name" TEXT, /* &str */
	"kafka_topic" TEXT, /* &str */
	"mode" TEXT DEFAULT 'stream' /* &str */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bind_table_to_topic_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:257
-- pg_registry::create_table_from_schema
CREATE  FUNCTION "create_table_from_schema"(
	"table_name" TEXT, /* &str */
	"schema_subject" TEXT, /* &str */
	"add_id_column" bool DEFAULT true /* bool */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_table_from_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:236
-- pg_registry::drop_schema
CREATE  FUNCTION "drop_schema"(
	"schema_id" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:23
-- pg_registry::extension_docs
CREATE  FUNCTION "extension_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'extension_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:103
-- pg_registry::generate_schema_from_table
CREATE  FUNCTION "generate_schema_from_table"(
	"table_name" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'generate_schema_from_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:208
-- pg_registry::get_latest_schema
CREATE  FUNCTION "get_latest_schema"(
	"subject" TEXT /* &str */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_latest_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:196
-- pg_registry::get_schema
CREATE  FUNCTION "get_schema"(
	"schema_id" INT /* i32 */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:316
-- pg_registry::get_table_binding
CREATE  FUNCTION "get_table_binding"(
	"table_name" TEXT /* &str */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_table_binding_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:221
-- pg_registry::get_topic_schema
CREATE  FUNCTION "get_topic_schema"(
	"topic_name" TEXT, /* &str */
	"schema_type" TEXT DEFAULT 'value' /* &str */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_topic_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:88
-- pg_registry::register_schema
CREATE  FUNCTION "register_schema"(
	"subject" TEXT, /* &str */
	"schema_def" jsonb, /* pgrx::datum::json::JsonB */
	"description" TEXT /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:119
-- pg_registry::register_schema_from_table
CREATE  FUNCTION "register_schema_from_table"(
	"subject" TEXT, /* &str */
	"table_name" TEXT, /* &str */
	"description" TEXT /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_schema_from_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:153
-- pg_registry::unbind_schema_from_topic
CREATE  FUNCTION "unbind_schema_from_topic"(
	"topic_name" TEXT, /* &str */
	"schema_type" TEXT DEFAULT 'value' /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unbind_schema_from_topic_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:304
-- pg_registry::unbind_table_from_topic
CREATE  FUNCTION "unbind_table_from_topic"(
	"table_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unbind_table_from_topic_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:166
-- pg_registry::validate
CREATE  FUNCTION "validate"(
	"schema_id" INT, /* i32 */
	"data" jsonb /* pgrx::datum::json::JsonB */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'validate_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_registry/src/lib.rs:180
-- pg_registry::validate_for_topic
CREATE  FUNCTION "validate_for_topic"(
	"topic_name" TEXT, /* &str */
	"data" jsonb, /* pgrx::datum::json::JsonB */
	"schema_type" TEXT DEFAULT 'value' /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'validate_for_topic_wrapper';
/* </end connected objects> */

