/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/schema.rs:3
-- bootstrap

-- =============================================================================
-- Calendar: named working calendars
-- =============================================================================
CREATE TABLE @extschema@.calendar (
    id          SERIAL PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- Weekly pattern: 7 rows per calendar (one per day of week)
-- day_of_week: 0=Sunday, 1=Monday, ..., 6=Saturday (matches EXTRACT(DOW))
-- =============================================================================
CREATE TABLE @extschema@.weekly_pattern (
    id          SERIAL PRIMARY KEY,
    calendar_id INT NOT NULL REFERENCES @extschema@.calendar(id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    is_working  BOOLEAN NOT NULL DEFAULT false,
    UNIQUE(calendar_id, day_of_week)
);

CREATE INDEX idx_weekly_pattern_calendar ON @extschema@.weekly_pattern(calendar_id);

-- =============================================================================
-- Holiday: named non-working days, optionally recurring (month+day match)
-- =============================================================================
CREATE TABLE @extschema@.holiday (
    id           SERIAL PRIMARY KEY,
    calendar_id  INT NOT NULL REFERENCES @extschema@.calendar(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    holiday_date DATE NOT NULL,
    recurring    BOOLEAN NOT NULL DEFAULT false,
    UNIQUE(calendar_id, holiday_date, name)
);

CREATE INDEX idx_holiday_calendar ON @extschema@.holiday(calendar_id);
CREATE INDEX idx_holiday_date ON @extschema@.holiday(holiday_date);

-- =============================================================================
-- Exception: per-date overrides (highest priority)
-- =============================================================================
CREATE TABLE @extschema@.exception (
    id             SERIAL PRIMARY KEY,
    calendar_id    INT NOT NULL REFERENCES @extschema@.calendar(id) ON DELETE CASCADE,
    exception_date DATE NOT NULL,
    is_working     BOOLEAN NOT NULL,
    reason         TEXT,
    UNIQUE(calendar_id, exception_date)
);

CREATE INDEX idx_exception_calendar ON @extschema@.exception(calendar_id);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/exception.rs:6
-- pg_calendar::exception::add_exception
CREATE  FUNCTION "add_exception"(
	"calendar_name" TEXT, /* &str */
	"exception_date" date, /* pgrx::datum::date::Date */
	"is_working" bool, /* bool */
	"reason" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_exception_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/holiday.rs:6
-- pg_calendar::holiday::add_holiday
CREATE  FUNCTION "add_holiday"(
	"calendar_name" TEXT, /* &str */
	"holiday_name" TEXT, /* &str */
	"holiday_date" date, /* pgrx::datum::date::Date */
	"recurring" bool DEFAULT false /* core::option::Option<bool> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_holiday_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/compute.rs:14
-- pg_calendar::compute::add_working_days
CREATE  FUNCTION "add_working_days"(
	"calendar_name" TEXT, /* &str */
	"start_date" date, /* pgrx::datum::date::Date */
	"days" INT /* i32 */
) RETURNS date /* pgrx::datum::date::Date */
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_working_days_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/queries.rs:105
-- pg_calendar::queries::calendar_days
CREATE  FUNCTION "calendar_days"(
	"calendar_name" TEXT, /* &str */
	"from_date" date, /* pgrx::datum::date::Date */
	"to_date" date /* pgrx::datum::date::Date */
) RETURNS TABLE (
	"day_date" TEXT,  /* alloc::string::String */
	"day_name" TEXT,  /* alloc::string::String */
	"is_working" bool,  /* bool */
	"note" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'calendar_days_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/queries.rs:7
-- pg_calendar::queries::calendar_info
CREATE  FUNCTION "calendar_info"(
	"calendar_name" TEXT /* &str */
) RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"description" TEXT,  /* core::option::Option<alloc::string::String> */
	"working_days" TEXT,  /* alloc::string::String */
	"holiday_count" bigint,  /* i64 */
	"exception_count" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'calendar_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/calendar.rs:46
-- pg_calendar::calendar::clone_calendar
CREATE  FUNCTION "clone_calendar"(
	"source_name" TEXT, /* &str */
	"new_name" TEXT, /* &str */
	"description" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'clone_calendar_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/calendar.rs:4
-- pg_calendar::calendar::create_calendar
CREATE  FUNCTION "create_calendar"(
	"name" TEXT, /* &str */
	"description" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_calendar_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/calendar.rs:33
-- pg_calendar::calendar::drop_calendar
CREATE  FUNCTION "drop_calendar"(
	"name" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_calendar_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/compute.rs:7
-- pg_calendar::compute::is_working_day
CREATE  FUNCTION "is_working_day"(
	"calendar_name" TEXT, /* &str */
	"check_date" date /* pgrx::datum::date::Date */
) RETURNS bool /* bool */
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'is_working_day_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/holiday.rs:50
-- pg_calendar::holiday::list_holidays
CREATE  FUNCTION "list_holidays"(
	"calendar_name" TEXT, /* &str */
	"year" INT DEFAULT NULL /* core::option::Option<i32> */
) RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"holiday_date" TEXT,  /* alloc::string::String */
	"recurring" bool  /* bool */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_holidays_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/compute.rs:85
-- pg_calendar::compute::next_working_day
CREATE  FUNCTION "next_working_day"(
	"calendar_name" TEXT, /* &str */
	"from_date" date /* pgrx::datum::date::Date */
) RETURNS date /* pgrx::datum::date::Date */
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'next_working_day_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/compute.rs:102
-- pg_calendar::compute::prev_working_day
CREATE  FUNCTION "prev_working_day"(
	"calendar_name" TEXT, /* &str */
	"from_date" date /* pgrx::datum::date::Date */
) RETURNS date /* pgrx::datum::date::Date */
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prev_working_day_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/exception.rs:33
-- pg_calendar::exception::remove_exception
CREATE  FUNCTION "remove_exception"(
	"calendar_name" TEXT, /* &str */
	"exception_date" date /* pgrx::datum::date::Date */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'remove_exception_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/holiday.rs:32
-- pg_calendar::holiday::remove_holiday
CREATE  FUNCTION "remove_holiday"(
	"calendar_name" TEXT, /* &str */
	"holiday_name" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'remove_holiday_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/seed.rs:6
-- pg_calendar::seed::seed_iso
CREATE  FUNCTION "seed_iso"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seed_iso_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/seed.rs:44
-- pg_calendar::seed::seed_middle_east
CREATE  FUNCTION "seed_middle_east"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seed_middle_east_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/seed.rs:86
-- pg_calendar::seed::seed_six_day
CREATE  FUNCTION "seed_six_day"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seed_six_day_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/pattern.rs:6
-- pg_calendar::pattern::set_weekday
CREATE  FUNCTION "set_weekday"(
	"calendar_name" TEXT, /* &str */
	"day_of_week" INT, /* i32 */
	"is_working" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_weekday_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/pattern.rs:29
-- pg_calendar::pattern::set_working_days
CREATE  FUNCTION "set_working_days"(
	"calendar_name" TEXT, /* &str */
	"days_csv" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_working_days_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/pattern.rs:73
-- pg_calendar::pattern::weekly_pattern
CREATE  FUNCTION "weekly_pattern"(
	"calendar_name" TEXT /* &str */
) RETURNS TABLE (
	"day_of_week" smallint,  /* i16 */
	"day_name" TEXT,  /* alloc::string::String */
	"is_working" bool  /* bool */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'weekly_pattern_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_calendar/src/compute.rs:42
-- pg_calendar::compute::working_days_between
CREATE  FUNCTION "working_days_between"(
	"calendar_name" TEXT, /* &str */
	"start_date" date, /* pgrx::datum::date::Date */
	"end_date" date /* pgrx::datum::date::Date */
) RETURNS INT /* i32 */
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'working_days_between_wrapper';
/* </end connected objects> */

