/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:726
-- bootstrap

-- Datasets ===========================================================
-- `default_srid` is the spatial reference system used when registering
-- new chunks/meshes for this dataset, unless the variable overrides
-- it. Defaults to 4326 (WGS84 geographic) for back-compat — every
-- geographic dataset registered before Phase A behaves identically.
-- SRID 0 means "no spatial reference" (Cartesian XYZ, engineering
-- coords, simulation-space data). Custom EPSG codes (e.g., 3857 web
-- mercator, 28992 Dutch RD) are accepted; PostGIS does the math.
CREATE TABLE pgx.datasets (
    id           BIGSERIAL PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    format       TEXT NOT NULL
                 CHECK (format IN ('zarr', 'netcdf', 'hdf5', 'grib', 'grib2',
                                   'cog', 'selafin', 'med', 'cgns', 'fits',
                                   'memory')),
    conventions  TEXT[],
    default_srid INT NOT NULL DEFAULT 4326,
    metadata     JSONB,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Variables ==========================================================
-- CF-aware columns:
--   * standard_name / units / long_name come from the file's
--     attribute bag (the CF "self-describing" promise)
--   * scale_factor / add_offset / fill_value are the CF "data packing"
--     triple — physical = stored * scale + offset, with bytes-equal-to-
--     fill_value mapped to NaN at decode time
--   * valid_min / valid_max are the CF physical-value envelope (we
--     store but don't enforce; queries can filter on it)
-- `srid` overrides `datasets.default_srid` per-variable. NULL means
-- "inherit". Useful when a single Zarr store mixes geographic
-- coordinate axes (lat/lon, SRID 4326) with model-space data
-- (SRID 0) — register each variable with its own SRID.
CREATE TABLE pgx.variables (
    id            BIGSERIAL PRIMARY KEY,
    dataset_id    BIGINT NOT NULL REFERENCES pgx.datasets(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    standard_name TEXT,
    long_name     TEXT,
    units         TEXT,
    dtype         TEXT,
    dim_order     TEXT[],
    srid          INT,
    scale_factor  DOUBLE PRECISION,
    add_offset    DOUBLE PRECISION,
    fill_value    DOUBLE PRECISION,
    valid_min     DOUBLE PRECISION,
    valid_max     DOUBLE PRECISION,
    metadata      JSONB,
    UNIQUE (dataset_id, name)
);

-- Variable components =================================================
-- Composite (vector / tensor) variables — `velocity = [u, v, w]`,
-- `rgb = [r, g, b]`, `stress = [sxx, syy, szz, sxy, sxz, syz]`. The
-- composite is itself a row in `pgx.variables` (with no chunks of its
-- own); each component is another `pgx.variables` row (typically with
-- its own chunks). `position` is 1-indexed and gives the array
-- ordering returned by `pgx.fetch_vec`.
CREATE TABLE pgx.variable_components (
    id                    BIGSERIAL PRIMARY KEY,
    composite_variable_id BIGINT NOT NULL REFERENCES pgx.variables(id)
                          ON DELETE CASCADE,
    position              INT    NOT NULL CHECK (position >= 1),
    component_name        TEXT   NOT NULL,
    component_variable_id BIGINT NOT NULL REFERENCES pgx.variables(id)
                          ON DELETE CASCADE,
    UNIQUE (composite_variable_id, position),
    UNIQUE (composite_variable_id, component_name)
);

CREATE INDEX variable_components_composite
    ON pgx.variable_components (composite_variable_id, position);

-- Meshes =============================================================
-- One row per logical mesh on a dataset. For fixed meshes that's one
-- row; for versioned/deforming meshes additional rows in
-- pgx.mesh_versions describe per-time-window mesh states.
CREATE TABLE pgx.meshes (
    id          BIGSERIAL PRIMARY KEY,
    dataset_id  BIGINT NOT NULL REFERENCES pgx.datasets(id) ON DELETE CASCADE,
    kind        TEXT NOT NULL
                CHECK (kind IN ('regular_grid', 'curvilinear',
                                'ugrid_triangle', 'ugrid_polygon',
                                'fem_tetra', 'fem_hex', 'voronoi',
                                'particle_cloud', 'time_series', 'profile')),
    motion      TEXT NOT NULL DEFAULT 'fixed'
                CHECK (motion IN ('fixed', 'versioned', 'deforming', 'lagrangian')),
    crs         INT,
    extent      geometry(POLYGON),
    node_count  BIGINT,
    cell_count  BIGINT,
    metadata    JSONB,
    UNIQUE (dataset_id)
);

CREATE INDEX meshes_extent_gist ON pgx.meshes USING GIST (extent);

-- Mesh versions ======================================================
-- Only populated when motion != 'fixed'.
CREATE TABLE pgx.mesh_versions (
    id           BIGSERIAL PRIMARY KEY,
    mesh_id      BIGINT NOT NULL REFERENCES pgx.meshes(id) ON DELETE CASCADE,
    valid_time   TSTZRANGE NOT NULL,
    extent       geometry(POLYGON) NOT NULL,
    uri          TEXT,
    byte_offset  BIGINT,
    byte_length  BIGINT,
    chunk_key    TEXT,
    metadata     JSONB
);

CREATE INDEX mesh_versions_time_gist ON pgx.mesh_versions USING GIST (valid_time);
CREATE INDEX mesh_versions_ext_gist  ON pgx.mesh_versions USING GIST (extent);

-- Mesh nodes ==========================================================
-- Unstructured mesh vertices. One row per file-native node, stamped
-- with the mesh_version it belongs to so deforming meshes can carry
-- multiple geometric realisations of the same node.
--
-- `geom` is PostGIS Point — stored as Point (not PointZ) because
-- PostGIS GIST indexes work fine over Z-coords stuffed into the X/Y
-- envelope via ST_3DEnvelope; for the typical 2D mesh case we just
-- store Point and let `attrs` carry vertical/Z metadata when needed.
-- Real unstructured surface meshes (UGRID polygons, SELAFIN triangles)
-- are 2D and this stays simple. 3D FEM volumes will need PointZ + a
-- dedicated 3D GIST index later (Phase E.2).
CREATE TABLE pgx.mesh_nodes (
    id              BIGSERIAL PRIMARY KEY,
    mesh_version_id BIGINT NOT NULL REFERENCES pgx.mesh_versions(id)
                    ON DELETE CASCADE,
    node_id         BIGINT NOT NULL,
    geom            geometry(POINT) NOT NULL,
    attrs           JSONB,
    UNIQUE (mesh_version_id, node_id)
);

CREATE INDEX mesh_nodes_geom_gist   ON pgx.mesh_nodes USING GIST (geom);
CREATE INDEX mesh_nodes_version_idx ON pgx.mesh_nodes (mesh_version_id);

-- Mesh cells ==========================================================
-- Unstructured mesh elements (triangles, quads, polygons, tetrahedra).
-- `node_ids` is the file-native node-id list bounding the cell, in the
-- order the file uses (CW / CCW preserved). `centroid` is precomputed
-- so spatial queries can prune via GIST without dereferencing each
-- cell's nodes — the typical "values are per-cell" case.
CREATE TABLE pgx.mesh_cells (
    id              BIGSERIAL PRIMARY KEY,
    mesh_version_id BIGINT NOT NULL REFERENCES pgx.mesh_versions(id)
                    ON DELETE CASCADE,
    cell_id         BIGINT NOT NULL,
    node_ids        BIGINT[] NOT NULL,
    centroid        geometry(POINT) NOT NULL,
    attrs           JSONB,
    UNIQUE (mesh_version_id, cell_id)
);

CREATE INDEX mesh_cells_centroid_gist ON pgx.mesh_cells USING GIST (centroid);
CREATE INDEX mesh_cells_version_idx   ON pgx.mesh_cells (mesh_version_id);

-- Chunks =============================================================
-- The hot table. ~1M-100M rows typical.
CREATE TABLE pgx.chunks (
    id              BIGSERIAL PRIMARY KEY,
    variable_id     BIGINT NOT NULL REFERENCES pgx.variables(id) ON DELETE CASCADE,
    mesh_version_id BIGINT REFERENCES pgx.mesh_versions(id),
    time_range      TSTZRANGE,
    level_range     NUMRANGE,
    bbox_envelope   geometry(POLYGON),
    node_range      INT8RANGE,
    member_id       INT,
    uri             TEXT NOT NULL,
    byte_offset     BIGINT,
    byte_length     BIGINT,
    chunk_key       TEXT,
    estimated_cells BIGINT,
    metadata        JSONB,
    indexed_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX chunks_variable     ON pgx.chunks (variable_id);
CREATE INDEX chunks_time_gist    ON pgx.chunks USING GIST (time_range);
CREATE INDEX chunks_bbox_gist    ON pgx.chunks USING GIST (bbox_envelope);
CREATE INDEX chunks_node_gist    ON pgx.chunks USING GIST (node_range);
CREATE INDEX chunks_member       ON pgx.chunks (member_id) WHERE member_id IS NOT NULL;

-- Idempotency for register_chunk: same (variable, time, uri, byte_offset)
-- represents the same chunk. Used by the xarray_index sink's upsert.
-- NULLS NOT DISTINCT (PG15+) so chunks without a byte_offset / time_range
-- (e.g. SELAFIN time-stepped chunks) still dedupe instead of multiplying.
CREATE UNIQUE INDEX chunks_dedupe_idx
    ON pgx.chunks (variable_id, uri, byte_offset, time_range) NULLS NOT DISTINCT;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:937
-- requires:
--   bootstrap_catalog


CREATE FUNCTION pgx.fdw_handler() RETURNS fdw_handler
    AS '$libdir/pg_xarray', 'pgx_fdw_handler_wrapper'
    LANGUAGE C STRICT;

CREATE FUNCTION pgx.fdw_validator(options text[], catalog oid) RETURNS void
    AS '$libdir/pg_xarray', 'pgx_fdw_validator_wrapper'
    LANGUAGE C STRICT;

CREATE FOREIGN DATA WRAPPER pgx_fdw
    HANDLER pgx.fdw_handler
    VALIDATOR pgx.fdw_validator;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:638
-- pg_xarray::chunk_count
CREATE  FUNCTION "chunk_count"(
	"dataset" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'chunk_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:699
-- pg_xarray::dataset_summary
CREATE  FUNCTION "dataset_summary"(
	"dataset" TEXT /* &str */
) RETURNS TABLE (
	"dataset" TEXT,  /* alloc::string::String */
	"format" TEXT,  /* alloc::string::String */
	"default_srid" INT,  /* i32 */
	"n_variables" bigint,  /* i64 */
	"n_composite_variables" bigint,  /* i64 */
	"n_chunks" bigint,  /* i64 */
	"total_bbox_wkt" TEXT,  /* core::option::Option<alloc::string::String> */
	"earliest_time" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"latest_time" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"min_level" double precision,  /* core::option::Option<f64> */
	"max_level" double precision  /* core::option::Option<f64> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dataset_summary_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:367
-- pg_xarray::fetch
CREATE  FUNCTION "fetch"(
	"dataset" TEXT, /* &str */
	"variable" TEXT, /* &str */
	"at_time" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"bbox_wkt" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"level_from" double precision DEFAULT NULL, /* core::option::Option<f64> */
	"level_to" double precision DEFAULT NULL, /* core::option::Option<f64> */
	"max_cells" INT DEFAULT 1000000, /* i32 */
	"time_from" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"time_to" timestamp with time zone DEFAULT NULL /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
) RETURNS TABLE (
	"lat" double precision,  /* core::option::Option<f64> */
	"lon" double precision,  /* core::option::Option<f64> */
	"level" double precision,  /* core::option::Option<f64> */
	"time" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"value" double precision  /* f64 */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fetch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:509
-- pg_xarray::fetch_mesh
CREATE  FUNCTION "fetch_mesh"(
	"dataset" TEXT, /* &str */
	"variable" TEXT, /* &str */
	"at_time" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"bbox_wkt" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"max_cells" INT DEFAULT 1000000, /* i32 */
	"time_from" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"time_to" timestamp with time zone DEFAULT NULL /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
) RETURNS TABLE (
	"node_id" bigint,  /* core::option::Option<i64> */
	"cell_id" bigint,  /* core::option::Option<i64> */
	"geom_wkt" TEXT,  /* core::option::Option<alloc::string::String> */
	"time" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"value" double precision  /* f64 */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fetch_mesh_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:438
-- pg_xarray::fetch_vec
CREATE  FUNCTION "fetch_vec"(
	"dataset" TEXT, /* &str */
	"variable" TEXT, /* &str */
	"at_time" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"bbox_wkt" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"level_from" double precision DEFAULT NULL, /* core::option::Option<f64> */
	"level_to" double precision DEFAULT NULL, /* core::option::Option<f64> */
	"max_cells" INT DEFAULT 1000000, /* i32 */
	"time_from" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"time_to" timestamp with time zone DEFAULT NULL /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
) RETURNS TABLE (
	"lat" double precision,  /* core::option::Option<f64> */
	"lon" double precision,  /* core::option::Option<f64> */
	"level" double precision,  /* core::option::Option<f64> */
	"time" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"values" double precision[]  /* alloc::vec::Vec<f64> */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fetch_vec_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:404
-- pg_xarray::fetch_xyz
CREATE  FUNCTION "fetch_xyz"(
	"dataset" TEXT, /* &str */
	"variable" TEXT, /* &str */
	"at_time" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"bbox_wkt" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"z_from" double precision DEFAULT NULL, /* core::option::Option<f64> */
	"z_to" double precision DEFAULT NULL, /* core::option::Option<f64> */
	"max_cells" INT DEFAULT 1000000, /* i32 */
	"time_from" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"time_to" timestamp with time zone DEFAULT NULL /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
) RETURNS TABLE (
	"x" double precision,  /* core::option::Option<f64> */
	"y" double precision,  /* core::option::Option<f64> */
	"z" double precision,  /* core::option::Option<f64> */
	"time" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"value" double precision  /* f64 */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fetch_xyz_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:468
-- pg_xarray::fetch_xyz_vec
CREATE  FUNCTION "fetch_xyz_vec"(
	"dataset" TEXT, /* &str */
	"variable" TEXT, /* &str */
	"at_time" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"bbox_wkt" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"z_from" double precision DEFAULT NULL, /* core::option::Option<f64> */
	"z_to" double precision DEFAULT NULL, /* core::option::Option<f64> */
	"max_cells" INT DEFAULT 1000000, /* i32 */
	"time_from" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"time_to" timestamp with time zone DEFAULT NULL /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
) RETURNS TABLE (
	"x" double precision,  /* core::option::Option<f64> */
	"y" double precision,  /* core::option::Option<f64> */
	"z" double precision,  /* core::option::Option<f64> */
	"time" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"values" double precision[]  /* alloc::vec::Vec<f64> */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fetch_xyz_vec_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:673
-- pg_xarray::list_chunks
CREATE  FUNCTION "list_chunks"(
	"dataset" TEXT, /* &str */
	"variable" TEXT /* &str */
) RETURNS TABLE (
	"id" bigint,  /* i64 */
	"bbox_wkt" TEXT,  /* core::option::Option<alloc::string::String> */
	"time_lo" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"time_hi" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"level_lo" double precision,  /* core::option::Option<f64> */
	"level_hi" double precision,  /* core::option::Option<f64> */
	"uri" TEXT,  /* alloc::string::String */
	"byte_offset" bigint,  /* core::option::Option<i64> */
	"byte_length" bigint,  /* core::option::Option<i64> */
	"chunk_key" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_chunks_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:624
-- pg_xarray::list_datasets
CREATE  FUNCTION "list_datasets"() RETURNS TABLE (
	"id" bigint,  /* i64 */
	"name" TEXT,  /* alloc::string::String */
	"format" TEXT,  /* alloc::string::String */
	"created_at" timestamp with time zone  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_datasets_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:649
-- pg_xarray::list_variables
CREATE  FUNCTION "list_variables"(
	"dataset" TEXT /* &str */
) RETURNS TABLE (
	"id" bigint,  /* i64 */
	"name" TEXT,  /* alloc::string::String */
	"dtype" TEXT,  /* core::option::Option<alloc::string::String> */
	"units" TEXT,  /* core::option::Option<alloc::string::String> */
	"standard_name" TEXT,  /* core::option::Option<alloc::string::String> */
	"long_name" TEXT,  /* core::option::Option<alloc::string::String> */
	"srid" INT,  /* core::option::Option<i32> */
	"n_components" bigint,  /* i64 */
	"n_chunks" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_variables_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:294
-- pg_xarray::list_zarr_variables
CREATE  FUNCTION "list_zarr_variables"(
	"uri" TEXT /* &str */
) RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"shape" bigint[],  /* alloc::vec::Vec<i64> */
	"dimension_names" TEXT[],  /* alloc::vec::Vec<alloc::string::String> */
	"dtype" TEXT,  /* alloc::string::String */
	"is_data_variable" bool  /* bool */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_zarr_variables_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:181
-- pg_xarray::register_chunk
CREATE  FUNCTION "register_chunk"(
	"dataset" TEXT, /* &str */
	"variable" TEXT, /* &str */
	"uri" TEXT, /* &str */
	"time_from" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"time_to" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"bbox_wkt" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"byte_offset" bigint DEFAULT NULL, /* core::option::Option<i64> */
	"byte_length" bigint DEFAULT NULL, /* core::option::Option<i64> */
	"chunk_key" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"mesh_version_id" bigint DEFAULT NULL, /* core::option::Option<i64> */
	"metadata" jsonb DEFAULT NULL, /* core::option::Option<pgrx::datum::json::JsonB> */
	"level_from" double precision DEFAULT NULL, /* core::option::Option<f64> */
	"level_to" double precision DEFAULT NULL /* core::option::Option<f64> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_chunk_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:52
-- pg_xarray::register_dataset
CREATE  FUNCTION "register_dataset"(
	"name" TEXT, /* &str */
	"format" TEXT, /* &str */
	"conventions" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"metadata" jsonb DEFAULT NULL, /* core::option::Option<pgrx::datum::json::JsonB> */
	"default_srid" INT DEFAULT NULL /* core::option::Option<i32> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_dataset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:250
-- pg_xarray::register_file
CREATE  FUNCTION "register_file"(
	"dataset" TEXT, /* &str */
	"variable" TEXT, /* &str */
	"uri" TEXT, /* &str */
	"format" TEXT DEFAULT 'zarr', /* &str */
	"lat_axis" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"lon_axis" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"time_axis" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"z_axis" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"srid" INT DEFAULT NULL, /* core::option::Option<i32> */
	"x_axis" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"y_axis" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"auto_create" bool DEFAULT true /* bool */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_file_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:105
-- pg_xarray::register_mesh
CREATE  FUNCTION "register_mesh"(
	"dataset" TEXT, /* &str */
	"kind" TEXT, /* &str */
	"motion" TEXT DEFAULT 'fixed', /* &str */
	"crs" INT DEFAULT NULL, /* core::option::Option<i32> */
	"extent_wkt" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"node_count" bigint DEFAULT NULL, /* core::option::Option<i64> */
	"cell_count" bigint DEFAULT NULL, /* core::option::Option<i64> */
	"metadata" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_mesh_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:164
-- pg_xarray::register_mesh_cell
CREATE  FUNCTION "register_mesh_cell"(
	"mesh_version_id" bigint, /* i64 */
	"cell_id" bigint, /* i64 */
	"node_ids" bigint[], /* alloc::vec::Vec<i64> */
	"centroid_wkt" TEXT, /* &str */
	"attrs" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_mesh_cell_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:150
-- pg_xarray::register_mesh_node
CREATE  FUNCTION "register_mesh_node"(
	"mesh_version_id" bigint, /* i64 */
	"node_id" bigint, /* i64 */
	"geom_wkt" TEXT, /* &str */
	"attrs" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_mesh_node_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:122
-- pg_xarray::register_mesh_version
CREATE  FUNCTION "register_mesh_version"(
	"dataset" TEXT, /* &str */
	"valid_from" timestamp with time zone, /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"valid_to" timestamp with time zone, /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"extent_wkt" TEXT, /* &str */
	"uri" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"byte_offset" bigint DEFAULT NULL, /* core::option::Option<i64> */
	"byte_length" bigint DEFAULT NULL, /* core::option::Option<i64> */
	"chunk_key" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"metadata" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_mesh_version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:74
-- pg_xarray::register_variable
CREATE  FUNCTION "register_variable"(
	"dataset" TEXT, /* &str */
	"name" TEXT, /* &str */
	"standard_name" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"units" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"dtype" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"dim_order" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"metadata" jsonb DEFAULT NULL, /* core::option::Option<pgrx::datum::json::JsonB> */
	"srid" INT DEFAULT NULL, /* core::option::Option<i32> */
	"components" TEXT[] DEFAULT NULL /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_variable_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:332
-- pg_xarray::register_zarr_store
CREATE  FUNCTION "register_zarr_store"(
	"dataset" TEXT, /* &str */
	"uri" TEXT, /* &str */
	"lat_axis" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"lon_axis" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"time_axis" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"z_axis" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"srid" INT DEFAULT NULL, /* core::option::Option<i32> */
	"x_axis" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"y_axis" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TABLE (
	"n_variables" bigint,  /* i64 */
	"n_chunks" bigint  /* i64 */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_zarr_store_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:558
-- pg_xarray::xarray_to_glb
CREATE  FUNCTION "xarray_to_glb"(
	"dataset" TEXT, /* &str */
	"surface_var" TEXT, /* &str */
	"color_var" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"flow_uv" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"time_from" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"time_to" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"bbox_wkt" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"colormap" TEXT DEFAULT 'viridis', /* &str */
	"z_scale" double precision DEFAULT 1.0, /* f64 */
	"options" jsonb DEFAULT NULL, /* core::option::Option<pgrx::datum::json::JsonB> */
	"target_srid" INT DEFAULT 4326 /* i32 */
) RETURNS bytea /* alloc::vec::Vec<u8> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'xarray_to_glb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_xarray/src/lib.rs:596
-- pg_xarray::xarray_to_png
CREATE  FUNCTION "xarray_to_png"(
	"dataset" TEXT, /* &str */
	"surface_var" TEXT, /* &str */
	"at_time" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"bbox_wkt" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"width" INT DEFAULT 512, /* i32 */
	"height" INT DEFAULT 512, /* i32 */
	"colormap" TEXT DEFAULT 'viridis', /* &str */
	"options" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS bytea /* alloc::vec::Vec<u8> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'xarray_to_png_wrapper';
/* </end connected objects> */

