[package]
name = "pg_ortools"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "pgrx_embed_pg_ortools"
path = "./src/bin/pgrx_embed.rs"

[features]
default = ["pg16"]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14", "ortools_core/pg14"]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15", "ortools_core/pg15"]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16", "ortools_core/pg16"]
pg17 = ["pgrx/pg17", "pgrx-tests/pg17", "ortools_core/pg17"]
pg18 = ["pgrx/pg18", "pgrx-tests/pg18", "ortools_core/pg18"]
pg_test = []

[dependencies]
pgrx.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
ortools_core = { path = "../../crates/ortools_core" }

[dev-dependencies]
pgrx-tests.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
tokio-postgres.workspace = true
serde_json.workspace = true
