/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:57
-- bootstrap

-- Executor registry with health monitoring
CREATE TABLE pgswarm.executors (
    id                    BIGSERIAL PRIMARY KEY,
    name                  TEXT NOT NULL UNIQUE,
    function_name         TEXT NOT NULL,
    description           TEXT,
    total_runs            BIGINT NOT NULL DEFAULT 0,
    total_failures        BIGINT NOT NULL DEFAULT 0,
    consecutive_failures  INT NOT NULL DEFAULT 0,
    max_consecutive_failures INT NOT NULL DEFAULT 5,
    last_failure_at       TIMESTAMPTZ,
    last_error            TEXT,
    health_status         TEXT NOT NULL DEFAULT 'healthy'
                          CHECK (health_status IN ('healthy', 'degraded', 'disabled')),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Node registry
CREATE TABLE pgswarm.nodes (
    id              BIGSERIAL PRIMARY KEY,
    node_name       TEXT NOT NULL,
    pid             INT NOT NULL,
    workers_count   INT NOT NULL DEFAULT 2,
    status          TEXT NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'draining', 'dead')),
    last_heartbeat  TIMESTAMPTZ NOT NULL DEFAULT now(),
    registered_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata        JSONB DEFAULT '{}'
);

CREATE INDEX idx_nodes_heartbeat ON pgswarm.nodes (last_heartbeat);
CREATE UNIQUE INDEX idx_nodes_pid ON pgswarm.nodes (pid);

-- Jobs: high-level units of work
CREATE TABLE pgswarm.jobs (
    id              BIGSERIAL PRIMARY KEY,
    executor_name   TEXT NOT NULL REFERENCES pgswarm.executors(name),
    payload         JSONB NOT NULL DEFAULT '{}',
    chunk_count     INT NOT NULL DEFAULT 1,
    priority        INT NOT NULL DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'running', 'completed', 'failed', 'cancelled')),
    scheduling      TEXT NOT NULL DEFAULT 'greedy'
                    CHECK (scheduling IN ('greedy', 'round_robin')),
    result_table    TEXT,
    max_retries     INT NOT NULL DEFAULT 3,
    task_timeout    INT NOT NULL DEFAULT 3600,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    created_by      TEXT NOT NULL DEFAULT current_user,
    metadata        JSONB DEFAULT '{}'
);

CREATE INDEX idx_jobs_status ON pgswarm.jobs (status);
CREATE INDEX idx_jobs_created ON pgswarm.jobs (created_at);

-- Tasks: individual units of work (one per chunk per job)
CREATE TABLE pgswarm.tasks (
    id              BIGSERIAL PRIMARY KEY,
    job_id          BIGINT NOT NULL REFERENCES pgswarm.jobs(id) ON DELETE CASCADE,
    chunk_index     INT NOT NULL,
    chunk_id        TEXT,
    priority        INT NOT NULL DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'running', 'completed', 'failed', 'cancelled')),
    node_id         BIGINT REFERENCES pgswarm.nodes(id) ON DELETE SET NULL,
    assigned_node_id BIGINT REFERENCES pgswarm.nodes(id) ON DELETE SET NULL,
    retry_count     INT NOT NULL DEFAULT 0,
    max_retries     INT NOT NULL DEFAULT 3,
    timeout_secs    INT NOT NULL DEFAULT 3600,
    payload         JSONB NOT NULL DEFAULT '{}',
    result          JSONB,
    error_message   TEXT,
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_tasks_status ON pgswarm.tasks (status);
CREATE INDEX idx_tasks_job_id ON pgswarm.tasks (job_id);
CREATE INDEX idx_tasks_node_id ON pgswarm.tasks (node_id) WHERE node_id IS NOT NULL;
CREATE INDEX idx_tasks_pending ON pgswarm.tasks (priority DESC, created_at ASC)
    WHERE status = 'pending';

-- Aggressive autovacuum for high-churn task table
ALTER TABLE pgswarm.tasks SET (
    autovacuum_vacuum_scale_factor = 0.01,
    autovacuum_analyze_scale_factor = 0.005
);

-- Watches: continuous source table monitoring
-- Links a source table to an executor for automatic task creation.
-- The node manager polls watched tables and creates jobs from new rows.
CREATE TABLE pgswarm.watches (
    id              BIGSERIAL PRIMARY KEY,
    source_table    TEXT NOT NULL,
    executor_name   TEXT NOT NULL REFERENCES pgswarm.executors(name),
    job_payload     JSONB NOT NULL DEFAULT '{}',
    batch_size      INT NOT NULL DEFAULT 100,
    poll_interval   INT NOT NULL DEFAULT 5,
    priority        INT NOT NULL DEFAULT 0,
    max_retries     INT NOT NULL DEFAULT 3,
    task_timeout    INT NOT NULL DEFAULT 3600,
    scheduling      TEXT NOT NULL DEFAULT 'greedy'
                    CHECK (scheduling IN ('greedy', 'round_robin')),
    result_table    TEXT,
    enabled         BOOLEAN NOT NULL DEFAULT true,
    last_processed_id BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(source_table, executor_name)
);

-- Job progress view
CREATE VIEW pgswarm.job_progress AS
SELECT
    j.id AS job_id,
    j.executor_name,
    j.status AS job_status,
    j.chunk_count AS total_tasks,
    COUNT(*) FILTER (WHERE t.status = 'completed') AS completed,
    COUNT(*) FILTER (WHERE t.status = 'failed') AS failed,
    COUNT(*) FILTER (WHERE t.status = 'running') AS running,
    COUNT(*) FILTER (WHERE t.status = 'pending') AS pending,
    COUNT(*) FILTER (WHERE t.status = 'cancelled') AS cancelled,
    j.created_at,
    j.started_at,
    j.completed_at,
    CASE WHEN j.completed_at IS NOT NULL
         THEN j.completed_at - j.started_at
         WHEN j.started_at IS NOT NULL
         THEN now() - j.started_at
         ELSE NULL
    END AS duration
FROM pgswarm.jobs j
LEFT JOIN pgswarm.tasks t ON t.job_id = j.id
GROUP BY j.id;

-- Node status view
CREATE VIEW pgswarm.node_status AS
SELECT
    n.id AS node_id,
    n.node_name,
    n.pid,
    n.status,
    n.workers_count,
    n.last_heartbeat,
    now() - n.last_heartbeat AS time_since_heartbeat,
    COUNT(t.id) FILTER (WHERE t.status = 'running') AS active_tasks,
    COUNT(t.id) FILTER (WHERE t.status = 'completed') AS completed_tasks,
    COUNT(t.id) FILTER (WHERE t.status = 'failed') AS failed_tasks
FROM pgswarm.nodes n
LEFT JOIN pgswarm.tasks t ON t.node_id = n.id
GROUP BY n.id;

-- Executor health view
CREATE VIEW pgswarm.executor_health AS
SELECT
    e.id,
    e.name,
    e.function_name,
    e.health_status,
    e.total_runs,
    e.total_failures,
    e.consecutive_failures,
    e.max_consecutive_failures,
    CASE WHEN e.total_runs > 0
         THEN round((e.total_failures::numeric / e.total_runs::numeric) * 100, 1)
         ELSE 0
    END AS failure_rate_pct,
    e.last_failure_at,
    e.last_error,
    e.created_at
FROM pgswarm.executors e
ORDER BY e.consecutive_failures DESC;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1559
-- pg_swarm::activate_node
CREATE  FUNCTION "activate_node"(
	"node_id" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'activate_node_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1220
-- pg_swarm::cancel_job
CREATE  FUNCTION "cancel_job"(
	"job_id" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cancel_job_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:979
-- pg_swarm::create_result_table
CREATE  FUNCTION "create_result_table"(
	"table_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_result_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:997
-- pg_swarm::create_source_table
CREATE  FUNCTION "create_source_table"(
	"table_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_source_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1547
-- pg_swarm::drain_node
CREATE  FUNCTION "drain_node"(
	"node_id" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drain_node_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1590
-- pg_swarm::executor_stats
CREATE  FUNCTION "executor_stats"(
	"name" TEXT /* &str */
) RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"health_status" TEXT,  /* alloc::string::String */
	"total_runs" bigint,  /* i64 */
	"total_failures" bigint,  /* i64 */
	"consecutive_failures" INT,  /* i32 */
	"failure_rate_pct" double precision,  /* f64 */
	"last_error" TEXT,  /* core::option::Option<alloc::string::String> */
	"last_failure_at" timestamp with time zone  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'executor_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1278
-- pg_swarm::get_job
CREATE  FUNCTION "get_job"(
	"job_id" bigint /* i64 */
) RETURNS TABLE (
	"id" bigint,  /* i64 */
	"executor_name" TEXT,  /* alloc::string::String */
	"payload" jsonb,  /* pgrx::datum::json::JsonB */
	"chunk_count" INT,  /* i32 */
	"status" TEXT,  /* alloc::string::String */
	"priority" INT,  /* i32 */
	"created_at" timestamp with time zone,  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"started_at" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"completed_at" timestamp with time zone  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_job_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1465
-- pg_swarm::get_task_results
CREATE  FUNCTION "get_task_results"(
	"job_id" bigint /* i64 */
) RETURNS TABLE (
	"chunk_index" INT,  /* i32 */
	"result" jsonb,  /* core::option::Option<pgrx::datum::json::JsonB> */
	"completed_at" timestamp with time zone  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_task_results_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1395
-- pg_swarm::get_tasks
CREATE  FUNCTION "get_tasks"(
	"job_id" bigint /* i64 */
) RETURNS TABLE (
	"id" bigint,  /* i64 */
	"chunk_index" INT,  /* i32 */
	"chunk_id" TEXT,  /* core::option::Option<alloc::string::String> */
	"status" TEXT,  /* alloc::string::String */
	"node_id" bigint,  /* core::option::Option<i64> */
	"assigned_node_id" bigint,  /* core::option::Option<i64> */
	"retry_count" INT,  /* i32 */
	"result" jsonb,  /* core::option::Option<pgrx::datum::json::JsonB> */
	"error_message" TEXT,  /* core::option::Option<alloc::string::String> */
	"started_at" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"completed_at" timestamp with time zone  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_tasks_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:435
-- pg_swarm::list_executors
CREATE  FUNCTION "list_executors"() RETURNS TABLE (
	"id" bigint,  /* i64 */
	"name" TEXT,  /* alloc::string::String */
	"function_name" TEXT,  /* alloc::string::String */
	"description" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_executors_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1347
-- pg_swarm::list_jobs
CREATE  FUNCTION "list_jobs"(
	"status_filter" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TABLE (
	"id" bigint,  /* i64 */
	"executor_name" TEXT,  /* alloc::string::String */
	"status" TEXT,  /* alloc::string::String */
	"chunk_count" INT,  /* i32 */
	"priority" INT,  /* i32 */
	"created_at" timestamp with time zone  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_jobs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1507
-- pg_swarm::list_nodes
CREATE  FUNCTION "list_nodes"() RETURNS TABLE (
	"id" bigint,  /* i64 */
	"node_name" TEXT,  /* alloc::string::String */
	"pid" INT,  /* i32 */
	"status" TEXT,  /* alloc::string::String */
	"workers_count" INT,  /* i32 */
	"last_heartbeat" timestamp with time zone  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_nodes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1165
-- pg_swarm::list_watches
CREATE  FUNCTION "list_watches"() RETURNS TABLE (
	"id" bigint,  /* i64 */
	"source_table" TEXT,  /* alloc::string::String */
	"executor_name" TEXT,  /* alloc::string::String */
	"batch_size" INT,  /* i32 */
	"poll_interval" INT,  /* i32 */
	"result_table" TEXT,  /* core::option::Option<alloc::string::String> */
	"last_processed_id" bigint,  /* i64 */
	"enabled" bool  /* bool */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_watches_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:396
-- pg_swarm::register_executor
CREATE  FUNCTION "register_executor"(
	"name" TEXT, /* &str */
	"function_name" TEXT, /* &str */
	"description" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_executor_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1574
-- pg_swarm::reset_executor
CREATE  FUNCTION "reset_executor"(
	"name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reset_executor_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:250
-- pg_swarm::reset_workers
CREATE  FUNCTION "reset_workers"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reset_workers_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1243
-- pg_swarm::retry_job
CREATE  FUNCTION "retry_job"(
	"job_id" bigint /* i64 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'retry_job_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1659
-- pg_swarm::status
CREATE  FUNCTION "status"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:478
-- pg_swarm::submit_job
CREATE  FUNCTION "submit_job"(
	"executor_name" TEXT, /* &str */
	"payload" jsonb DEFAULT '{}', /* pgrx::datum::json::JsonB */
	"chunk_count" INT DEFAULT 1, /* i32 */
	"priority" INT DEFAULT 0, /* i32 */
	"max_retries" INT DEFAULT 3, /* i32 */
	"task_timeout" INT DEFAULT 3600, /* i32 */
	"scheduling" TEXT DEFAULT 'greedy', /* &str */
	"result_table" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'submit_job_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:699
-- pg_swarm::submit_job_from_table
CREATE  FUNCTION "submit_job_from_table"(
	"executor_name" TEXT, /* &str */
	"source_table" TEXT, /* &str */
	"job_payload" jsonb DEFAULT '{}', /* pgrx::datum::json::JsonB */
	"priority" INT DEFAULT 0, /* i32 */
	"max_retries" INT DEFAULT 3, /* i32 */
	"task_timeout" INT DEFAULT 3600, /* i32 */
	"scheduling" TEXT DEFAULT 'greedy', /* &str */
	"result_table" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'submit_job_from_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:574
-- pg_swarm::submit_job_with_chunks
CREATE  FUNCTION "submit_job_with_chunks"(
	"executor_name" TEXT, /* &str */
	"chunks" jsonb, /* pgrx::datum::json::JsonB */
	"job_payload" jsonb DEFAULT '{}', /* pgrx::datum::json::JsonB */
	"priority" INT DEFAULT 0, /* i32 */
	"max_retries" INT DEFAULT 3, /* i32 */
	"task_timeout" INT DEFAULT 3600, /* i32 */
	"scheduling" TEXT DEFAULT 'greedy', /* &str */
	"result_table" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'submit_job_with_chunks_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1057
-- pg_swarm::swarm_count
CREATE  FUNCTION "swarm_count"(
	"table_name" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'swarm_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1016
-- pg_swarm::swarm_insert
CREATE  FUNCTION "swarm_insert"(
	"table_name" TEXT, /* &str */
	"payload" jsonb /* pgrx::datum::json::JsonB */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'swarm_insert_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1036
-- pg_swarm::swarm_insert_batch
CREATE  FUNCTION "swarm_insert_batch"(
	"table_name" TEXT, /* &str */
	"payloads" jsonb /* pgrx::datum::json::JsonB */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'swarm_insert_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:424
-- pg_swarm::unregister_executor
CREATE  FUNCTION "unregister_executor"(
	"name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unregister_executor_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1153
-- pg_swarm::unwatch_source_table
CREATE  FUNCTION "unwatch_source_table"(
	"source_table" TEXT, /* &str */
	"executor_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unwatch_source_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:1083
-- pg_swarm::watch_source_table
CREATE  FUNCTION "watch_source_table"(
	"source_table" TEXT, /* &str */
	"executor_name" TEXT, /* &str */
	"job_payload" jsonb DEFAULT '{}', /* pgrx::datum::json::JsonB */
	"batch_size" INT DEFAULT 100, /* i32 */
	"poll_interval" INT DEFAULT 5, /* i32 */
	"priority" INT DEFAULT 0, /* i32 */
	"max_retries" INT DEFAULT 3, /* i32 */
	"task_timeout" INT DEFAULT 3600, /* i32 */
	"scheduling" TEXT DEFAULT 'greedy', /* &str */
	"result_table" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'watch_source_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_swarm/src/lib.rs:250
-- pg_swarm::worker_status
CREATE  FUNCTION "worker_status"() RETURNS TABLE (
	"worker" INT,  /* i32 */
	"name" TEXT,  /* alloc::string::String */
	"state" TEXT,  /* alloc::string::String */
	"failures" INT,  /* i32 */
	"restarts" INT,  /* i32 */
	"pid" INT,  /* i32 */
	"since" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"last_failure" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'worker_status_wrapper';
/* </end connected objects> */

