/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:276
-- bootstrap

-- Stream configuration table
CREATE TABLE delta.streams (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    direction TEXT NOT NULL CHECK (direction IN ('ingest', 'export')),
    uri TEXT NOT NULL,
    pg_table TEXT NOT NULL,
    mode TEXT NOT NULL,
    poll_interval_ms INTEGER,
    batch_size INTEGER,
    flush_interval_ms INTEGER,
    start_version BIGINT,
    tracking_column TEXT,
    key_columns TEXT[],
    storage_options JSONB,
    enabled BOOLEAN NOT NULL DEFAULT true,
    status TEXT NOT NULL DEFAULT 'stopped' CHECK (status IN ('running', 'stopped', 'error')),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Stream progress tracking (table-level)
CREATE TABLE delta.stream_progress (
    stream_id INTEGER PRIMARY KEY REFERENCES delta.streams(id) ON DELETE CASCADE,
    delta_version BIGINT,
    pg_lsn PG_LSN,
    last_value JSONB,
    rows_synced BIGINT NOT NULL DEFAULT 0,
    bytes_synced BIGINT NOT NULL DEFAULT 0,
    last_sync_at TIMESTAMPTZ,
    last_error_at TIMESTAMPTZ,
    error_count INTEGER NOT NULL DEFAULT 0
);

-- Partition-level progress tracking for efficient incremental sync
CREATE TABLE delta.partition_progress (
    id BIGSERIAL PRIMARY KEY,
    stream_id INTEGER NOT NULL REFERENCES delta.streams(id) ON DELETE CASCADE,
    partition_values JSONB NOT NULL,        -- {"year": 2024, "month": 1}
    partition_path TEXT NOT NULL,            -- "year=2024/month=01"
    delta_version BIGINT NOT NULL,           -- Version when this partition was last synced
    files_processed TEXT[],                  -- List of file paths already processed
    rows_synced BIGINT NOT NULL DEFAULT 0,
    last_sync_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(stream_id, partition_path)
);

-- Index for efficient partition lookup
CREATE INDEX idx_partition_progress_stream_path
    ON delta.partition_progress(stream_id, partition_path);

-- Index for finding stale partitions
CREATE INDEX idx_partition_progress_stream_version
    ON delta.partition_progress(stream_id, delta_version);

-- Error log for debugging
CREATE TABLE delta.stream_errors (
    id BIGSERIAL PRIMARY KEY,
    stream_id INTEGER REFERENCES delta.streams(id) ON DELETE CASCADE,
    error_type TEXT NOT NULL,
    error_message TEXT NOT NULL,
    context JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for efficient error lookup
CREATE INDEX idx_stream_errors_stream_occurred
    ON delta.stream_errors(stream_id, occurred_at DESC);

-- Update trigger for updated_at
CREATE OR REPLACE FUNCTION delta.update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER streams_updated_at
    BEFORE UPDATE ON delta.streams
    FOR EACH ROW EXECUTE FUNCTION delta.update_timestamp();

-- Managed Delta tables - tracks tables created via create_table()
CREATE TABLE delta.tables (
    id SERIAL PRIMARY KEY,
    pg_table TEXT UNIQUE NOT NULL,               -- Target Postgres table (schema.table)
    delta_uri TEXT NOT NULL,                     -- Delta Lake URI (s3://, file://, etc.)
    partition_columns TEXT[],                    -- Partition columns from Delta metadata
    delta_version BIGINT NOT NULL DEFAULT 0,     -- Last synced Delta version
    storage_options JSONB,                       -- Per-table storage credentials override
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_refresh_at TIMESTAMPTZ
);

-- Track partition sync state for managed tables
CREATE TABLE delta.table_partitions (
    id BIGSERIAL PRIMARY KEY,
    table_id INTEGER NOT NULL REFERENCES delta.tables(id) ON DELETE CASCADE,
    partition_path TEXT NOT NULL,                 -- "year=2024/month=01"
    partition_values JSONB NOT NULL,              -- {"year": 2024, "month": 1}
    delta_version BIGINT NOT NULL,                -- Version when partition was last synced
    files_processed TEXT[],                       -- Files already synced
    rows_synced BIGINT NOT NULL DEFAULT 0,
    last_sync_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(table_id, partition_path)
);

-- Index for partition lookup
CREATE INDEX idx_table_partitions_table_path
    ON delta.table_partitions(table_id, partition_path);

CREATE TRIGGER tables_updated_at
    BEFORE UPDATE ON delta.tables
    FOR EACH ROW EXECUTE FUNCTION delta.update_timestamp();

-- Export tables - tracks Postgres tables exported to Delta via export_table()
CREATE TABLE delta.export_tables (
    id SERIAL PRIMARY KEY,
    pg_table TEXT UNIQUE NOT NULL,               -- Source Postgres table (schema.table)
    delta_uri TEXT NOT NULL,                     -- Delta Lake URI (s3://, file://, etc.)
    partition_columns TEXT[],                    -- Columns to partition by in Delta
    tracking_column TEXT,                        -- Column to detect changes (e.g., updated_at)
    last_tracking_value TEXT,                    -- Last value of tracking column exported
    delta_version BIGINT NOT NULL DEFAULT 0,     -- Current Delta table version
    storage_options JSONB,                       -- Per-table storage credentials override
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_export_at TIMESTAMPTZ
);

-- Track partition export state
CREATE TABLE delta.export_partitions (
    id BIGSERIAL PRIMARY KEY,
    export_id INTEGER NOT NULL REFERENCES delta.export_tables(id) ON DELETE CASCADE,
    partition_path TEXT NOT NULL,                 -- "year=2024/month=01"
    partition_values JSONB NOT NULL,              -- {"year": 2024, "month": 1}
    last_tracking_value TEXT,                     -- Last tracking value for this partition
    rows_exported BIGINT NOT NULL DEFAULT 0,
    last_export_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(export_id, partition_path)
);

-- Index for partition lookup
CREATE INDEX idx_export_partitions_export_path
    ON delta.export_partitions(export_id, partition_path);

CREATE TRIGGER export_tables_updated_at
    BEFORE UPDATE ON delta.export_tables
    FOR EACH ROW EXECUTE FUNCTION delta.update_timestamp();
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/index/catalog.rs:12
-- requires:
--   bootstrap_schema


-- Catalogued Delta tables (index mode). One row per indexed table.
CREATE TABLE delta.indexed_tables (
    id              BIGSERIAL PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    location        TEXT NOT NULL,
    current_version BIGINT NOT NULL,
    schema_snapshot JSONB NOT NULL,                 -- column → {type, ordinal}
    partition_keys  TEXT[],
    storage_options JSONB,                          -- per-table credential override
    indexed_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Per-file catalog: the pruning index. Rows stay in parquet.
CREATE TABLE delta.files (
    id               BIGSERIAL PRIMARY KEY,
    table_id         BIGINT NOT NULL REFERENCES delta.indexed_tables(id) ON DELETE CASCADE,
    delta_version    BIGINT NOT NULL,
    path             TEXT NOT NULL,                 -- relative to indexed_tables.location
    size_bytes       BIGINT NOT NULL,
    num_records      BIGINT,
    partition_values JSONB,
    column_stats     JSONB,                         -- {"col":{"min":..,"max":..,"null_count":N}}
    has_dv           BOOLEAN NOT NULL DEFAULT false,
    modification_ts  TIMESTAMPTZ,
    UNIQUE (table_id, delta_version, path)
);

CREATE INDEX files_table            ON delta.files (table_id);
CREATE INDEX files_table_version    ON delta.files (table_id, delta_version);
CREATE INDEX files_partition_gin    ON delta.files USING GIN (partition_values);
CREATE INDEX files_column_stats_gin ON delta.files USING GIN (column_stats jsonb_path_ops);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/index/fdw.rs:574
-- requires:
--   index_catalog


CREATE FUNCTION delta.fdw_handler() RETURNS fdw_handler
    AS '$libdir/pg_delta', 'delta_fdw_handler' LANGUAGE C STRICT;

CREATE FUNCTION delta.fdw_validator(text[], oid) RETURNS void
    AS '$libdir/pg_delta', 'delta_fdw_validator' LANGUAGE C STRICT;

CREATE FOREIGN DATA WRAPPER pg_delta_fdw
    HANDLER delta.fdw_handler
    VALIDATOR delta.fdw_validator;

CREATE SERVER pg_delta_server FOREIGN DATA WRAPPER pg_delta_fdw;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:829
-- pg_delta::create_table
CREATE  FUNCTION "create_table"(
	"uri" TEXT, /* &str */
	"pg_table" TEXT, /* &str */
	"storage_options" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:1006
-- pg_delta::drop_export
CREATE  FUNCTION "drop_export"(
	"pg_table" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_export_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:1093
-- pg_delta::drop_index
CREATE  FUNCTION "drop_index"(
	"name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_index_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:871
-- pg_delta::drop_table
CREATE  FUNCTION "drop_table"(
	"pg_table" TEXT, /* &str */
	"drop_table" bool DEFAULT false /* bool */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:991
-- pg_delta::export
CREATE  FUNCTION "export"(
	"pg_table" TEXT, /* &str */
	"full_export" bool DEFAULT false /* bool */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'export_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:957
-- pg_delta::export_table
CREATE  FUNCTION "export_table"(
	"pg_table" TEXT, /* &str */
	"uri" TEXT, /* &str */
	"partition_by" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"tracking_column" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"storage_options" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'export_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:1134
-- pg_delta::extension_docs
CREATE  FUNCTION "extension_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'extension_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:1116
-- pg_delta::fetch
CREATE  FUNCTION "fetch"(
	"table" TEXT, /* &str */
	"filter" jsonb DEFAULT '{}', /* pgrx::datum::json::JsonB */
	"columns" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"max_rows" bigint DEFAULT 1000000 /* i64 */
) RETURNS SETOF jsonb /* pgrx::datum::json::JsonB */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fetch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:796
-- pg_delta::history
CREATE  FUNCTION "history"(
	"uri" TEXT, /* &str */
	"limit" INT DEFAULT 10 /* core::option::Option<i32> */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'history_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:1105
-- pg_delta::index_info
CREATE  FUNCTION "index_info"(
	"name" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'index_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:1076
-- pg_delta::index_table
CREATE  FUNCTION "index_table"(
	"name" TEXT, /* &str */
	"location" TEXT, /* &str */
	"storage_options" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'index_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:784
-- pg_delta::info
CREATE  FUNCTION "info"(
	"uri" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:1012
-- pg_delta::list_exports
CREATE  FUNCTION "list_exports"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_exports_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:1099
-- pg_delta::list_indexes
CREATE  FUNCTION "list_indexes"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_indexes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:877
-- pg_delta::list_tables
CREATE  FUNCTION "list_tables"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_tables_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:749
-- pg_delta::read
CREATE  FUNCTION "read"(
	"uri" TEXT, /* &str */
	"pg_table" TEXT, /* &str */
	"mode" TEXT DEFAULT 'replace', /* &str */
	"version" bigint DEFAULT NULL, /* core::option::Option<i64> */
	"timestamp" timestamp with time zone DEFAULT NULL /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'read_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:855
-- pg_delta::refresh
CREATE  FUNCTION "refresh"(
	"pg_table" TEXT, /* &str */
	"full_refresh" bool DEFAULT false /* bool */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'refresh_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:1087
-- pg_delta::refresh_index
CREATE  FUNCTION "refresh_index"(
	"name" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'refresh_index_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:790
-- pg_delta::schema
CREATE  FUNCTION "schema"(
	"uri" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:476
-- pg_delta::status
CREATE  FUNCTION "status"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:508
-- pg_delta::stream_create
CREATE  FUNCTION "stream_create"(
	"name" TEXT, /* &str */
	"uri" TEXT, /* &str */
	"pg_table" TEXT, /* &str */
	"direction" TEXT, /* &str */
	"mode" TEXT DEFAULT 'append', /* &str */
	"poll_interval_ms" INT DEFAULT NULL, /* core::option::Option<i32> */
	"batch_size" INT DEFAULT NULL, /* core::option::Option<i32> */
	"flush_interval_ms" INT DEFAULT NULL, /* core::option::Option<i32> */
	"start_version" bigint DEFAULT NULL, /* core::option::Option<i64> */
	"tracking_column" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"key_columns" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"storage_options" jsonb DEFAULT NULL, /* core::option::Option<pgrx::datum::json::JsonB> */
	"enabled" bool DEFAULT true /* bool */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stream_create_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:682
-- pg_delta::stream_drop
CREATE  FUNCTION "stream_drop"(
	"name" TEXT, /* &str */
	"force" bool DEFAULT false /* bool */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stream_drop_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:717
-- pg_delta::stream_reset
CREATE  FUNCTION "stream_reset"(
	"name" TEXT, /* &str */
	"version" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS bool /* bool */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stream_reset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:618
-- pg_delta::stream_start
CREATE  FUNCTION "stream_start"(
	"name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stream_start_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:650
-- pg_delta::stream_stop
CREATE  FUNCTION "stream_stop"(
	"name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stream_stop_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:802
-- pg_delta::test_storage
CREATE  FUNCTION "test_storage"(
	"uri" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'test_storage_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_delta/src/lib.rs:761
-- pg_delta::write
CREATE  FUNCTION "write"(
	"uri" TEXT, /* &str */
	"query" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"pg_table" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"mode" TEXT DEFAULT 'append', /* &str */
	"partition_by" TEXT[] DEFAULT NULL /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'write_wrapper';
/* </end connected objects> */

