/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/eidos_oauth/src/lib.rs:184
-- eidos_oauth::oauth_docs
CREATE  FUNCTION "oauth_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'oauth_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/eidos_oauth/src/lib.rs:126
-- eidos_oauth::oauth_get_claim
CREATE  FUNCTION "oauth_get_claim"(
	"token" TEXT, /* &str */
	"claim" TEXT /* &str */
) RETURNS TEXT /* core::option::Option<alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'oauth_get_claim_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/eidos_oauth/src/lib.rs:143
-- eidos_oauth::oauth_inject_claims
CREATE  FUNCTION "oauth_inject_claims"(
	"token" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'oauth_inject_claims_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/eidos_oauth/src/lib.rs:158
-- eidos_oauth::oauth_jwks_status
CREATE  FUNCTION "oauth_jwks_status"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'oauth_jwks_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/eidos_oauth/src/lib.rs:168
-- eidos_oauth::oauth_refresh_jwks
CREATE  FUNCTION "oauth_refresh_jwks"() RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'oauth_refresh_jwks_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/eidos_oauth/src/lib.rs:114
-- eidos_oauth::oauth_validate_token
CREATE  FUNCTION "oauth_validate_token"(
	"token" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'oauth_validate_token_wrapper';
/* </end connected objects> */

