/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/eidos_catalog.rs:27

-- ============================================================================
-- pg_ml eidos_catalog contract — v1
--   Spec: https://github.com/matroidbe/eidos/blob/main/docs/development/eidos-catalog-contract.md
-- ============================================================================

-- Type mapping helper. Mirrors eidos-core's discover.rs::pg_type_to_eidos
-- exactly. Eidos cross-checks each arg/return pg_type → eidos_type at
-- discovery-time; a divergence here fails plugin import.
CREATE OR REPLACE FUNCTION _eidos_pg_to_eidos_type(udt_name TEXT)
RETURNS TEXT LANGUAGE sql IMMUTABLE SET search_path = pgml, public AS $body$
    SELECT CASE lower(udt_name)
        WHEN 'int2'        THEN 'integer'
        WHEN 'int4'        THEN 'integer'
        WHEN 'int8'        THEN 'integer'
        WHEN 'smallint'    THEN 'integer'
        WHEN 'integer'     THEN 'integer'
        WHEN 'bigint'      THEN 'integer'
        WHEN 'float4'      THEN 'decimal'
        WHEN 'float8'      THEN 'decimal'
        WHEN 'numeric'     THEN 'decimal'
        WHEN 'decimal'     THEN 'decimal'
        WHEN 'real'        THEN 'decimal'
        WHEN 'bool'        THEN 'boolean'
        WHEN 'boolean'     THEN 'boolean'
        WHEN 'text'        THEN 'text'
        WHEN 'varchar'     THEN 'text'
        WHEN 'bpchar'      THEN 'text'
        WHEN 'character'   THEN 'text'
        WHEN 'date'        THEN 'date'
        WHEN 'timestamp'   THEN 'timestamp'
        WHEN 'timestamptz' THEN 'timestamp'
        WHEN 'uuid'        THEN 'uuid'
        WHEN 'jsonb'       THEN 'jsonb'
        WHEN 'json'        THEN 'jsonb'
        WHEN 'money'       THEN 'money'
        WHEN 'bytea'       THEN 'bytea'
        ELSE 'text /* ' || udt_name || ' */'
    END;
$body$;

-- Helper: build the args JSONB for a function from pg_proc so the live
-- signature is the source of truth. Returns NULL if the function doesn't exist
-- (so the catalog fails fast on schema drift), '[]' for a zero-arg function.
CREATE OR REPLACE FUNCTION _eidos_args_for(p_schema TEXT, p_func TEXT, descs JSONB DEFAULT '{}'::jsonb)
RETURNS JSONB LANGUAGE sql STABLE SET search_path = pgml, public AS $body$
    WITH proc AS (
        SELECT p.oid, p.proargnames, p.proargtypes, p.pronargs, p.pronargdefaults
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = p_schema AND p.proname = p_func
        -- Deterministic on overloaded names: lowest oid = earliest-created.
        ORDER BY p.oid
        LIMIT 1
    ),
    args AS (
        SELECT
            COALESCE(proc.proargnames[i+1], 'arg' || (i+1)::text) AS name,
            format_type(proc.proargtypes[i], NULL)              AS pg_type_full,
            (SELECT typname FROM pg_type WHERE oid = proc.proargtypes[i]) AS udt,
            (i+1) > (proc.pronargs - proc.pronargdefaults)      AS has_default,
            i AS pos
        FROM proc, generate_series(0, proc.pronargs - 1) i
    )
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'name',        a.name,
        'pg_type',     a.pg_type_full,
        'eidos_type',  _eidos_pg_to_eidos_type(a.udt),
        'required',    NOT a.has_default,
        'description', descs->a.name
    ) ORDER BY a.pos), CASE WHEN EXISTS (SELECT 1 FROM proc) THEN '[]'::jsonb END)
    FROM args a;
$body$;

-- Helper: build the returns descriptor from pg_proc.
CREATE OR REPLACE FUNCTION _eidos_returns_for(p_schema TEXT, p_func TEXT, p_shape TEXT DEFAULT 'scalar')
RETURNS JSONB LANGUAGE sql STABLE SET search_path = pgml, public AS $body$
    WITH proc AS (
        SELECT format_type(p.prorettype, NULL) AS pg_type_full,
               (SELECT typname FROM pg_type WHERE oid = p.prorettype) AS udt
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = p_schema AND p.proname = p_func
        ORDER BY p.oid
        LIMIT 1
    )
    SELECT jsonb_build_object(
        'pg_type',    pg_type_full,
        'eidos_type', _eidos_pg_to_eidos_type(udt),
        'shape',      p_shape
    ) FROM proc;
$body$;

-- ============================================================================
-- eidos_catalog_meta — required
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_meta() RETURNS jsonb
LANGUAGE sql STABLE SET search_path = pgml, public AS $body$
    SELECT jsonb_build_object(
        'extension',      'pg_ml',
        -- Read the installed version live so meta can never go stale against
        -- the actual extension.
        'version',        COALESCE((SELECT extversion FROM pg_extension WHERE extname = 'pg_ml'), '0.0.0'),
        'eidos_protocol', '1',
        'display_name',   'PyCaret ML',
        'description',    'PyCaret AutoML in PostgreSQL: experiment setup, training, inference and embeddings',
        'icon',           'cpu',
        'primary_color',  '#ec4899',
        'domains',        ARRAY['ml']
    );
$body$;

-- ============================================================================
-- eidos_catalog_entities — required
-- pg_ml owns its own experiment store, not Eidos entities. Return zero rows.
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_entities() RETURNS TABLE (
    name              text,
    schema_name       text,
    table_name        text,
    primary_key       text[],
    columns           jsonb,
    domain            text,
    display_name      text,
    icon              text,
    read_only         boolean,
    fsm_machine       text,
    default_sort      text,
    search_columns    text[]
) LANGUAGE sql STABLE SET search_path = pgml, public AS $body$
    SELECT NULL::text, NULL::text, NULL::text, NULL::text[], NULL::jsonb,
           NULL::text, NULL::text, NULL::text, NULL::boolean, NULL::text,
           NULL::text, NULL::text[]
    WHERE false;
$body$;

-- ============================================================================
-- eidos_catalog_functions — required
--
-- The curated public surface. SIGNATURES come from pg_proc via
-- _eidos_args_for / _eidos_returns_for (no drift possible); the side-effect
-- class + display metadata are authored here.
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_functions() RETURNS TABLE (
    name              text,
    schema_name       text,
    args              jsonb,
    returns           jsonb,
    side_effects      text,
    fsm_event         jsonb,
    suggested_roles   text[],
    domain            text,
    display_name      text,
    icon              text,
    danger            boolean
) LANGUAGE sql STABLE SET search_path = pgml, public AS $body$
    WITH defs(name, side_effects, domain, display_name, icon, danger, return_shape) AS (
        VALUES
            ('predict'        , 'query'  , 'ml', 'Predict'              , 'sparkles'     , false, 'scalar'),
            ('predict_row'    , 'query'  , 'ml', 'Predict (by name)'    , 'sparkles'     , false, 'scalar'),
            ('predict_proba'  , 'query'  , 'ml', 'Predict probabilities', 'percent'      , false, 'scalar'),
            ('predict_proba_row', 'query', 'ml', 'Probabilities (by name)', 'percent'    , false, 'scalar'),
            ('predict_dist'   , 'query'  , 'ml', 'Predict distribution' , 'bar-chart-3'  , false, 'scalar'),
            ('embed'          , 'query'  , 'ml', 'Embed text'           , 'vector-square', false, 'scalar'),
            ('training_status', 'query'  , 'ml', 'Training status'      , 'activity'     , false, 'jsonb'),
            ('setup'          , 'mutates', 'ml', 'Setup experiment'     , 'settings'     , false, 'scalar'),
            ('create_model'   , 'mutates', 'ml', 'Create model'         , 'plus-circle'  , false, 'scalar'),
            ('compare_models' , 'mutates', 'ml', 'Compare models'       , 'git-compare'  , false, 'scalar'),
            ('start_training' , 'mutates', 'ml', 'Train (async)'        , 'play-circle'  , false, 'scalar'),
            ('cancel_training', 'mutates', 'ml', 'Cancel training'      , 'x-circle'     , true , 'scalar'),
            ('deploy'         , 'mutates', 'ml', 'Deploy model'         , 'rocket'       , false, 'scalar'),
            ('drop_project'   , 'mutates', 'ml', 'Drop project'         , 'trash-2'      , true , 'scalar')
    )
    SELECT
        d.name,
        'pgml'::text                                           AS schema_name,
        _eidos_args_for('pgml', d.name)                        AS args,
        _eidos_returns_for('pgml', d.name, d.return_shape)     AS returns,
        d.side_effects,
        NULL::jsonb                                                AS fsm_event,
        ARRAY['admin']::text[]                                     AS suggested_roles,
        d.domain,
        d.display_name,
        d.icon,
        d.danger
    FROM defs d;
$body$;

GRANT EXECUTE ON FUNCTION _eidos_pg_to_eidos_type(text)        TO PUBLIC;
GRANT EXECUTE ON FUNCTION _eidos_args_for(text, text, jsonb)   TO PUBLIC;
GRANT EXECUTE ON FUNCTION _eidos_returns_for(text, text, text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_meta()                 TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_entities()             TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_functions()            TO PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/async_training_sql.rs:245
-- pg_ml::async_training_sql::cancel_training
CREATE  FUNCTION "cancel_training"(
	"job_id" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cancel_training_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:273
-- pg_ml::sql_functions::compare_models
CREATE  FUNCTION "compare_models"(
	"project_name" TEXT, /* &str */
	"n_select" INT DEFAULT 1, /* core::option::Option<i32> */
	"sort" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"include" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"exclude" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"budget_time" INT DEFAULT 1800, /* core::option::Option<i32> */
	"deploy" bool DEFAULT true /* bool */
) RETURNS TABLE (
	"project_id" bigint,  /* i64 */
	"model_id" bigint,  /* i64 */
	"algorithm" TEXT,  /* alloc::string::String */
	"task" TEXT,  /* alloc::string::String */
	"metrics" jsonb,  /* pgrx::datum::json::JsonB */
	"deployed" bool  /* bool */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'compare_models_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:610
-- pg_ml::sql_functions::compare_ts_models
CREATE  FUNCTION "compare_ts_models"(
	"project_name" TEXT, /* &str */
	"n_select" INT DEFAULT 1, /* core::option::Option<i32> */
	"sort" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"include" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"exclude" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"budget_time" INT DEFAULT 1800, /* core::option::Option<i32> */
	"deploy" bool DEFAULT true /* bool */
) RETURNS TABLE (
	"project_id" bigint,  /* i64 */
	"model_id" bigint,  /* i64 */
	"algorithm" TEXT,  /* alloc::string::String */
	"task" TEXT,  /* alloc::string::String */
	"metrics" jsonb,  /* pgrx::datum::json::JsonB */
	"deployed" bool  /* bool */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'compare_ts_models_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:367
-- pg_ml::sql_functions::create_model
CREATE  FUNCTION "create_model"(
	"project_name" TEXT, /* &str */
	"algorithm" TEXT, /* &str */
	"hyperparams" jsonb DEFAULT NULL, /* core::option::Option<pgrx::datum::json::JsonB> */
	"deploy" bool DEFAULT true, /* bool */
	"conformal" bool DEFAULT false, /* bool */
	"conformal_method" TEXT DEFAULT 'plus', /* &str */
	"conformal_cv" INT DEFAULT 5 /* i32 */
) RETURNS TABLE (
	"project_id" bigint,  /* i64 */
	"model_id" bigint,  /* i64 */
	"algorithm" TEXT,  /* alloc::string::String */
	"task" TEXT,  /* alloc::string::String */
	"metrics" jsonb,  /* pgrx::datum::json::JsonB */
	"deployed" bool,  /* bool */
	"conformal" bool  /* bool */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_model_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:544
-- pg_ml::sql_functions::create_ts_model
CREATE  FUNCTION "create_ts_model"(
	"project_name" TEXT, /* &str */
	"algorithm" TEXT, /* &str */
	"hyperparams" jsonb DEFAULT NULL, /* core::option::Option<pgrx::datum::json::JsonB> */
	"deploy" bool DEFAULT true /* bool */
) RETURNS TABLE (
	"project_id" bigint,  /* i64 */
	"model_id" bigint,  /* i64 */
	"algorithm" TEXT,  /* alloc::string::String */
	"task" TEXT,  /* alloc::string::String */
	"metrics" jsonb,  /* pgrx::datum::json::JsonB */
	"deployed" bool  /* bool */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_ts_model_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:1340
-- pg_ml::sql_functions::current_experiment
CREATE  FUNCTION "current_experiment"() RETURNS TABLE (
	"project_name" TEXT,  /* core::option::Option<alloc::string::String> */
	"task" TEXT,  /* core::option::Option<alloc::string::String> */
	"target_column" TEXT,  /* core::option::Option<alloc::string::String> */
	"feature_columns" TEXT[],  /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"data_rows" bigint,  /* core::option::Option<i64> */
	"data_cols" bigint  /* core::option::Option<i64> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'current_experiment_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:965
-- pg_ml::sql_functions::deploy
CREATE  FUNCTION "deploy"(
	"model_id" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'deploy_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:974
-- pg_ml::sql_functions::drop_project
CREATE  FUNCTION "drop_project"(
	"project_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_project_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:1228
-- pg_ml::sql_functions::embed
CREATE  FUNCTION "embed"(
	"input" TEXT, /* &str */
	"provider" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"model" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS real[] /* alloc::vec::Vec<f32> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'embed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:1272
-- pg_ml::sql_functions::embed_batch
CREATE  FUNCTION "embed_batch"(
	"inputs" TEXT[] /* alloc::vec::Vec<alloc::string::String> */
) RETURNS TABLE (
	"index" INT,  /* i32 */
	"embedding" real[]  /* alloc::vec::Vec<f32> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'embed_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:1294
-- pg_ml::sql_functions::embedding_info
CREATE  FUNCTION "embedding_info"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'embedding_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/lib.rs:46
-- pg_ml::extension_docs
CREATE  FUNCTION "extension_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'extension_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:685
-- pg_ml::sql_functions::forecast
CREATE  FUNCTION "forecast"(
	"project_name" TEXT, /* &str */
	"fh" INT DEFAULT NULL, /* core::option::Option<i32> */
	"return_pred_int" bool DEFAULT false, /* bool */
	"alpha" double precision DEFAULT 0.05 /* f64 */
) RETURNS TABLE (
	"step" INT,  /* i32 */
	"timestamp" TEXT,  /* alloc::string::String */
	"prediction" double precision,  /* f64 */
	"lower" double precision,  /* core::option::Option<f64> */
	"upper" double precision  /* core::option::Option<f64> */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'forecast_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:1201
-- pg_ml::sql_functions::init
CREATE  FUNCTION "init"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'init_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:1334
-- pg_ml::sql_functions::kernel_status
CREATE  FUNCTION "kernel_status"() RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'kernel_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:170
-- pg_ml::sql_functions::list_datasets
CREATE  FUNCTION "list_datasets"() RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"task" TEXT,  /* core::option::Option<alloc::string::String> */
	"rows" bigint,  /* core::option::Option<i64> */
	"features" bigint  /* core::option::Option<i64> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_datasets_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:125
-- pg_ml::sql_functions::load_dataset
CREATE  FUNCTION "load_dataset"(
	"name" TEXT, /* &str */
	"schema_name" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"table_name" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"if_exists" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TABLE (
	"schema_name" TEXT,  /* alloc::string::String */
	"table_name" TEXT,  /* alloc::string::String */
	"row_count" bigint,  /* i64 */
	"columns" TEXT[]  /* alloc::vec::Vec<alloc::string::String> */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'load_dataset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:1100
-- pg_ml::sql_functions::load_experiment
CREATE  FUNCTION "load_experiment"(
	"project_name" TEXT /* &str */
) RETURNS TABLE (
	"experiment_id" TEXT,  /* alloc::string::String */
	"task" TEXT,  /* alloc::string::String */
	"target_column" TEXT,  /* alloc::string::String */
	"feature_columns" TEXT[],  /* alloc::vec::Vec<alloc::string::String> */
	"train_size" double precision,  /* f64 */
	"fold" INT,  /* i32 */
	"model_id" bigint,  /* core::option::Option<i64> */
	"algorithm" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'load_experiment_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/mlflow.rs:299
-- pg_ml::mlflow::mlflow_status
CREATE  FUNCTION "mlflow_status"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mlflow_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/mlflow.rs:322
-- pg_ml::mlflow::mlflow_url
CREATE  FUNCTION "mlflow_url"() RETURNS TEXT /* core::option::Option<alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mlflow_url_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:775
-- pg_ml::sql_functions::predict
CREATE  FUNCTION "predict"(
	"project_name" TEXT, /* &str */
	"features" double precision[] /* alloc::vec::Vec<f64> */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'predict_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:922
-- pg_ml::sql_functions::predict_batch
CREATE  FUNCTION "predict_batch"(
	"project_name" TEXT, /* &str */
	"relation_name" TEXT, /* &str */
	"id_column" TEXT, /* &str */
	"feature_columns" TEXT[] DEFAULT NULL /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
) RETURNS TABLE (
	"id" TEXT,  /* alloc::string::String */
	"prediction" TEXT  /* alloc::string::String */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'predict_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:884
-- pg_ml::sql_functions::predict_dist
CREATE  FUNCTION "predict_dist"(
	"project_name" TEXT, /* &str */
	"features" double precision[], /* alloc::vec::Vec<f64> */
	"alpha" double precision DEFAULT 0.1, /* f64 */
	"dist_type" TEXT DEFAULT 'triangular' /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'predict_dist_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:854
-- pg_ml::sql_functions::predict_interval
CREATE  FUNCTION "predict_interval"(
	"project_name" TEXT, /* &str */
	"features" double precision[], /* alloc::vec::Vec<f64> */
	"alpha" double precision DEFAULT 0.1 /* f64 */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'predict_interval_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:835
-- pg_ml::sql_functions::predict_proba
CREATE  FUNCTION "predict_proba"(
	"project_name" TEXT, /* &str */
	"features" double precision[] /* alloc::vec::Vec<f64> */
) RETURNS double precision[] /* alloc::vec::Vec<f64> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'predict_proba_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:820
-- pg_ml::sql_functions::predict_proba_row
CREATE  FUNCTION "predict_proba_row"(
	"project_name" TEXT, /* &str */
	"row" jsonb /* pgrx::datum::json::JsonB */
) RETURNS double precision[] /* alloc::vec::Vec<f64> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'predict_proba_row_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:796
-- pg_ml::sql_functions::predict_row
CREATE  FUNCTION "predict_row"(
	"project_name" TEXT, /* &str */
	"row" jsonb /* pgrx::datum::json::JsonB */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'predict_row_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:38
-- pg_ml::sql_functions::python_info
CREATE  FUNCTION "python_info"() RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'python_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/lib.rs:61
-- pg_ml::reset_workers
CREATE  FUNCTION "reset_workers"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reset_workers_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:198
-- pg_ml::sql_functions::setup
CREATE  FUNCTION "setup"(
	"relation_name" TEXT, /* &str */
	"target" TEXT, /* &str */
	"project_name" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"task" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"exclude_columns" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"options" jsonb DEFAULT NULL, /* core::option::Option<pgrx::datum::json::JsonB> */
	"id_column" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TABLE (
	"experiment_id" TEXT,  /* alloc::string::String */
	"task" TEXT,  /* alloc::string::String */
	"target_column" TEXT,  /* alloc::string::String */
	"feature_columns" TEXT[],  /* alloc::vec::Vec<alloc::string::String> */
	"train_size" double precision,  /* f64 */
	"fold" INT  /* i32 */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'setup_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:474
-- pg_ml::sql_functions::setup_timeseries
CREATE  FUNCTION "setup_timeseries"(
	"relation_name" TEXT, /* &str */
	"target" TEXT, /* &str */
	"index" TEXT, /* &str */
	"project_name" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"fh" INT DEFAULT 12, /* i32 */
	"fold" INT DEFAULT 3, /* i32 */
	"fold_strategy" TEXT DEFAULT 'expanding', /* &str */
	"session_id" INT DEFAULT NULL /* core::option::Option<i32> */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'setup_timeseries_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:21
-- pg_ml::sql_functions::setup_venv
CREATE  FUNCTION "setup_venv"() RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'setup_venv_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:1322
-- pg_ml::sql_functions::shutdown
CREATE  FUNCTION "shutdown"() RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'shutdown_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/async_training_sql.rs:61
-- pg_ml::async_training_sql::start_training
CREATE  FUNCTION "start_training"(
	"project_name" TEXT, /* &str */
	"source_table" TEXT, /* &str */
	"target_column" TEXT, /* &str */
	"algorithm" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"automl" bool DEFAULT false, /* bool */
	"task" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"exclude_columns" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"train_size" double precision DEFAULT 0.8, /* f64 */
	"budget_time" INT DEFAULT NULL, /* core::option::Option<i32> */
	"conformal" bool DEFAULT false, /* bool */
	"conformal_method" TEXT DEFAULT 'plus', /* &str */
	"metric" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"hyperparams" jsonb DEFAULT NULL, /* core::option::Option<pgrx::datum::json::JsonB> */
	"setup_options" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'start_training_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/async_training_sql.rs:186
-- pg_ml::async_training_sql::start_ts_training
CREATE  FUNCTION "start_ts_training"(
	"project_name" TEXT, /* &str */
	"source_table" TEXT, /* &str */
	"target_column" TEXT, /* &str */
	"index_column" TEXT, /* &str */
	"algorithm" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"automl" bool DEFAULT false, /* bool */
	"fh" INT DEFAULT 12, /* i32 */
	"fold_strategy" TEXT DEFAULT 'expanding', /* &str */
	"budget_time" INT DEFAULT NULL, /* core::option::Option<i32> */
	"metric" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"hyperparams" jsonb DEFAULT NULL, /* core::option::Option<pgrx::datum::json::JsonB> */
	"setup_options" jsonb DEFAULT NULL /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'start_ts_training_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:91
-- pg_ml::sql_functions::status
CREATE  FUNCTION "status"() RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/async_training_sql.rs:135
-- pg_ml::async_training_sql::training_status
CREATE  FUNCTION "training_status"(
	"job_id" bigint /* i64 */
) RETURNS TABLE (
	"job_id" bigint,  /* i64 */
	"project_name" TEXT,  /* alloc::string::String */
	"state" TEXT,  /* alloc::string::String */
	"mode" TEXT,  /* alloc::string::String */
	"progress" double precision,  /* f64 */
	"current_step" TEXT,  /* core::option::Option<alloc::string::String> */
	"algorithms_tested" INT,  /* core::option::Option<i32> */
	"algorithms_total" INT,  /* core::option::Option<i32> */
	"current_algorithm" TEXT,  /* core::option::Option<alloc::string::String> */
	"best_so_far" jsonb,  /* core::option::Option<pgrx::datum::json::JsonB> */
	"model_id" bigint,  /* core::option::Option<i64> */
	"error_message" TEXT,  /* core::option::Option<alloc::string::String> */
	"started_at" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"completed_at" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"elapsed_seconds" double precision  /* core::option::Option<f64> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'training_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/sql_functions.rs:987
-- pg_ml::sql_functions::verify_experiment
CREATE  FUNCTION "verify_experiment"(
	"project_name" TEXT, /* &str */
	"model_id" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'verify_experiment_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_ml/src/lib.rs:61
-- pg_ml::worker_status
CREATE  FUNCTION "worker_status"() RETURNS TABLE (
	"worker" INT,  /* i32 */
	"name" TEXT,  /* alloc::string::String */
	"state" TEXT,  /* alloc::string::String */
	"failures" INT,  /* i32 */
	"restarts" INT,  /* i32 */
	"pid" INT,  /* i32 */
	"since" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"last_failure" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'worker_status_wrapper';
/* </end connected objects> */

