/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:132
-- bootstrap

-- Time index registry (which column represents "when data became known")
CREATE TABLE IF NOT EXISTS pgft.time_indexes (
    id SERIAL PRIMARY KEY,
    schema_name TEXT NOT NULL,
    table_name TEXT NOT NULL,
    time_column TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(schema_name, table_name)
);

-- Relationship metadata (supplements foreign keys)
CREATE TABLE IF NOT EXISTS pgft.relationships (
    id SERIAL PRIMARY KEY,
    parent_schema TEXT NOT NULL,
    parent_table TEXT NOT NULL,
    parent_column TEXT NOT NULL,
    child_schema TEXT NOT NULL,
    child_table TEXT NOT NULL,
    child_column TEXT NOT NULL,
    relationship_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(parent_schema, parent_table, parent_column, child_schema, child_table, child_column)
);

-- Feature definitions (generated features catalog)
CREATE TABLE IF NOT EXISTS pgft.feature_definitions (
    id SERIAL PRIMARY KEY,
    project_name TEXT NOT NULL,
    feature_name TEXT NOT NULL,
    feature_type TEXT NOT NULL,
    primitive TEXT NOT NULL,
    base_column TEXT,
    source_table TEXT,
    depth INT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Generated feature matrices metadata
CREATE TABLE IF NOT EXISTS pgft.feature_matrices (
    id SERIAL PRIMARY KEY,
    project_name TEXT NOT NULL UNIQUE,
    target_schema TEXT NOT NULL,
    target_table TEXT NOT NULL,
    target_id_column TEXT NOT NULL,
    cutoff_time TIMESTAMPTZ,
    cutoff_times_table TEXT,
    cutoff_interval TEXT,
    windows TEXT[],
    output_schema TEXT NOT NULL,
    output_name TEXT NOT NULL,
    output_type TEXT NOT NULL DEFAULT 'table',
    feature_count INT NOT NULL,
    row_count BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_time_indexes_table ON pgft.time_indexes(schema_name, table_name);
CREATE INDEX IF NOT EXISTS idx_relationships_parent ON pgft.relationships(parent_schema, parent_table);
CREATE INDEX IF NOT EXISTS idx_relationships_child ON pgft.relationships(child_schema, child_table);
CREATE INDEX IF NOT EXISTS idx_feature_definitions_project ON pgft.feature_definitions(project_name);
CREATE INDEX IF NOT EXISTS idx_feature_matrices_project ON pgft.feature_matrices(project_name);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:340
-- pg_feature::add_relationship
CREATE  FUNCTION "add_relationship"(
	"parent_table" TEXT, /* &str */
	"parent_column" TEXT, /* &str */
	"child_table" TEXT, /* &str */
	"child_column" TEXT, /* &str */
	"relationship_name" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_relationship_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:407
-- pg_feature::discover_relationships
CREATE  FUNCTION "discover_relationships"(
	"schema_name" TEXT DEFAULT 'public' /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'discover_relationships_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:313
-- pg_feature::discover_time_indexes
CREATE  FUNCTION "discover_time_indexes"(
	"schema_name" TEXT DEFAULT 'public' /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'discover_time_indexes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:599
-- pg_feature::explain_feature
CREATE  FUNCTION "explain_feature"(
	"project_name" TEXT, /* &str */
	"feature_name" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'explain_feature_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:26
-- pg_feature::extension_docs
CREATE  FUNCTION "extension_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'extension_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:569
-- pg_feature::list_features
CREATE  FUNCTION "list_features"(
	"project_name" TEXT /* &str */
) RETURNS TABLE (
	"feature_name" TEXT,  /* alloc::string::String */
	"feature_type" TEXT,  /* alloc::string::String */
	"primitive" TEXT,  /* alloc::string::String */
	"base_column" TEXT,  /* core::option::Option<alloc::string::String> */
	"source_table" TEXT,  /* core::option::Option<alloc::string::String> */
	"depth" INT,  /* i32 */
	"description" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_features_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:361
-- pg_feature::list_relationships
CREATE  FUNCTION "list_relationships"() RETURNS TABLE (
	"id" bigint,  /* i64 */
	"parent_schema" TEXT,  /* alloc::string::String */
	"parent_table" TEXT,  /* alloc::string::String */
	"parent_column" TEXT,  /* alloc::string::String */
	"child_schema" TEXT,  /* alloc::string::String */
	"child_table" TEXT,  /* alloc::string::String */
	"child_column" TEXT,  /* alloc::string::String */
	"relationship_name" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_relationships_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:272
-- pg_feature::list_time_indexes
CREATE  FUNCTION "list_time_indexes"() RETURNS TABLE (
	"id" bigint,  /* i64 */
	"schema_name" TEXT,  /* alloc::string::String */
	"table_name" TEXT,  /* alloc::string::String */
	"time_column" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_time_indexes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:533
-- pg_feature::make_temporal_cutoffs
CREATE  FUNCTION "make_temporal_cutoffs"(
	"target_table" TEXT, /* &str */
	"target_id" TEXT, /* &str */
	"start_time" timestamp with time zone, /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"window_size" TEXT, /* &str */
	"output_table" TEXT, /* &str */
	"end_time" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"num_windows" INT DEFAULT NULL /* core::option::Option<i32> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'make_temporal_cutoffs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:389
-- pg_feature::remove_relationship
CREATE  FUNCTION "remove_relationship"(
	"relationship_id" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'remove_relationship_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:295
-- pg_feature::remove_time_index
CREATE  FUNCTION "remove_time_index"(
	"table_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'remove_time_index_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:263
-- pg_feature::set_time_index
CREATE  FUNCTION "set_time_index"(
	"table_name" TEXT, /* &str */
	"time_column" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_time_index_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_feature/src/lib.rs:450
-- pg_feature::synthesize_features
CREATE  FUNCTION "synthesize_features"(
	"project_name" TEXT, /* &str */
	"target_table" TEXT, /* &str */
	"target_id" TEXT, /* &str */
	"cutoff_time" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"cutoff_times_table" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"cutoff_time_column" TEXT DEFAULT 'cutoff_time', /* core::option::Option<&str> */
	"cutoff_interval" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"windows" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"tables" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"agg_primitives" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"trans_primitives" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<alloc::string::String>> */
	"max_depth" INT DEFAULT NULL, /* core::option::Option<i32> */
	"output_name" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"if_exists" TEXT DEFAULT 'error' /* core::option::Option<&str> */
) RETURNS TABLE (
	"project_name" TEXT,  /* alloc::string::String */
	"feature_count" INT,  /* i32 */
	"row_count" bigint,  /* i64 */
	"output_name" TEXT  /* alloc::string::String */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'synthesize_features_wrapper';
/* </end connected objects> */

