/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/schema.rs:3
-- bootstrap

-- =============================================================================
-- Category: human-readable grouping for units (mass, length, volume, etc.)
-- =============================================================================
CREATE TABLE @extschema@.category (
    id          SERIAL PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- Unit: individual units with SI dimension vectors and conversion factors
-- factor is relative to SI base units (kg, m, s, K, mol, A, cd)
-- offset handles affine conversions (temperature: base = value * factor + offset)
-- =============================================================================
CREATE TABLE @extschema@.unit (
    id              SERIAL PRIMARY KEY,
    category_id     INT REFERENCES @extschema@.category(id) ON DELETE SET NULL,
    name            TEXT NOT NULL UNIQUE,
    symbol          TEXT NOT NULL UNIQUE,
    factor          DOUBLE PRECISION NOT NULL CHECK (factor > 0),
    "offset"        DOUBLE PRECISION NOT NULL DEFAULT 0,
    -- SI base dimension exponents
    dim_mass        SMALLINT NOT NULL DEFAULT 0,   -- kg
    dim_length      SMALLINT NOT NULL DEFAULT 0,   -- m
    dim_time        SMALLINT NOT NULL DEFAULT 0,   -- s
    dim_temp        SMALLINT NOT NULL DEFAULT 0,   -- K
    dim_amount      SMALLINT NOT NULL DEFAULT 0,   -- mol
    dim_current     SMALLINT NOT NULL DEFAULT 0,   -- A
    dim_luminosity  SMALLINT NOT NULL DEFAULT 0,   -- cd
    description     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_unit_category ON @extschema@.unit(category_id);
CREATE INDEX idx_unit_symbol ON @extschema@.unit(symbol);
CREATE INDEX idx_unit_dims ON @extschema@.unit(
    dim_mass, dim_length, dim_time, dim_temp,
    dim_amount, dim_current, dim_luminosity
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/convert.rs:95
-- pg_uom::convert::compatible_units
CREATE  FUNCTION "compatible_units"(
	"unit_ref" TEXT /* &str */
) RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"symbol" TEXT,  /* alloc::string::String */
	"category" TEXT,  /* core::option::Option<alloc::string::String> */
	"factor" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'compatible_units_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/convert.rs:73
-- pg_uom::convert::conversion_factor
CREATE  FUNCTION "conversion_factor"(
	"from_unit" TEXT, /* &str */
	"to_unit" TEXT /* &str */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'conversion_factor_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/convert.rs:31
-- pg_uom::convert::convert
CREATE  FUNCTION "convert"(
	"value" double precision, /* f64 */
	"from_unit" TEXT, /* &str */
	"to_unit" TEXT /* &str */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'convert_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/category.rs:4
-- pg_uom::category::create_category
CREATE  FUNCTION "create_category"(
	"name" TEXT, /* &str */
	"description" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_category_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/unit.rs:5
-- pg_uom::unit::create_unit
CREATE  FUNCTION "create_unit"(
	"name" TEXT, /* &str */
	"symbol" TEXT, /* &str */
	"factor" double precision, /* f64 */
	"dim_mass" INT DEFAULT 0, /* core::option::Option<i32> */
	"dim_length" INT DEFAULT 0, /* core::option::Option<i32> */
	"dim_time" INT DEFAULT 0, /* core::option::Option<i32> */
	"dim_temp" INT DEFAULT 0, /* core::option::Option<i32> */
	"dim_amount" INT DEFAULT 0, /* core::option::Option<i32> */
	"dim_current" INT DEFAULT 0, /* core::option::Option<i32> */
	"dim_luminosity" INT DEFAULT 0, /* core::option::Option<i32> */
	"category_name" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"offset" double precision DEFAULT 0, /* core::option::Option<f64> */
	"description" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_unit_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/category.rs:19
-- pg_uom::category::drop_category
CREATE  FUNCTION "drop_category"(
	"name" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_category_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/unit.rs:68
-- pg_uom::unit::drop_unit
CREATE  FUNCTION "drop_unit"(
	"unit_name" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_unit_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/queries.rs:88
-- pg_uom::queries::list_categories
CREATE  FUNCTION "list_categories"() RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"description" TEXT,  /* core::option::Option<alloc::string::String> */
	"unit_count" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_categories_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/queries.rs:5
-- pg_uom::queries::list_units
CREATE  FUNCTION "list_units"(
	"category_name" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"symbol" TEXT,  /* alloc::string::String */
	"category" TEXT,  /* core::option::Option<alloc::string::String> */
	"factor" double precision,  /* f64 */
	"dimensions" TEXT  /* alloc::string::String */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_units_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/seed.rs:14
-- pg_uom::seed::seed_si
CREATE  FUNCTION "seed_si"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seed_si_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_uom/src/convert.rs:149
-- pg_uom::convert::unit_dimensions
CREATE  FUNCTION "unit_dimensions"(
	"unit_ref" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unit_dimensions_wrapper';
/* </end connected objects> */

