/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:262
-- bootstrap

-- Pipeline definitions
CREATE TABLE pgstreams.pipelines (
    id          SERIAL PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    definition  JSONB NOT NULL,
    state       TEXT NOT NULL DEFAULT 'created'
                CHECK (state IN ('created', 'running', 'stopped', 'failed')),
    worker_id   INT,
    error       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at  TIMESTAMPTZ,
    stopped_at  TIMESTAMPTZ
);

-- Pipeline version history
CREATE TABLE pgstreams.pipeline_versions (
    id          SERIAL PRIMARY KEY,
    pipeline_id INT NOT NULL REFERENCES pgstreams.pipelines(id) ON DELETE CASCADE,
    version     INT NOT NULL,
    definition  JSONB NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (pipeline_id, version)
);

-- Registry of auto-created state tables
CREATE TABLE pgstreams.state_tables (
    id          SERIAL PRIMARY KEY,
    pipeline    TEXT NOT NULL,
    processor   TEXT NOT NULL,
    table_name  TEXT NOT NULL UNIQUE,
    table_type  TEXT NOT NULL
                CHECK (table_type IN ('aggregate', 'window', 'join_buffer', 'cep', 'dedupe')),
    definition  JSONB NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Reusable processor/input/output definitions
CREATE TABLE pgstreams.resources (
    id          SERIAL PRIMARY KEY,
    type        TEXT NOT NULL CHECK (type IN ('processor', 'input', 'output')),
    name        TEXT NOT NULL,
    definition  JSONB NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (type, name)
);

-- Offset tracking for non-kafka input connectors
CREATE TABLE pgstreams.connector_offsets (
    id            SERIAL PRIMARY KEY,
    pipeline      TEXT NOT NULL,
    connector     TEXT NOT NULL,
    offset_value  BIGINT NOT NULL DEFAULT 0,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (pipeline, connector)
);

-- Error log / dead letter records
CREATE TABLE pgstreams.error_log (
    id          BIGSERIAL PRIMARY KEY,
    pipeline    TEXT NOT NULL,
    processor   TEXT,
    error       TEXT NOT NULL,
    record      JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_error_log_pipeline ON pgstreams.error_log (pipeline, created_at);

-- Late events log for window processors
CREATE TABLE pgstreams.late_events (
    id            BIGSERIAL PRIMARY KEY,
    pipeline      TEXT NOT NULL,
    processor     TEXT NOT NULL,
    record        JSONB NOT NULL,
    event_time    TIMESTAMPTZ,
    window_start  TIMESTAMPTZ NOT NULL,
    window_end    TIMESTAMPTZ NOT NULL,
    watermark     TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_late_events_pipeline ON pgstreams.late_events (pipeline, created_at);

-- Pipeline metrics snapshots
CREATE TABLE pgstreams.metrics (
    id          BIGSERIAL PRIMARY KEY,
    pipeline    TEXT NOT NULL,
    metric      TEXT NOT NULL,
    value       DOUBLE PRECISION NOT NULL,
    measured_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_metrics_pipeline ON pgstreams.metrics (pipeline, measured_at);

-- Generic cursor state for non-Kafka connectors (opendal, http_paginated,
-- webhook, ldes, custom). Per pipeline + connector role.
CREATE TABLE pgstreams.connector_state (
    pipeline       TEXT NOT NULL,
    connector_role TEXT NOT NULL,
    cursor         JSONB NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (pipeline, connector_role)
);

-- Named secrets referenced by connector configs as ${secret:NAME}.
-- Values returned ONLY to engine code; never via observability functions.
CREATE TABLE pgstreams.secrets (
    name        TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- LDES member-IRI dedupe (used by the LDES source connector).
CREATE TABLE pgstreams.ldes_seen_members (
    stream_url    TEXT NOT NULL,
    member_iri    TEXT NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stream_url, member_iri)
);

-- Per-record isolation for the `call` output connector.
--
-- Runs one record's function call inside a subtransaction: the PL/pgSQL
-- EXCEPTION block is exactly BeginInternalSubTransaction /
-- RollbackAndReleaseCurrentSubTransaction. Returns NULL on success, or the
-- SQLSTATE and message on a raise, so the caller can route that one record to
-- the dead-letter output and keep going with the rest of the batch.
--
-- Caveat: non-transactional side effects inside the called function (dblink,
-- the http extension, NOTIFY — anything reaching outside the database) are NOT
-- rolled back by the subtransaction.
-- `assume_role` is applied HERE rather than around the call site, so it wraps
-- only the user function. Setting it outside would leave the connector calling
-- this very function as the application role, which has no rights on the
-- pgstreams schema — the pipeline then fails with `permission denied for schema
-- pgstreams` before the user function is ever reached.
--
-- On error the subtransaction rollback restores the role for free; on success
-- it is reset explicitly.
CREATE FUNCTION pgstreams.call_guarded(query TEXT, payload JSONB, assume_role TEXT DEFAULT NULL)
RETURNS JSONB
LANGUAGE plpgsql
AS $call_guarded$
BEGIN
    IF assume_role IS NOT NULL THEN
        EXECUTE format('SET LOCAL ROLE %I', assume_role);
    END IF;
    EXECUTE query USING payload;
    IF assume_role IS NOT NULL THEN
        RESET ROLE;
    END IF;
    RETURN NULL;
EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('sqlstate', SQLSTATE, 'message', SQLERRM);
END;
$call_guarded$;

COMMENT ON FUNCTION pgstreams.call_guarded(TEXT, JSONB, TEXT) IS
    'Runs one `call` output-connector invocation inside a subtransaction, optionally as `assume_role`; returns NULL on success or {sqlstate, message} on error.';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:37
-- pg_streaming::create_pipeline
CREATE  FUNCTION "create_pipeline"(
	"name" TEXT, /* &str */
	"definition" jsonb /* pgrx::datum::json::JsonB */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_pipeline_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:49
-- pg_streaming::drop_pipeline
CREATE  FUNCTION "drop_pipeline"(
	"name" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_pipeline_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:91
-- pg_streaming::drop_secret
CREATE  FUNCTION "drop_secret"(
	"name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_secret_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:168
-- pg_streaming::errors
CREATE  FUNCTION "errors"(
	"name" TEXT, /* &str */
	"limit" INT DEFAULT 10 /* i32 */
) RETURNS TABLE (
	"id" bigint,  /* i64 */
	"pipeline" TEXT,  /* alloc::string::String */
	"processor" TEXT,  /* core::option::Option<alloc::string::String> */
	"error" TEXT,  /* alloc::string::String */
	"record" jsonb,  /* core::option::Option<pgrx::datum::json::JsonB> */
	"created_at" timestamp with time zone  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'errors_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:227
-- pg_streaming::lag
CREATE  FUNCTION "lag"() RETURNS TABLE (
	"pipeline" TEXT,  /* alloc::string::String */
	"connector" TEXT,  /* alloc::string::String */
	"committed_offset" bigint,  /* i64 */
	"updated_at" timestamp with time zone  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'lag_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:188
-- pg_streaming::late_events
CREATE  FUNCTION "late_events"(
	"name" TEXT, /* &str */
	"limit" INT DEFAULT 10 /* i32 */
) RETURNS TABLE (
	"id" bigint,  /* i64 */
	"pipeline" TEXT,  /* alloc::string::String */
	"processor" TEXT,  /* alloc::string::String */
	"event_time" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"window_start" timestamp with time zone,  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"window_end" timestamp with time zone,  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"watermark" timestamp with time zone,  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"created_at" timestamp with time zone  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'late_events_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:136
-- pg_streaming::list_custom_processors
CREATE  FUNCTION "list_custom_processors"() RETURNS TABLE (
	"name" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_custom_processors_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:130
-- pg_streaming::list_custom_sinks
CREATE  FUNCTION "list_custom_sinks"() RETURNS TABLE (
	"name" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_custom_sinks_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:119
-- pg_streaming::list_custom_sources
CREATE  FUNCTION "list_custom_sources"() RETURNS TABLE (
	"name" TEXT  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_custom_sources_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:97
-- pg_streaming::list_secrets
CREATE  FUNCTION "list_secrets"() RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"description" TEXT,  /* core::option::Option<alloc::string::String> */
	"created_at" timestamp with time zone  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_secrets_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:210
-- pg_streaming::metrics
CREATE  FUNCTION "metrics"(
	"name" TEXT, /* &str */
	"limit" INT DEFAULT 50 /* i32 */
) RETURNS TABLE (
	"pipeline" TEXT,  /* alloc::string::String */
	"metric" TEXT,  /* alloc::string::String */
	"value" double precision,  /* f64 */
	"measured_at" timestamp with time zone  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'metrics_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:75
-- pg_streaming::replay
CREATE  FUNCTION "replay"(
	"name" TEXT, /* &str */
	"after" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'replay_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/worker.rs:31
-- pg_streaming::worker::reset_workers
CREATE  FUNCTION "reset_workers"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reset_workers_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:67
-- pg_streaming::restart
CREATE  FUNCTION "restart"(
	"name" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'restart_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:85
-- pg_streaming::set_secret
CREATE  FUNCTION "set_secret"(
	"name" TEXT, /* &str */
	"value" TEXT, /* &str */
	"description" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_secret_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:55
-- pg_streaming::start
CREATE  FUNCTION "start"(
	"name" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'start_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:150
-- pg_streaming::status
CREATE  FUNCTION "status"() RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"state" TEXT,  /* alloc::string::String */
	"worker_id" INT,  /* core::option::Option<i32> */
	"error" TEXT,  /* core::option::Option<alloc::string::String> */
	"started_at" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"stopped_at" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"uptime" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:61
-- pg_streaming::stop
CREATE  FUNCTION "stop"(
	"name" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stop_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:241
-- pg_streaming::trace
CREATE  FUNCTION "trace"(
	"name" TEXT, /* &str */
	"limit" INT DEFAULT 5 /* i32 */
) RETURNS TABLE (
	"record" jsonb,  /* core::option::Option<pgrx::datum::json::JsonB> */
	"error" TEXT,  /* alloc::string::String */
	"created_at" timestamp with time zone  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'trace_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/lib.rs:43
-- pg_streaming::update_pipeline
CREATE  FUNCTION "update_pipeline"(
	"name" TEXT, /* &str */
	"definition" jsonb /* pgrx::datum::json::JsonB */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'update_pipeline_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_streaming/src/worker.rs:31
-- pg_streaming::worker::worker_status
CREATE  FUNCTION "worker_status"() RETURNS TABLE (
	"worker" INT,  /* i32 */
	"name" TEXT,  /* alloc::string::String */
	"state" TEXT,  /* alloc::string::String */
	"failures" INT,  /* i32 */
	"restarts" INT,  /* i32 */
	"pid" INT,  /* i32 */
	"since" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"last_failure" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'worker_status_wrapper';
/* </end connected objects> */

