/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/lib.rs:54
-- bootstrap

-- Topic registry
CREATE TABLE pgkafka.topics (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    source_table TEXT,
    offset_column TEXT,
    value_column TEXT,
    value_expr TEXT,
    key_column TEXT,
    key_expr TEXT,
    headers_column TEXT,
    headers_expr TEXT,
    timestamp_column TEXT,
    timestamp_expr TEXT,
    -- Write support for source-backed topics
    writable BOOLEAN NOT NULL DEFAULT FALSE,
    write_mode TEXT CHECK (write_mode IS NULL OR write_mode IN ('stream', 'table')),
    write_key_column TEXT,           -- For table mode: column to match Kafka key
    kafka_offset_column TEXT,        -- For table mode: column to track Kafka offset
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    config JSONB NOT NULL DEFAULT '{}',
    CONSTRAINT chk_value_source CHECK (
        source_table IS NULL OR (value_column IS NOT NULL OR value_expr IS NOT NULL)
    ),
    CONSTRAINT chk_offset_required CHECK (
        source_table IS NULL OR offset_column IS NOT NULL
    ),
    CONSTRAINT chk_value_exclusive CHECK (
        NOT (value_column IS NOT NULL AND value_expr IS NOT NULL)
    ),
    CONSTRAINT chk_key_exclusive CHECK (
        NOT (key_column IS NOT NULL AND key_expr IS NOT NULL)
    ),
    CONSTRAINT chk_write_mode_source CHECK (
        write_mode IS NULL OR source_table IS NOT NULL
    ),
    CONSTRAINT chk_table_mode_key CHECK (
        write_mode != 'table' OR write_key_column IS NOT NULL
    )
);

-- Messages table (for native topics)
CREATE TABLE pgkafka.messages (
    offset_id BIGSERIAL,
    topic_id INT NOT NULL REFERENCES pgkafka.topics(id) ON DELETE CASCADE,
    key BYTEA,
    key_text TEXT,
    key_json JSONB,
    value BYTEA NOT NULL,
    value_text TEXT,
    value_json JSONB,
    headers JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (topic_id, offset_id)
);

CREATE INDEX idx_messages_topic_offset ON pgkafka.messages (topic_id, offset_id);

-- Consumer groups (coordinator state; see storage/groups.rs)
-- state: Empty | PreparingRebalance | CompletingRebalance | Stable
CREATE TABLE pgkafka.consumer_groups (
    id SERIAL PRIMARY KEY,
    group_id TEXT NOT NULL UNIQUE,
    state TEXT NOT NULL DEFAULT 'Empty'
        CHECK (state IN ('Empty', 'PreparingRebalance', 'CompletingRebalance', 'Stable')),
    generation_id INT NOT NULL DEFAULT 0,
    protocol_type TEXT,               -- e.g. 'consumer'
    protocol TEXT,                    -- selected assignor, e.g. 'range'
    leader_id TEXT,
    rebalance_started_at TIMESTAMPTZ, -- when the current PreparingRebalance began
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Consumer group members
CREATE TABLE pgkafka.consumer_group_members (
    id SERIAL PRIMARY KEY,
    group_id INT NOT NULL REFERENCES pgkafka.consumer_groups(id) ON DELETE CASCADE,
    member_id TEXT NOT NULL,
    client_id TEXT,
    client_host TEXT,
    session_timeout_ms INT NOT NULL DEFAULT 30000,
    rebalance_timeout_ms INT NOT NULL DEFAULT 60000,
    protocol_type TEXT,
    protocols JSONB NOT NULL DEFAULT '[]', -- [{"name": ..., "metadata": "<hex>"}], preference order
    generation_id INT,                     -- generation this member last joined (NULL = pending)
    assignment BYTEA,
    assignment_generation INT,             -- generation the assignment belongs to
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_heartbeat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (group_id, member_id)
);

-- Consumer offsets
CREATE TABLE pgkafka.consumer_offsets (
    group_id INT NOT NULL REFERENCES pgkafka.consumer_groups(id) ON DELETE CASCADE,
    topic_id INT NOT NULL REFERENCES pgkafka.topics(id) ON DELETE CASCADE,
    partition INT NOT NULL DEFAULT 0,
    committed_offset BIGINT NOT NULL,
    metadata TEXT,
    committed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (group_id, topic_id, partition)
);

-- Aggressive autovacuum for high-write message table
ALTER TABLE pgkafka.messages SET (
    autovacuum_vacuum_scale_factor = 0.01,
    autovacuum_analyze_scale_factor = 0.005
);

-- Schema registry (for typed topics)
CREATE TABLE pgkafka.schemas (
    id SERIAL PRIMARY KEY,
    subject TEXT NOT NULL,
    version INT NOT NULL DEFAULT 1,
    schema_def JSONB NOT NULL,
    fingerprint TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (subject, version),
    UNIQUE (subject, fingerprint)
);

CREATE INDEX idx_schemas_subject ON pgkafka.schemas(subject);
CREATE INDEX idx_schemas_fingerprint ON pgkafka.schemas(fingerprint);

-- Schema-to-topic binding for validation
CREATE TABLE pgkafka.topic_schemas (
    id SERIAL PRIMARY KEY,
    topic_name TEXT NOT NULL,
    schema_type TEXT NOT NULL CHECK (schema_type IN ('key', 'value')),
    schema_id INT NOT NULL REFERENCES pgkafka.schemas(id) ON DELETE CASCADE,
    validation_mode TEXT NOT NULL DEFAULT 'STRICT' CHECK (validation_mode IN ('STRICT', 'LOG')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (topic_name, schema_type)
);

CREATE INDEX idx_topic_schemas_topic ON pgkafka.topic_schemas(topic_name);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/schema.rs:640
-- pg_kafka::schema::bind_schema_to_topic
CREATE  FUNCTION "bind_schema_to_topic"(
	"topic_name" TEXT, /* &str */
	"schema_id" INT, /* i32 */
	"schema_type" TEXT DEFAULT 'value', /* &str */
	"validation_mode" TEXT DEFAULT 'STRICT' /* &str */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bind_schema_to_topic_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/topic_admin.rs:6
-- pg_kafka::topic_admin::create_topic

CREATE FUNCTION create_topic(
    name TEXT,
    source_table TEXT DEFAULT NULL,
    offset_column TEXT DEFAULT NULL,
    value_column TEXT DEFAULT NULL,
    value_expr TEXT DEFAULT NULL,
    key_column TEXT DEFAULT NULL,
    key_expr TEXT DEFAULT NULL,
    config jsonb DEFAULT NULL
) RETURNS INT
VOLATILE
LANGUAGE c AS 'MODULE_PATHNAME', 'create_topic_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/topic_writes.rs:31
-- pg_kafka::topic_writes::create_topic_from_table

CREATE FUNCTION create_topic_from_table(
    name TEXT,
    source_table TEXT,
    offset_column TEXT,
    value_column TEXT DEFAULT NULL,
    value_expr TEXT DEFAULT NULL,
    key_column TEXT DEFAULT NULL,
    key_expr TEXT DEFAULT NULL,
    timestamp_column TEXT DEFAULT NULL
) RETURNS INT
VOLATILE
LANGUAGE c AS 'MODULE_PATHNAME', 'create_topic_from_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/schema.rs:761
-- pg_kafka::schema::create_typed_topic
CREATE  FUNCTION "create_typed_topic"(
	"topic_name" TEXT, /* &str */
	"schema_def" jsonb, /* pgrx::datum::json::JsonB */
	"table_name" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"write_mode" TEXT DEFAULT 'stream', /* &str */
	"key_column" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"validation_mode" TEXT DEFAULT 'STRICT' /* &str */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_typed_topic_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/schema.rs:915
-- pg_kafka::schema::create_typed_topic_from_table
CREATE  FUNCTION "create_typed_topic_from_table"(
	"topic_name" TEXT, /* &str */
	"table_name" TEXT, /* &str */
	"offset_column" TEXT, /* &str */
	"write_mode" TEXT DEFAULT 'stream', /* &str */
	"key_column" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"kafka_offset_column" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"validation_mode" TEXT DEFAULT 'STRICT' /* &str */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_typed_topic_from_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/topic_writes.rs:213
-- pg_kafka::topic_writes::disable_topic_writes
CREATE  FUNCTION "disable_topic_writes"(
	"topic_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'disable_topic_writes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/schema.rs:718
-- pg_kafka::schema::drop_schema
CREATE  FUNCTION "drop_schema"(
	"schema_id" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/topic_admin.rs:56
-- pg_kafka::topic_admin::drop_topic

CREATE FUNCTION drop_topic(name TEXT, delete_messages bool DEFAULT true) RETURNS bool
VOLATILE STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'drop_topic_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/topic_writes.rs:122
-- pg_kafka::topic_writes::enable_topic_writes

CREATE FUNCTION enable_topic_writes(
    topic_name TEXT,
    write_mode TEXT DEFAULT 'stream',
    key_column TEXT DEFAULT NULL,
    kafka_offset_column TEXT DEFAULT NULL
) RETURNS BOOL
VOLATILE
LANGUAGE c AS 'MODULE_PATHNAME', 'enable_topic_writes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/lib.rs:48
-- pg_kafka::extension_docs
CREATE  FUNCTION "extension_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'extension_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/schema.rs:601
-- pg_kafka::schema::get_latest_schema
CREATE  FUNCTION "get_latest_schema"(
	"subject" TEXT /* &str */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_latest_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/schema.rs:590
-- pg_kafka::schema::get_schema
CREATE  FUNCTION "get_schema"(
	"schema_id" INT /* i32 */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/schema.rs:612
-- pg_kafka::schema::get_topic_schema
CREATE  FUNCTION "get_topic_schema"(
	"topic_name" TEXT, /* &str */
	"schema_type" TEXT DEFAULT 'value' /* &str */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_topic_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/produce.rs:18
-- pg_kafka::produce::produce

CREATE FUNCTION produce(topic TEXT, value bytea, key bytea DEFAULT NULL, headers jsonb DEFAULT NULL) RETURNS bigint
VOLATILE LANGUAGE c AS 'MODULE_PATHNAME', 'produce_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/schema.rs:551
-- pg_kafka::schema::register_schema
CREATE  FUNCTION "register_schema"(
	"subject" TEXT, /* &str */
	"schema_def" jsonb, /* pgrx::datum::json::JsonB */
	"description" TEXT /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'register_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/worker.rs:20
-- pg_kafka::worker::reset_workers
CREATE  FUNCTION "reset_workers"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reset_workers_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/schema.rs:1001
-- pg_kafka::schema::schema_from_table
CREATE  FUNCTION "schema_from_table"(
	"table_name" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'schema_from_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/admin.rs:11
-- pg_kafka::admin::status
CREATE  FUNCTION "status"() RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/schema.rs:1015
-- pg_kafka::schema::table_from_schema
CREATE  FUNCTION "table_from_schema"(
	"table_name" TEXT, /* &str */
	"schema_def" jsonb, /* pgrx::datum::json::JsonB */
	"add_id_column" bool DEFAULT true /* bool */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'table_from_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/schema.rs:697
-- pg_kafka::schema::unbind_schema_from_topic
CREATE  FUNCTION "unbind_schema_from_topic"(
	"topic_name" TEXT, /* &str */
	"schema_type" TEXT DEFAULT 'value' /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unbind_schema_from_topic_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_kafka/src/worker.rs:20
-- pg_kafka::worker::worker_status
CREATE  FUNCTION "worker_status"() RETURNS TABLE (
	"worker" INT,  /* i32 */
	"name" TEXT,  /* alloc::string::String */
	"state" TEXT,  /* alloc::string::String */
	"failures" INT,  /* i32 */
	"restarts" INT,  /* i32 */
	"pid" INT,  /* i32 */
	"since" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"last_failure" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'worker_status_wrapper';
/* </end connected objects> */

