/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/lib.rs:27
-- bootstrap

    -- Repository registry
    CREATE TABLE IF NOT EXISTS repos (
        id          TEXT PRIMARY KEY,
        path        TEXT NOT NULL UNIQUE,
        description TEXT,
        default_branch TEXT NOT NULL DEFAULT 'main',
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_by  TEXT NOT NULL DEFAULT current_user
    );

    -- Commit log synced from git
    CREATE TABLE IF NOT EXISTS commits (
        repo_id     TEXT NOT NULL REFERENCES repos(id),
        hash        TEXT NOT NULL,
        parent_hash TEXT,
        message     TEXT NOT NULL,
        author      TEXT NOT NULL,
        author_email TEXT,
        committed_at TIMESTAMPTZ NOT NULL,
        synced_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (repo_id, hash)
    );

    CREATE INDEX IF NOT EXISTS idx_commits_repo_date
        ON commits(repo_id, committed_at DESC);

    -- Sync state tracking
    CREATE TABLE IF NOT EXISTS sync_state (
        repo_id         TEXT PRIMARY KEY REFERENCES repos(id),
        last_synced_hash TEXT,
        last_synced_at  TIMESTAMPTZ
    );

    -- Current state of tracked files with auto-extracted metadata
    CREATE TABLE IF NOT EXISTS files (
        repo_id     TEXT NOT NULL REFERENCES repos(id),
        path        TEXT NOT NULL,
        branch      TEXT NOT NULL DEFAULT 'main',
        current_hash TEXT NOT NULL,
        mime_type   TEXT,
        size_bytes  BIGINT,
        encoding    TEXT,
        language    TEXT,
        line_count  INTEGER,
        title       TEXT,
        owner       TEXT,
        tags        JSONB DEFAULT '[]'::jsonb,
        custom_meta JSONB DEFAULT '{}'::jsonb,
        created_at  TIMESTAMPTZ,
        updated_at  TIMESTAMPTZ,
        updated_by  TEXT,
        PRIMARY KEY (repo_id, branch, path)
    );

    -- Change log per file (one row per commit that touched the file)
    CREATE TABLE IF NOT EXISTS file_history (
        repo_id     TEXT NOT NULL,
        path        TEXT NOT NULL,
        commit_hash TEXT NOT NULL,
        change_type TEXT NOT NULL,
        old_hash    TEXT,
        new_hash    TEXT,
        old_path    TEXT,
        lines_added   INTEGER,
        lines_removed INTEGER,
        committed_at TIMESTAMPTZ NOT NULL,
        author      TEXT NOT NULL,
        PRIMARY KEY (repo_id, path, commit_hash)
    );

    CREATE INDEX IF NOT EXISTS idx_file_history_repo_commit
        ON file_history(repo_id, commit_hash);

    -- Optional: user profile mapping (role -> email for git commits)
    CREATE TABLE IF NOT EXISTS user_profiles (
        role_name    TEXT PRIMARY KEY,
        display_name TEXT,
        email        TEXT
    );

    -- Role-based access control
    CREATE TABLE IF NOT EXISTS permissions (
        repo_id     TEXT NOT NULL REFERENCES repos(id),
        role_name   TEXT NOT NULL,
        scope_type  TEXT NOT NULL CHECK (scope_type IN ('repo', 'branch', 'path')),
        scope_value TEXT NOT NULL DEFAULT '*',
        access      TEXT NOT NULL CHECK (access IN ('read', 'write', 'admin')),
        granted_by  TEXT NOT NULL DEFAULT current_user,
        granted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (repo_id, role_name, scope_type, scope_value)
    );

    -- Branch metadata and protection
    CREATE TABLE IF NOT EXISTS branches (
        repo_id       TEXT NOT NULL REFERENCES repos(id),
        name          TEXT NOT NULL,
        head_commit   TEXT,
        protected     BOOLEAN NOT NULL DEFAULT false,
        allowed_roles TEXT[],
        PRIMARY KEY (repo_id, name)
    );

    -- =======================================================================
    -- Row-Level Security policies
    -- =======================================================================

    -- repos: visible if user has any permission on it
    ALTER TABLE repos ENABLE ROW LEVEL SECURITY;
    CREATE POLICY repos_read ON repos FOR SELECT USING (
        EXISTS (SELECT 1 FROM permissions p
                WHERE p.repo_id = repos.id AND p.role_name = current_user)
    );
    CREATE POLICY repos_admin ON repos FOR ALL USING (
        EXISTS (SELECT 1 FROM permissions p
                WHERE p.repo_id = repos.id AND p.role_name = current_user
                  AND p.access = 'admin')
    );

    -- commits: read if any permission on repo; write if write/admin
    ALTER TABLE commits ENABLE ROW LEVEL SECURITY;
    CREATE POLICY commits_read ON commits FOR SELECT USING (
        EXISTS (SELECT 1 FROM permissions p
                WHERE p.repo_id = commits.repo_id AND p.role_name = current_user
                  AND p.access IN ('read', 'write', 'admin')
                  AND (p.scope_type = 'repo' OR p.scope_type = 'branch' OR p.scope_type = 'path'))
    );
    CREATE POLICY commits_write ON commits FOR INSERT WITH CHECK (
        EXISTS (SELECT 1 FROM permissions p
                WHERE p.repo_id = commits.repo_id AND p.role_name = current_user
                  AND p.access IN ('write', 'admin') AND p.scope_type = 'repo')
    );

    -- files: scope-aware read and write
    ALTER TABLE files ENABLE ROW LEVEL SECURITY;
    CREATE POLICY files_read ON files FOR SELECT USING (
        EXISTS (SELECT 1 FROM permissions p
                WHERE p.repo_id = files.repo_id AND p.role_name = current_user
                  AND p.access IN ('read', 'write', 'admin')
                  AND ((p.scope_type = 'repo')
                    OR (p.scope_type = 'branch' AND p.scope_value = files.branch)
                    OR (p.scope_type = 'path' AND files.path LIKE replace(p.scope_value, '*', '%'))))
    );
    CREATE POLICY files_write ON files FOR UPDATE USING (
        EXISTS (SELECT 1 FROM permissions p
                WHERE p.repo_id = files.repo_id AND p.role_name = current_user
                  AND p.access IN ('write', 'admin')
                  AND ((p.scope_type = 'repo')
                    OR (p.scope_type = 'path' AND files.path LIKE replace(p.scope_value, '*', '%'))))
    );

    -- file_history: read if any permission on repo
    ALTER TABLE file_history ENABLE ROW LEVEL SECURITY;
    CREATE POLICY file_history_read ON file_history FOR SELECT USING (
        EXISTS (SELECT 1 FROM permissions p
                WHERE p.repo_id = file_history.repo_id AND p.role_name = current_user
                  AND p.access IN ('read', 'write', 'admin')
                  AND (p.scope_type = 'repo' OR p.scope_type = 'branch' OR p.scope_type = 'path'))
    );

    -- =======================================================================
    -- Public table access (RLS policies handle row-level filtering)
    -- =======================================================================
    GRANT USAGE ON SCHEMA @extschema@ TO PUBLIC;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA @extschema@ TO PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/lib.rs:219
-- pg_git::extension_docs
CREATE  FUNCTION "extension_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'extension_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:151
-- pg_git::sql::git_add
CREATE  FUNCTION "git_add"(
	"repo_id" TEXT, /* &str */
	"path" TEXT, /* &str */
	"content" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TEXT /* alloc::string::String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_add_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:174
-- pg_git::sql::git_add_binary
CREATE  FUNCTION "git_add_binary"(
	"repo_id" TEXT, /* &str */
	"path" TEXT, /* &str */
	"content" bytea /* &[u8] */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_add_binary_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:589
-- pg_git::sql::git_branch
CREATE  FUNCTION "git_branch"(
	"repo_id" TEXT, /* &str */
	"branch_name" TEXT, /* &str */
	"start_point" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TEXT /* alloc::string::String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_branch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:685
-- pg_git::sql::git_branches
CREATE  FUNCTION "git_branches"(
	"repo_id" TEXT /* &str */
) RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"head_commit" TEXT,  /* core::option::Option<alloc::string::String> */
	"is_current" bool,  /* bool */
	"protected" bool  /* bool */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_branches_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:625
-- pg_git::sql::git_checkout
CREATE  FUNCTION "git_checkout"(
	"repo_id" TEXT, /* &str */
	"branch_name" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_checkout_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:205
-- pg_git::sql::git_commit
CREATE  FUNCTION "git_commit"(
	"repo_id" TEXT, /* &str */
	"message" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_commit_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:745
-- pg_git::sql::git_delete_branch
CREATE  FUNCTION "git_delete_branch"(
	"repo_id" TEXT, /* &str */
	"branch_name" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_delete_branch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:414
-- pg_git::sql::git_diff
CREATE  FUNCTION "git_diff"(
	"repo_id" TEXT, /* &str */
	"from_ref" TEXT, /* &str */
	"to_ref" TEXT /* &str */
) RETURNS TABLE (
	"path" TEXT,  /* alloc::string::String */
	"change_type" TEXT,  /* alloc::string::String */
	"lines_added" INT,  /* core::option::Option<i32> */
	"lines_removed" INT  /* core::option::Option<i32> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_diff_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:465
-- pg_git::sql::git_grant
CREATE  FUNCTION "git_grant"(
	"repo_id" TEXT, /* &str */
	"role_name" TEXT, /* &str */
	"access" TEXT, /* &str */
	"scope_type" TEXT DEFAULT 'repo', /* &str */
	"scope_value" TEXT DEFAULT '*' /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_grant_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:11
-- pg_git::sql::git_init
CREATE  FUNCTION "git_init"(
	"repo_id" TEXT, /* &str */
	"path" TEXT, /* core::option::Option<&str> */
	"description" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TEXT /* alloc::string::String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_init_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:344
-- pg_git::sql::git_log
CREATE  FUNCTION "git_log"(
	"repo_id" TEXT, /* &str */
	"path" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"max_rows" INT DEFAULT 100 /* i32 */
) RETURNS TABLE (
	"hash" TEXT,  /* alloc::string::String */
	"parent_hash" TEXT,  /* core::option::Option<alloc::string::String> */
	"message" TEXT,  /* alloc::string::String */
	"author" TEXT,  /* alloc::string::String */
	"author_email" TEXT,  /* core::option::Option<alloc::string::String> */
	"committed_at" TEXT  /* alloc::string::String */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_log_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:640
-- pg_git::sql::git_merge
CREATE  FUNCTION "git_merge"(
	"repo_id" TEXT, /* &str */
	"source_branch" TEXT, /* &str */
	"target_branch" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TEXT /* alloc::string::String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_merge_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:544
-- pg_git::sql::git_protect_branch
CREATE  FUNCTION "git_protect_branch"(
	"repo_id" TEXT, /* &str */
	"branch_name" TEXT, /* &str */
	"allowed_roles" TEXT[] /* alloc::vec::Vec<alloc::string::String> */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_protect_branch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:83
-- pg_git::sql::git_register
CREATE  FUNCTION "git_register"(
	"repo_id" TEXT, /* &str */
	"path" TEXT, /* &str */
	"description" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TEXT /* alloc::string::String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_register_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:519
-- pg_git::sql::git_revoke
CREATE  FUNCTION "git_revoke"(
	"repo_id" TEXT, /* &str */
	"role_name" TEXT, /* &str */
	"access" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_revoke_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:306
-- pg_git::sql::git_show
CREATE  FUNCTION "git_show"(
	"repo_id" TEXT, /* &str */
	"path" TEXT, /* &str */
	"commit_hash" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TEXT /* alloc::string::String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_show_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:188
-- pg_git::sql::git_show_binary
CREATE  FUNCTION "git_show_binary"(
	"repo_id" TEXT, /* &str */
	"path" TEXT, /* &str */
	"commit_hash" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS bytea /* alloc::vec::Vec<u8> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_show_binary_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_git/src/sql.rs:322
-- pg_git::sql::git_status
CREATE  FUNCTION "git_status"() RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'git_status_wrapper';
/* </end connected objects> */

