/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:48
-- bootstrap

-- Schema is created by control file (schema = pgsheet)

-- Sheet metadata
CREATE TABLE IF NOT EXISTS pgsheet._sheets (
    name text PRIMARY KEY,
    source_schema text NOT NULL,
    source_table text NOT NULL,
    source_filter text,
    created_at timestamptz DEFAULT now(),
    created_by text DEFAULT current_setting('app.user_id', true)
);

-- Column metadata (source + overlay + formula columns)
CREATE TABLE IF NOT EXISTS pgsheet._columns (
    sheet_name text NOT NULL REFERENCES pgsheet._sheets(name) ON DELETE CASCADE,
    col_name text NOT NULL,
    col_type text NOT NULL DEFAULT 'text',
    is_source boolean NOT NULL DEFAULT false,
    is_formula boolean NOT NULL DEFAULT false,
    formula_expr text,
    formula_sql text,
    default_value text,
    PRIMARY KEY (sheet_name, col_name)
);

-- Snapshot metadata
CREATE TABLE IF NOT EXISTS pgsheet._snapshots (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    sheet_name text NOT NULL REFERENCES pgsheet._sheets(name) ON DELETE CASCADE,
    label text,
    cell_count bigint DEFAULT 0,
    created_at timestamptz DEFAULT now(),
    created_by text DEFAULT current_setting('app.user_id', true)
);

CREATE INDEX IF NOT EXISTS idx_snapshots_sheet
    ON pgsheet._snapshots(sheet_name, created_at DESC);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:191
-- pg_sheet::add_column
CREATE  FUNCTION "add_column"(
	"sheet_name" TEXT, /* &str */
	"col_name" TEXT, /* &str */
	"col_type" TEXT, /* &str */
	"default_value" TEXT DEFAULT NULL /* core::option::Option<alloc::string::String> */
) RETURNS bool /* bool */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_column_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:213
-- pg_sheet::add_formula
CREATE  FUNCTION "add_formula"(
	"sheet_name" TEXT, /* &str */
	"col_name" TEXT, /* &str */
	"formula" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_formula_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:496
-- pg_sheet::cell_history
CREATE  FUNCTION "cell_history"(
	"sheet_name" TEXT, /* &str */
	"entity_id" uuid, /* pgrx::datum::uuid::Uuid */
	"col_name" TEXT, /* &str */
	"limit" INT DEFAULT 20 /* i32 */
) RETURNS TABLE (
	"old_value" TEXT,  /* core::option::Option<alloc::string::String> */
	"new_value" TEXT,  /* core::option::Option<alloc::string::String> */
	"old_formula" TEXT,  /* core::option::Option<alloc::string::String> */
	"new_formula" TEXT,  /* core::option::Option<alloc::string::String> */
	"modified_by" TEXT,  /* core::option::Option<alloc::string::String> */
	"modified_at" timestamp with time zone  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cell_history_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:322
-- pg_sheet::clear_cell
CREATE  FUNCTION "clear_cell"(
	"sheet_name" TEXT, /* &str */
	"entity_id" uuid, /* pgrx::datum::uuid::Uuid */
	"col_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'clear_cell_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:116
-- pg_sheet::create_sheet
CREATE  FUNCTION "create_sheet"(
	"name" TEXT, /* &str */
	"source_schema" TEXT, /* &str */
	"source_table" TEXT, /* &str */
	"source_filter" TEXT DEFAULT NULL /* core::option::Option<alloc::string::String> */
) RETURNS bool /* bool */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_sheet_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:424
-- pg_sheet::diff
CREATE  FUNCTION "diff"(
	"sheet_name" TEXT, /* &str */
	"snapshot_id" uuid /* pgrx::datum::uuid::Uuid */
) RETURNS TABLE (
	"entity_id" uuid,  /* pgrx::datum::uuid::Uuid */
	"col_name" TEXT,  /* alloc::string::String */
	"change_type" TEXT,  /* alloc::string::String */
	"snapshot_value" TEXT,  /* core::option::Option<alloc::string::String> */
	"current_value" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'diff_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:222
-- pg_sheet::drop_column
CREATE  FUNCTION "drop_column"(
	"sheet_name" TEXT, /* &str */
	"col_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_column_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:130
-- pg_sheet::drop_sheet
CREATE  FUNCTION "drop_sheet"(
	"name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_sheet_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:596
-- pg_sheet::expire_locks
CREATE  FUNCTION "expire_locks"(
	"sheet_name" TEXT, /* &str */
	"older_than" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'expire_locks_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:39
-- pg_sheet::extension_docs
CREATE  FUNCTION "extension_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'extension_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:331
-- pg_sheet::get_cell
CREATE  FUNCTION "get_cell"(
	"sheet_name" TEXT, /* &str */
	"entity_id" uuid, /* pgrx::datum::uuid::Uuid */
	"col_name" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_cell_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:356
-- pg_sheet::get_data
CREATE  FUNCTION "get_data"(
	"sheet_name" TEXT, /* &str */
	"limit" INT DEFAULT 100, /* i32 */
	"offset" INT DEFAULT 0 /* i32 */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_data_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:240
-- pg_sheet::list_columns
CREATE  FUNCTION "list_columns"(
	"sheet_name" TEXT /* &str */
) RETURNS TABLE (
	"col_name" TEXT,  /* alloc::string::String */
	"col_type" TEXT,  /* alloc::string::String */
	"is_source" bool,  /* bool */
	"is_formula" bool,  /* bool */
	"formula_expr" TEXT,  /* core::option::Option<alloc::string::String> */
	"default_value" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_columns_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:139
-- pg_sheet::list_sheets
CREATE  FUNCTION "list_sheets"() RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"source_schema" TEXT,  /* alloc::string::String */
	"source_table" TEXT,  /* alloc::string::String */
	"source_filter" TEXT,  /* core::option::Option<alloc::string::String> */
	"created_at" timestamp with time zone  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_sheets_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:446
-- pg_sheet::list_snapshots
CREATE  FUNCTION "list_snapshots"(
	"sheet_name" TEXT /* &str */
) RETURNS TABLE (
	"id" uuid,  /* pgrx::datum::uuid::Uuid */
	"label" TEXT,  /* core::option::Option<alloc::string::String> */
	"cell_count" bigint,  /* i64 */
	"created_at" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"created_by" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_snapshots_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:548
-- pg_sheet::lock_cell
CREATE  FUNCTION "lock_cell"(
	"sheet_name" TEXT, /* &str */
	"entity_id" uuid, /* pgrx::datum::uuid::Uuid */
	"col_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'lock_cell_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:571
-- pg_sheet::locked_cells
CREATE  FUNCTION "locked_cells"(
	"sheet_name" TEXT /* &str */
) RETURNS TABLE (
	"entity_id" uuid,  /* pgrx::datum::uuid::Uuid */
	"col_name" TEXT,  /* alloc::string::String */
	"locked_by" TEXT,  /* alloc::string::String */
	"locked_at" timestamp with time zone  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'locked_cells_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:381
-- pg_sheet::parse_formula
CREATE  FUNCTION "parse_formula"(
	"formula" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'parse_formula_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:231
-- pg_sheet::rename_column
CREATE  FUNCTION "rename_column"(
	"sheet_name" TEXT, /* &str */
	"old_name" TEXT, /* &str */
	"new_name" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rename_column_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:415
-- pg_sheet::restore
CREATE  FUNCTION "restore"(
	"sheet_name" TEXT, /* &str */
	"snapshot_id" uuid /* pgrx::datum::uuid::Uuid */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'restore_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:308
-- pg_sheet::set_formula
CREATE  FUNCTION "set_formula"(
	"sheet_name" TEXT, /* &str */
	"entity_id" uuid, /* pgrx::datum::uuid::Uuid */
	"col_name" TEXT, /* &str */
	"formula" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_formula_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:291
-- pg_sheet::set_value
CREATE  FUNCTION "set_value"(
	"sheet_name" TEXT, /* &str */
	"entity_id" uuid, /* pgrx::datum::uuid::Uuid */
	"col_name" TEXT, /* &str */
	"value" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_value_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:345
-- pg_sheet::set_values
CREATE  FUNCTION "set_values"(
	"sheet_name" TEXT, /* &str */
	"cells" jsonb /* pgrx::datum::json::JsonB */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_values_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:521
-- pg_sheet::sheet_changes
CREATE  FUNCTION "sheet_changes"(
	"sheet_name" TEXT, /* &str */
	"limit" INT DEFAULT 50 /* i32 */
) RETURNS TABLE (
	"entity_id" uuid,  /* pgrx::datum::uuid::Uuid */
	"col_name" TEXT,  /* alloc::string::String */
	"old_value" TEXT,  /* core::option::Option<alloc::string::String> */
	"new_value" TEXT,  /* core::option::Option<alloc::string::String> */
	"modified_by" TEXT,  /* core::option::Option<alloc::string::String> */
	"modified_at" timestamp with time zone  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'sheet_changes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:406
-- pg_sheet::snapshot
CREATE  FUNCTION "snapshot"(
	"sheet_name" TEXT, /* &str */
	"label" TEXT DEFAULT NULL /* core::option::Option<alloc::string::String> */
) RETURNS TEXT /* alloc::string::String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'snapshot_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:557
-- pg_sheet::unlock_cell
CREATE  FUNCTION "unlock_cell"(
	"sheet_name" TEXT, /* &str */
	"entity_id" uuid, /* pgrx::datum::uuid::Uuid */
	"col_name" TEXT, /* &str */
	"force" bool DEFAULT false /* bool */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unlock_cell_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sheet/src/lib.rs:96
-- finalize

GRANT USAGE ON SCHEMA pgsheet TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA pgsheet TO PUBLIC;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA pgsheet TO PUBLIC;
/* </end connected objects> */

