/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/lib.rs:61
-- bootstrap

    -- Messages table (one row per published message)
    CREATE TABLE IF NOT EXISTS messages (
        message_id BIGSERIAL PRIMARY KEY,
        topic TEXT NOT NULL,
        payload BYTEA,
        qos SMALLINT DEFAULT 0,
        retain BOOLEAN DEFAULT false,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- Index for topic lookups
    CREATE INDEX IF NOT EXISTS idx_messages_topic ON messages(topic);
    CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);

    -- Subscriptions table
    CREATE TABLE IF NOT EXISTS subscriptions (
        subscription_id BIGSERIAL PRIMARY KEY,
        client_id TEXT NOT NULL,
        topic_filter TEXT NOT NULL,
        qos SMALLINT DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        UNIQUE(client_id, topic_filter)
    );

    -- Index for subscription lookups
    CREATE INDEX IF NOT EXISTS idx_subscriptions_client_id ON subscriptions(client_id);

    -- Client sessions table
    CREATE TABLE IF NOT EXISTS sessions (
        client_id TEXT PRIMARY KEY,
        connected_at TIMESTAMPTZ DEFAULT NOW(),
        last_seen TIMESTAMPTZ DEFAULT NOW()
    );

    -- Retained messages table (one per topic)
    CREATE TABLE IF NOT EXISTS retained (
        topic TEXT PRIMARY KEY,
        payload BYTEA,
        updated_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- Schema registry (for typed topics)
    CREATE TABLE IF NOT EXISTS schemas (
        id SERIAL PRIMARY KEY,
        subject TEXT NOT NULL,
        version INT NOT NULL DEFAULT 1,
        schema_def JSONB NOT NULL,
        fingerprint TEXT NOT NULL,
        description TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE(subject, version),
        UNIQUE(subject, fingerprint)
    );
    CREATE INDEX IF NOT EXISTS idx_schemas_subject ON schemas(subject);

    -- Schema binding + optional typed table backing
    CREATE TABLE IF NOT EXISTS topic_schemas (
        id SERIAL PRIMARY KEY,
        topic TEXT NOT NULL UNIQUE,
        schema_id INT NOT NULL REFERENCES schemas(id) ON DELETE CASCADE,
        source_table TEXT,
        validation_mode TEXT NOT NULL DEFAULT 'STRICT'
            CHECK (validation_mode IN ('STRICT', 'LOG')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_topic_schemas_topic ON topic_schemas(topic);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/lib.rs:43
-- pg_mqtt::extension_docs
CREATE  FUNCTION "extension_docs"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'extension_docs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/schema.rs:573
-- pg_mqtt::schema::mqtt_bind_schema
CREATE  FUNCTION "mqtt_bind_schema"(
	"topic" TEXT, /* &str */
	"schema_id" INT, /* i32 */
	"validation_mode" TEXT DEFAULT 'STRICT' /* &str */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_bind_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/schema.rs:714
-- pg_mqtt::schema::mqtt_create_typed_topic
CREATE  FUNCTION "mqtt_create_typed_topic"(
	"topic" TEXT, /* &str */
	"schema_def" jsonb, /* pgrx::datum::json::JsonB */
	"table_name" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"validation_mode" TEXT DEFAULT 'STRICT' /* &str */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_create_typed_topic_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/schema.rs:779
-- pg_mqtt::schema::mqtt_create_typed_topic_from_table
CREATE  FUNCTION "mqtt_create_typed_topic_from_table"(
	"topic" TEXT, /* &str */
	"table_name" TEXT, /* &str */
	"validation_mode" TEXT DEFAULT 'STRICT' /* &str */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_create_typed_topic_from_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/schema.rs:634
-- pg_mqtt::schema::mqtt_drop_schema
CREATE  FUNCTION "mqtt_drop_schema"(
	"schema_id" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_drop_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/schema.rs:546
-- pg_mqtt::schema::mqtt_get_latest_schema
CREATE  FUNCTION "mqtt_get_latest_schema"(
	"subject" TEXT /* &str */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_get_latest_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/schema.rs:535
-- pg_mqtt::schema::mqtt_get_schema
CREATE  FUNCTION "mqtt_get_schema"(
	"schema_id" INT /* i32 */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_get_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/schema.rs:557
-- pg_mqtt::schema::mqtt_get_topic_schema
CREATE  FUNCTION "mqtt_get_topic_schema"(
	"topic_name" TEXT /* &str */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_get_topic_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/lib.rs:450
-- pg_mqtt::mqtt_messages
CREATE  FUNCTION "mqtt_messages"(
	"topic_pattern" TEXT, /* &str */
	"limit" INT DEFAULT 10 /* i32 */
) RETURNS TABLE (
	"message_id" bigint,  /* i64 */
	"topic" TEXT,  /* alloc::string::String */
	"payload" TEXT,  /* alloc::string::String */
	"created_at" timestamp with time zone  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_messages_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/lib.rs:294
-- pg_mqtt::mqtt_publish
CREATE  FUNCTION "mqtt_publish"(
	"topic" TEXT, /* &str */
	"payload" TEXT /* &str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_publish_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/schema.rs:493
-- pg_mqtt::schema::mqtt_register_schema
CREATE  FUNCTION "mqtt_register_schema"(
	"subject" TEXT, /* &str */
	"schema_def" jsonb, /* pgrx::datum::json::JsonB */
	"description" TEXT /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_register_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/schema.rs:669
-- pg_mqtt::schema::mqtt_schema_from_table
CREATE  FUNCTION "mqtt_schema_from_table"(
	"table_name" TEXT /* &str */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_schema_from_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/lib.rs:513
-- pg_mqtt::mqtt_sessions
CREATE  FUNCTION "mqtt_sessions"() RETURNS TABLE (
	"client_id" TEXT,  /* alloc::string::String */
	"connected_at" timestamp with time zone,  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"last_seen" timestamp with time zone  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_sessions_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/lib.rs:273
-- pg_mqtt::mqtt_status
CREATE  FUNCTION "mqtt_status"() RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/lib.rs:505
-- pg_mqtt::mqtt_subscription_count
CREATE  FUNCTION "mqtt_subscription_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_subscription_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/schema.rs:659
-- pg_mqtt::schema::mqtt_table_from_schema
CREATE  FUNCTION "mqtt_table_from_schema"(
	"table_name" TEXT, /* &str */
	"schema_def" jsonb, /* pgrx::datum::json::JsonB */
	"add_id_column" bool DEFAULT true /* bool */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_table_from_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/schema.rs:613
-- pg_mqtt::schema::mqtt_unbind_schema
CREATE  FUNCTION "mqtt_unbind_schema"(
	"topic" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mqtt_unbind_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/lib.rs:143
-- pg_mqtt::reset_workers
CREATE  FUNCTION "reset_workers"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reset_workers_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_mqtt/src/lib.rs:143
-- pg_mqtt::worker_status
CREATE  FUNCTION "worker_status"() RETURNS TABLE (
	"worker" INT,  /* i32 */
	"name" TEXT,  /* alloc::string::String */
	"state" TEXT,  /* alloc::string::String */
	"failures" INT,  /* i32 */
	"restarts" INT,  /* i32 */
	"pid" INT,  /* i32 */
	"since" timestamp with time zone,  /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"last_failure" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'worker_status_wrapper';
/* </end connected objects> */

