//! SeqId — a typed wrapper for sequence-generated document numbers.
//!
//! Provides type safety so that columns using sequence IDs reject
//! accidental assignment of arbitrary text without an explicit cast.

use pgrx::prelude::*;
use serde::{Deserialize, Serialize};
use std::ffi::CStr;
use std::hash::{Hash, Hasher};

/// A typed document identifier generated by pg_sequence.
///
/// Behaves like TEXT at the wire level (input/output are plain strings)
/// but is a distinct PostgreSQL type. This prevents accidental assignment
/// of arbitrary text to columns typed as `seq_id`.
///
/// Usage:
/// ```sql
/// CREATE TABLE invoices (
///     invoice_no pgsequence.seqid NOT NULL,
///     amount     numeric
/// );
///
/// -- Works: next_formatted returns seq_id
/// INSERT INTO invoices (invoice_no, amount)
/// VALUES (pgsequence.next_formatted('invoice'), 100.00);
///
/// -- Fails: type mismatch
/// UPDATE invoices SET invoice_no = 'garbage';
///
/// -- Works: explicit cast
/// UPDATE invoices SET invoice_no = 'INV-2026-00050'::pgsequence.seqid;
/// ```
#[derive(
    Debug, Clone, Serialize, Deserialize, PostgresType, PostgresEq, PostgresOrd, PostgresHash,
)]
#[inoutfuncs]
pub struct SeqId(String);

impl SeqId {
    /// Create a new SeqId from a formatted string.
    pub fn new(value: String) -> Self {
        SeqId(value)
    }

    /// Get the inner string value.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

// =============================================================================
// InOutFuncs — plain string representation (no JSON wrapping)
// =============================================================================

impl InOutFuncs for SeqId {
    fn input(input: &CStr) -> Self
    where
        Self: Sized,
    {
        let s = input.to_str().expect("invalid UTF-8 in seq_id");
        if s.is_empty() {
            pgrx::error!("seq_id cannot be empty");
        }
        SeqId(s.to_string())
    }

    fn output(&self, buffer: &mut pgrx::StringInfo) {
        buffer.push_str(&self.0);
    }
}

// =============================================================================
// Trait impls for PostgresEq / PostgresOrd / PostgresHash
// =============================================================================

impl PartialEq for SeqId {
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl Eq for SeqId {}

impl PartialOrd for SeqId {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for SeqId {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.0.cmp(&other.0)
    }
}

impl Hash for SeqId {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

// =============================================================================
// Cast functions
// =============================================================================

/// Cast seq_id to text.
#[pg_extern(immutable, parallel_safe)]
pub fn seq_id_to_text(id: SeqId) -> String {
    id.0
}

/// Cast text to seq_id.
#[pg_extern(immutable, parallel_safe)]
pub fn text_to_seq_id(value: &str) -> SeqId {
    if value.is_empty() {
        pgrx::error!("seq_id cannot be empty");
    }
    SeqId(value.to_string())
}

// =============================================================================
// Register casts via extension SQL
// =============================================================================

pgrx::extension_sql!(
    r#"
CREATE CAST (SeqId AS text)
    WITH FUNCTION seq_id_to_text(SeqId)
    AS IMPLICIT;

CREATE CAST (text AS SeqId)
    WITH FUNCTION text_to_seq_id(text);
"#,
    name = "seq_id_casts",
    requires = [SeqId, seq_id_to_text, text_to_seq_id]
);

// =============================================================================
// Unit tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_seq_id_new() {
        let id = SeqId::new("INV-2026-00001".to_string());
        assert_eq!(id.as_str(), "INV-2026-00001");
    }

    #[test]
    fn test_seq_id_equality() {
        let a = SeqId::new("INV-001".to_string());
        let b = SeqId::new("INV-001".to_string());
        let c = SeqId::new("INV-002".to_string());
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    #[test]
    fn test_seq_id_ordering() {
        let a = SeqId::new("DO-000001".to_string());
        let b = SeqId::new("DO-000002".to_string());
        let c = SeqId::new("DO-000010".to_string());
        assert!(a < b);
        assert!(b < c);
    }

    #[test]
    fn test_seq_id_hash() {
        use std::collections::HashSet;
        let mut set = HashSet::new();
        set.insert(SeqId::new("INV-001".to_string()));
        set.insert(SeqId::new("INV-001".to_string()));
        assert_eq!(set.len(), 1);
    }

    #[test]
    fn test_seq_id_serde_roundtrip() {
        let id = SeqId::new("PO-2026-00042".to_string());
        let json = serde_json::to_string(&id).unwrap();
        let back: SeqId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, back);
    }
}
