/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/schema.rs:3
-- bootstrap

-- =============================================================================
-- sequence_def: defines how document numbers are generated
-- =============================================================================
CREATE TABLE @extschema@.sequence_def (
    id           SERIAL PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    prefix       TEXT NOT NULL DEFAULT '',
    suffix       TEXT NOT NULL DEFAULT '',
    format       TEXT NOT NULL DEFAULT '{prefix}{counter}{suffix}',
    counter_pad  INT NOT NULL DEFAULT 1 CHECK (counter_pad >= 1 AND counter_pad <= 20),
    start_value  BIGINT NOT NULL DEFAULT 1,
    increment    INT NOT NULL DEFAULT 1 CHECK (increment >= 1),
    reset_policy TEXT NOT NULL DEFAULT 'never' CHECK (reset_policy IN ('never','yearly','monthly')),
    gap_free     BOOLEAN NOT NULL DEFAULT false,
    description  TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- counter: active counters per sequence+scope+period combination
-- =============================================================================
CREATE TABLE @extschema@.counter (
    id            SERIAL PRIMARY KEY,
    sequence_id   INT NOT NULL REFERENCES @extschema@.sequence_def(id) ON DELETE CASCADE,
    scope_key     TEXT NOT NULL DEFAULT '',
    period_key    TEXT NOT NULL DEFAULT '',
    current_value BIGINT NOT NULL DEFAULT 0,
    UNIQUE(sequence_id, scope_key, period_key)
);
CREATE INDEX idx_counter_seq ON @extschema@.counter(sequence_id);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::SeqId
CREATE TYPE SeqId;

-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_in
CREATE  FUNCTION "seqid_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS SeqId /* core::option::Option<pg_sequence::seq_id::SeqId> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seqid_in_wrapper';

-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_out
CREATE  FUNCTION "seqid_out"(
	"input" SeqId /* pg_sequence::seq_id::SeqId */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seqid_out_wrapper';

-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::SeqId
CREATE TYPE SeqId (
	INTERNALLENGTH = variable,
	INPUT = seqid_in, /* pg_sequence::seq_id::seqid_in */
	OUTPUT = seqid_out, /* pg_sequence::seq_id::seqid_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/definition.rs:70
-- pg_sequence::definition::alter_sequence
CREATE  FUNCTION "alter_sequence"(
	"name" TEXT, /* &str */
	"prefix" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"suffix" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"format" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"counter_pad" INT DEFAULT NULL, /* core::option::Option<i32> */
	"increment" INT DEFAULT NULL, /* core::option::Option<i32> */
	"reset_policy" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"gap_free" bool DEFAULT NULL, /* core::option::Option<bool> */
	"description" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'alter_sequence_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/definition.rs:15
-- pg_sequence::definition::create_sequence
CREATE  FUNCTION "create_sequence"(
	"name" TEXT, /* &str */
	"prefix" TEXT DEFAULT '', /* core::option::Option<&str> */
	"suffix" TEXT DEFAULT '', /* core::option::Option<&str> */
	"format" TEXT DEFAULT '{prefix}{counter}{suffix}', /* core::option::Option<&str> */
	"counter_pad" INT DEFAULT 1, /* core::option::Option<i32> */
	"start_value" bigint DEFAULT 1, /* core::option::Option<i64> */
	"increment" INT DEFAULT 1, /* core::option::Option<i32> */
	"reset_policy" TEXT DEFAULT 'never', /* core::option::Option<&str> */
	"gap_free" bool DEFAULT false, /* core::option::Option<bool> */
	"description" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_sequence_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/generate.rs:155
-- pg_sequence::generate::current_val
CREATE  FUNCTION "current_val"(
	"name" TEXT, /* &str */
	"scope_key" TEXT DEFAULT '' /* core::option::Option<&str> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'current_val_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/definition.rs:152
-- pg_sequence::definition::drop_sequence
CREATE  FUNCTION "drop_sequence"(
	"name" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_sequence_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/queries.rs:116
-- pg_sequence::queries::list_counters
CREATE  FUNCTION "list_counters"(
	"name" TEXT /* &str */
) RETURNS TABLE (
	"scope_key" TEXT,  /* alloc::string::String */
	"period_key" TEXT,  /* alloc::string::String */
	"current_value" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_counters_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/queries.rs:7
-- pg_sequence::queries::list_sequences
CREATE  FUNCTION "list_sequences"() RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"prefix" TEXT,  /* alloc::string::String */
	"format" TEXT,  /* alloc::string::String */
	"reset_policy" TEXT,  /* alloc::string::String */
	"gap_free" bool,  /* bool */
	"description" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_sequences_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/generate.rs:112
-- pg_sequence::generate::next_formatted
CREATE  FUNCTION "next_formatted"(
	"name" TEXT, /* &str */
	"scope_key" TEXT DEFAULT '' /* core::option::Option<&str> */
) RETURNS SeqId /* pg_sequence::seq_id::SeqId */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'next_formatted_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/generate.rs:84
-- pg_sequence::generate::next_val
CREATE  FUNCTION "next_val"(
	"name" TEXT, /* &str */
	"scope_key" TEXT DEFAULT '' /* core::option::Option<&str> */
) RETURNS bigint /* i64 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'next_val_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/generate.rs:174
-- pg_sequence::generate::preview
CREATE  FUNCTION "preview"(
	"name" TEXT, /* &str */
	"scope_key" TEXT DEFAULT '' /* core::option::Option<&str> */
) RETURNS SeqId /* pg_sequence::seq_id::SeqId */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'preview_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/generate.rs:215
-- pg_sequence::generate::reset_counter
CREATE  FUNCTION "reset_counter"(
	"name" TEXT, /* &str */
	"scope_key" TEXT DEFAULT '', /* core::option::Option<&str> */
	"new_value" bigint DEFAULT NULL /* core::option::Option<i64> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reset_counter_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seed.rs:4
-- pg_sequence::seed::seed_common
CREATE  FUNCTION "seed_common"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seed_common_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:108
-- pg_sequence::seq_id::seq_id_to_text
CREATE  FUNCTION "seq_id_to_text"(
	"id" SeqId /* pg_sequence::seq_id::SeqId */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seq_id_to_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_cmp
CREATE  FUNCTION "seqid_cmp"(
	"left" SeqId, /* pg_sequence::seq_id::SeqId */
	"right" SeqId /* pg_sequence::seq_id::SeqId */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seqid_cmp_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_eq
CREATE  FUNCTION "seqid_eq"(
	"left" SeqId, /* pg_sequence::seq_id::SeqId */
	"right" SeqId /* pg_sequence::seq_id::SeqId */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seqid_eq_wrapper';

-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_eq
CREATE OPERATOR = (
	PROCEDURE="seqid_eq",
	LEFTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	RIGHTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	COMMUTATOR = =,
	NEGATOR = <>,
	RESTRICT = eqsel,
	JOIN = eqjoinsel,
	HASHES,
	MERGES
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_ge
CREATE  FUNCTION "seqid_ge"(
	"left" SeqId, /* pg_sequence::seq_id::SeqId */
	"right" SeqId /* pg_sequence::seq_id::SeqId */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seqid_ge_wrapper';

-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_ge
CREATE OPERATOR >= (
	PROCEDURE="seqid_ge",
	LEFTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	RIGHTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	COMMUTATOR = <=,
	NEGATOR = <,
	RESTRICT = scalargesel,
	JOIN = scalargejoinsel
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_gt
CREATE  FUNCTION "seqid_gt"(
	"left" SeqId, /* pg_sequence::seq_id::SeqId */
	"right" SeqId /* pg_sequence::seq_id::SeqId */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seqid_gt_wrapper';

-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_gt
CREATE OPERATOR > (
	PROCEDURE="seqid_gt",
	LEFTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	RIGHTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	COMMUTATOR = <,
	NEGATOR = <=,
	RESTRICT = scalargtsel,
	JOIN = scalargtjoinsel
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_hash
CREATE  FUNCTION "seqid_hash"(
	"value" SeqId /* pg_sequence::seq_id::SeqId */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seqid_hash_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_le
CREATE  FUNCTION "seqid_le"(
	"left" SeqId, /* pg_sequence::seq_id::SeqId */
	"right" SeqId /* pg_sequence::seq_id::SeqId */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seqid_le_wrapper';

-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_le
CREATE OPERATOR <= (
	PROCEDURE="seqid_le",
	LEFTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	RIGHTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	COMMUTATOR = >=,
	NEGATOR = >,
	RESTRICT = scalarlesel,
	JOIN = scalarlejoinsel
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_lt
CREATE  FUNCTION "seqid_lt"(
	"left" SeqId, /* pg_sequence::seq_id::SeqId */
	"right" SeqId /* pg_sequence::seq_id::SeqId */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seqid_lt_wrapper';

-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_lt
CREATE OPERATOR < (
	PROCEDURE="seqid_lt",
	LEFTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	RIGHTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	COMMUTATOR = >,
	NEGATOR = >=,
	RESTRICT = scalarltsel,
	JOIN = scalarltjoinsel
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_ne
CREATE  FUNCTION "seqid_ne"(
	"left" SeqId, /* pg_sequence::seq_id::SeqId */
	"right" SeqId /* pg_sequence::seq_id::SeqId */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'seqid_ne_wrapper';

-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::seqid_ne
CREATE OPERATOR <> (
	PROCEDURE="seqid_ne",
	LEFTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	RIGHTARG=SeqId, /* pg_sequence::seq_id::SeqId */
	COMMUTATOR = <>,
	NEGATOR = =,
	RESTRICT = neqsel,
	JOIN = neqjoinsel
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/queries.rs:49
-- pg_sequence::queries::sequence_info
CREATE  FUNCTION "sequence_info"(
	"name" TEXT /* &str */
) RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"prefix" TEXT,  /* alloc::string::String */
	"suffix" TEXT,  /* alloc::string::String */
	"format" TEXT,  /* alloc::string::String */
	"counter_pad" INT,  /* i32 */
	"start_value" bigint,  /* i64 */
	"increment" INT,  /* i32 */
	"reset_policy" TEXT,  /* alloc::string::String */
	"gap_free" bool,  /* bool */
	"counter_count" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'sequence_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:114
-- pg_sequence::seq_id::text_to_seq_id
CREATE  FUNCTION "text_to_seq_id"(
	"value" TEXT /* &str */
) RETURNS SeqId /* pg_sequence::seq_id::SeqId */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'text_to_seq_id_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:126
-- requires:
--   SeqId
--   seq_id_to_text
--   text_to_seq_id


CREATE CAST (SeqId AS text)
    WITH FUNCTION seq_id_to_text(SeqId)
    AS IMPLICIT;

CREATE CAST (text AS SeqId)
    WITH FUNCTION text_to_seq_id(text);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::SeqId
CREATE OPERATOR FAMILY SeqId_btree_ops USING btree;
CREATE OPERATOR CLASS SeqId_btree_ops DEFAULT FOR TYPE SeqId USING btree FAMILY SeqId_btree_ops AS
	OPERATOR 1 <,
	OPERATOR 2 <=,
	OPERATOR 3 =,
	OPERATOR 4 >=,
	OPERATOR 5 >,
	FUNCTION 1 seqid_cmp(SeqId, SeqId);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_sequence/src/seq_id.rs:35
-- pg_sequence::seq_id::SeqId
CREATE OPERATOR FAMILY SeqId_hash_ops USING hash;
CREATE OPERATOR CLASS SeqId_hash_ops DEFAULT FOR TYPE SeqId USING hash FAMILY SeqId_hash_ops AS
	OPERATOR    1   =  (SeqId, SeqId),
	FUNCTION    1   seqid_hash(SeqId);
/* </end connected objects> */

