/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/schema.rs:3
-- bootstrap

-- =============================================================================
-- Machine definition: a named state machine with an initial state
-- =============================================================================
CREATE TABLE @extschema@.machine (
    id          SERIAL PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    initial     TEXT NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- Valid states per machine
-- =============================================================================
CREATE TABLE @extschema@.state (
    id          SERIAL PRIMARY KEY,
    machine_id  INT NOT NULL REFERENCES @extschema@.machine(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    is_final    BOOLEAN NOT NULL DEFAULT false,
    description TEXT,
    UNIQUE(machine_id, name)
);

-- =============================================================================
-- Transitions: (machine, from_state, event) -> to_state
-- =============================================================================
CREATE TABLE @extschema@.transition (
    id                SERIAL PRIMARY KEY,
    machine_id        INT NOT NULL REFERENCES @extschema@.machine(id) ON DELETE CASCADE,
    from_state        TEXT NOT NULL,
    to_state          TEXT NOT NULL,
    event             TEXT NOT NULL,
    guard             TEXT,
    priority          INT NOT NULL DEFAULT 0,
    description       TEXT,
    label             TEXT,
    variant           TEXT CHECK (variant IS NULL OR variant IN ('default', 'primary', 'danger', 'outline')),
    sort_order        INT NOT NULL DEFAULT 0,
    confirm_required  BOOLEAN NOT NULL DEFAULT false,
    UNIQUE(machine_id, from_state, event, priority)
);

CREATE INDEX idx_transition_lookup ON @extschema@.transition(machine_id, from_state, event);

-- =============================================================================
-- Actions: side effects executed on transition
-- =============================================================================
CREATE TABLE @extschema@.action (
    id              SERIAL PRIMARY KEY,
    transition_id   INT NOT NULL REFERENCES @extschema@.transition(id) ON DELETE CASCADE,
    action_type     TEXT NOT NULL CHECK (action_type IN ('notify', 'sql', 'function')),
    action_value    TEXT NOT NULL,
    run_order       INT NOT NULL DEFAULT 0,
    phase           TEXT NOT NULL DEFAULT 'after' CHECK (phase IN ('before', 'after'))
);

-- =============================================================================
-- Table bindings: which tables are governed by which machine
-- =============================================================================
CREATE TABLE @extschema@.binding (
    id              SERIAL PRIMARY KEY,
    machine_id      INT NOT NULL REFERENCES @extschema@.machine(id) ON DELETE CASCADE,
    table_name      TEXT NOT NULL,
    status_column   TEXT NOT NULL DEFAULT 'status',
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(table_name, status_column)
);

-- =============================================================================
-- Transition history: immutable audit trail
-- =============================================================================
CREATE TABLE @extschema@.history (
    id                  BIGSERIAL PRIMARY KEY,
    machine_id          INT NOT NULL,
    table_name          TEXT NOT NULL,
    row_id              TEXT,
    old_state           TEXT NOT NULL,
    new_state           TEXT NOT NULL,
    event               TEXT,
    transitioned_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    transitioned_by     TEXT DEFAULT current_user
);

CREATE INDEX idx_history_table_row ON @extschema@.history(table_name, row_id);
CREATE INDEX idx_history_machine ON @extschema@.history(machine_id);

-- =============================================================================
-- Immutability: prevent UPDATE/DELETE on history
-- =============================================================================
CREATE FUNCTION @extschema@.prevent_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'pg_fsm: transition history is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER history_immutable
    BEFORE UPDATE OR DELETE ON @extschema@.history
    FOR EACH ROW EXECUTE FUNCTION @extschema@.prevent_mutation();
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/machine.rs:204
-- pg_fsm::machine::add_action
CREATE  FUNCTION "add_action"(
	"transition_id" INT, /* i32 */
	"action_type" TEXT, /* &str */
	"action_value" TEXT, /* &str */
	"run_order" INT DEFAULT 0, /* core::option::Option<i32> */
	"phase" TEXT DEFAULT 'after' /* core::option::Option<&str> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_action_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/machine.rs:53
-- pg_fsm::machine::add_state
CREATE  FUNCTION "add_state"(
	"machine_name" TEXT, /* &str */
	"state_name" TEXT, /* &str */
	"is_final" bool DEFAULT false, /* core::option::Option<bool> */
	"description" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"if_not_exists" bool DEFAULT false /* core::option::Option<bool> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/machine.rs:92
-- pg_fsm::machine::add_transition
CREATE  FUNCTION "add_transition"(
	"machine_name" TEXT, /* &str */
	"from_state" TEXT, /* &str */
	"to_state" TEXT, /* &str */
	"event" TEXT, /* &str */
	"guard" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"description" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"label" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"variant" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"sort_order" INT DEFAULT 0, /* core::option::Option<i32> */
	"confirm_required" bool DEFAULT false, /* core::option::Option<bool> */
	"if_not_exists" bool DEFAULT false /* core::option::Option<bool> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_transition_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/transition.rs:246
-- pg_fsm::transition::available_events
CREATE  FUNCTION "available_events"(
	"table_name" TEXT, /* &str */
	"row_id" TEXT, /* &str */
	"status_column" TEXT DEFAULT 'status' /* core::option::Option<&str> */
) RETURNS TABLE (
	"event" TEXT,  /* alloc::string::String */
	"to_state" TEXT,  /* alloc::string::String */
	"description" TEXT,  /* core::option::Option<alloc::string::String> */
	"label" TEXT,  /* alloc::string::String */
	"variant" TEXT,  /* core::option::Option<alloc::string::String> */
	"sort_order" INT,  /* i32 */
	"confirm_required" bool  /* bool */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'available_events_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/transition.rs:330
-- pg_fsm::transition::available_events_batch
CREATE  FUNCTION "available_events_batch"(
	"table_name" TEXT, /* &str */
	"row_ids" bigint[], /* pgrx::datum::array::Array<'_, i64> */
	"status_column" TEXT DEFAULT 'status' /* core::option::Option<&str> */
) RETURNS TABLE (
	"row_id" bigint,  /* i64 */
	"event" TEXT,  /* alloc::string::String */
	"to_state" TEXT,  /* alloc::string::String */
	"label" TEXT,  /* alloc::string::String */
	"variant" TEXT,  /* core::option::Option<alloc::string::String> */
	"sort_order" INT,  /* i32 */
	"confirm_required" bool  /* bool */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'available_events_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/binding.rs:5
-- pg_fsm::binding::bind_table
CREATE  FUNCTION "bind_table"(
	"machine_name" TEXT, /* &str */
	"table_name" TEXT, /* &str */
	"status_column" TEXT DEFAULT 'status' /* core::option::Option<&str> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bind_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/transition.rs:72
-- pg_fsm::transition::can_transition
CREATE  FUNCTION "can_transition"(
	"table_name" TEXT, /* &str */
	"row_id" TEXT, /* &str */
	"event" TEXT, /* &str */
	"status_column" TEXT DEFAULT 'status' /* core::option::Option<&str> */
) RETURNS bool /* bool */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'can_transition_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/machine.rs:5
-- pg_fsm::machine::create_machine
CREATE  FUNCTION "create_machine"(
	"name" TEXT, /* &str */
	"initial_state" TEXT, /* &str */
	"description" TEXT DEFAULT NULL, /* core::option::Option<&str> */
	"if_not_exists" bool DEFAULT false /* core::option::Option<bool> */
) RETURNS INT /* i32 */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_machine_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/queries.rs:145
-- pg_fsm::queries::current_state
CREATE  FUNCTION "current_state"(
	"table_name" TEXT, /* &str */
	"row_id" TEXT, /* &str */
	"status_column" TEXT DEFAULT 'status' /* core::option::Option<&str> */
) RETURNS TEXT /* alloc::string::String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'current_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/machine.rs:258
-- pg_fsm::machine::drop_machine
CREATE  FUNCTION "drop_machine"(
	"machine_name" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_machine_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/transition.rs:123
-- pg_fsm::transition::events_with_targets
CREATE  FUNCTION "events_with_targets"(
	"table_name" TEXT, /* &str */
	"row_id" TEXT, /* &str */
	"status_column" TEXT DEFAULT 'status' /* core::option::Option<&str> */
) RETURNS TABLE (
	"event" TEXT,  /* alloc::string::String */
	"to_state" TEXT,  /* core::option::Option<alloc::string::String> */
	"label" TEXT,  /* alloc::string::String */
	"variant" TEXT,  /* core::option::Option<alloc::string::String> */
	"available" bool,  /* bool */
	"reason_unavailable" TEXT  /* core::option::Option<alloc::string::String> */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'events_with_targets_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/queries.rs:6
-- pg_fsm::queries::history_for
CREATE  FUNCTION "history_for"(
	"table_name" TEXT, /* &str */
	"row_id" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TABLE (
	"old_state" TEXT,  /* alloc::string::String */
	"new_state" TEXT,  /* alloc::string::String */
	"event" TEXT,  /* core::option::Option<alloc::string::String> */
	"transitioned_at" timestamp with time zone,  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"transitioned_by" TEXT  /* core::option::Option<alloc::string::String> */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'history_for_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/queries.rs:75
-- pg_fsm::queries::history_for_paginated
CREATE  FUNCTION "history_for_paginated"(
	"table_name" TEXT, /* &str */
	"row_id" TEXT, /* &str */
	"before" timestamp with time zone DEFAULT NULL, /* core::option::Option<pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone> */
	"limit" INT DEFAULT 50 /* i32 */
) RETURNS TABLE (
	"old_state" TEXT,  /* alloc::string::String */
	"new_state" TEXT,  /* alloc::string::String */
	"event" TEXT,  /* core::option::Option<alloc::string::String> */
	"transitioned_at" timestamp with time zone,  /* pgrx::datum::time_stamp_with_timezone::TimestampWithTimeZone */
	"transitioned_by" TEXT  /* core::option::Option<alloc::string::String> */
)
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'history_for_paginated_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/queries.rs:230
-- pg_fsm::queries::list_events
CREATE  FUNCTION "list_events"(
	"machine_name" TEXT /* &str */
) RETURNS TEXT[] /* alloc::vec::Vec<alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_events_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/queries.rs:169
-- pg_fsm::queries::list_machines
CREATE  FUNCTION "list_machines"() RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"initial_state" TEXT,  /* alloc::string::String */
	"description" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_machines_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/queries.rs:198
-- pg_fsm::queries::list_states
CREATE  FUNCTION "list_states"(
	"machine_name" TEXT /* &str */
) RETURNS TABLE (
	"name" TEXT,  /* alloc::string::String */
	"is_final" bool,  /* bool */
	"description" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_states_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/queries.rs:252
-- pg_fsm::queries::list_transitions
CREATE  FUNCTION "list_transitions"(
	"machine_name" TEXT /* &str */
) RETURNS TABLE (
	"from_state" TEXT,  /* alloc::string::String */
	"event" TEXT,  /* alloc::string::String */
	"to_state" TEXT,  /* alloc::string::String */
	"guard" TEXT,  /* core::option::Option<alloc::string::String> */
	"label" TEXT,  /* core::option::Option<alloc::string::String> */
	"variant" TEXT,  /* core::option::Option<alloc::string::String> */
	"sort_order" INT  /* i32 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_transitions_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/queries.rs:311
-- pg_fsm::queries::machine_diagram
CREATE  FUNCTION "machine_diagram"(
	"machine_name" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'machine_diagram_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/queries.rs:393
-- pg_fsm::queries::machine_diagram_mermaid
CREATE  FUNCTION "machine_diagram_mermaid"(
	"machine_name" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'machine_diagram_mermaid_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/transition.rs:597
-- pg_fsm::transition::resolve_binding
CREATE  FUNCTION "resolve_binding"(
	"target" regclass, /* pgrx::rel::PgRelation */
	"status_column" TEXT DEFAULT 'status' /* core::option::Option<&str> */
) RETURNS TEXT /* core::option::Option<alloc::string::String> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'resolve_binding_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/transition.rs:9
-- pg_fsm::transition::transition
CREATE  FUNCTION "transition"(
	"table_name" TEXT, /* &str */
	"row_id" TEXT, /* &str */
	"event" TEXT, /* &str */
	"status_column" TEXT DEFAULT 'status', /* core::option::Option<&str> */
	"allow_noop" bool DEFAULT false /* core::option::Option<bool> */
) RETURNS TEXT /* alloc::string::String */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'transition_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/binding.rs:69
-- pg_fsm::binding::unbind_table
CREATE  FUNCTION "unbind_table"(
	"table_name" TEXT, /* &str */
	"status_column" TEXT DEFAULT 'status' /* core::option::Option<&str> */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unbind_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/binding.rs:154
-- pg_fsm::binding::validate_insert
CREATE  FUNCTION "validate_insert"(
	"table_name" TEXT, /* &str */
	"status_column" TEXT, /* &str */
	"row" jsonb /* pgrx::datum::json::JsonB */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'validate_insert_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_fsm/src/binding.rs:196
-- pg_fsm::binding::validate_transition
CREATE  FUNCTION "validate_transition"(
	"table_name" TEXT, /* &str */
	"status_column" TEXT, /* &str */
	"old_state" TEXT, /* &str */
	"new_state" TEXT, /* &str */
	"row" jsonb /* pgrx::datum::json::JsonB */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'validate_transition_wrapper';
/* </end connected objects> */

