/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/eidos_catalog.rs:29

-- ============================================================================
-- pg_solid eidos_catalog contract — v1
--   Spec: https://github.com/matroidbe/eidos/blob/main/docs/development/eidos-catalog-contract.md
-- ============================================================================

-- Type mapping helper. Mirrors eidos-core's discover.rs::pg_type_to_eidos
-- exactly. Eidos cross-checks each arg/return pg_type → eidos_type at
-- discovery-time; a divergence here fails plugin import.
CREATE OR REPLACE FUNCTION _eidos_pg_to_eidos_type(udt_name TEXT)
RETURNS TEXT LANGUAGE sql IMMUTABLE SET search_path = pgsolid, public AS $body$
    SELECT CASE lower(udt_name)
        WHEN 'int2'        THEN 'integer'
        WHEN 'int4'        THEN 'integer'
        WHEN 'int8'        THEN 'integer'
        WHEN 'smallint'    THEN 'integer'
        WHEN 'integer'     THEN 'integer'
        WHEN 'bigint'      THEN 'integer'
        WHEN 'float4'      THEN 'decimal'
        WHEN 'float8'      THEN 'decimal'
        WHEN 'numeric'     THEN 'decimal'
        WHEN 'decimal'     THEN 'decimal'
        WHEN 'real'        THEN 'decimal'
        WHEN 'bool'        THEN 'boolean'
        WHEN 'boolean'     THEN 'boolean'
        WHEN 'text'        THEN 'text'
        WHEN 'varchar'     THEN 'text'
        WHEN 'bpchar'      THEN 'text'
        WHEN 'character'   THEN 'text'
        WHEN 'date'        THEN 'date'
        WHEN 'timestamp'   THEN 'timestamp'
        WHEN 'timestamptz' THEN 'timestamp'
        WHEN 'uuid'        THEN 'uuid'
        WHEN 'jsonb'       THEN 'jsonb'
        WHEN 'json'        THEN 'jsonb'
        WHEN 'money'       THEN 'money'
        WHEN 'bytea'       THEN 'bytea'
        ELSE 'text /* ' || udt_name || ' */'
    END;
$body$;

-- Helper: build the args JSONB for a function from pg_proc so the live
-- signature is the source of truth. Returns NULL if the function doesn't exist
-- (so the catalog fails fast on schema drift), '[]' for a zero-arg function.
CREATE OR REPLACE FUNCTION _eidos_args_for(p_schema TEXT, p_func TEXT, descs JSONB DEFAULT '{}'::jsonb)
RETURNS JSONB LANGUAGE sql STABLE SET search_path = pgsolid, public AS $body$
    WITH proc AS (
        SELECT p.oid, p.proargnames, p.proargtypes, p.pronargs, p.pronargdefaults
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = p_schema AND p.proname = p_func
        -- Deterministic on overloaded names: lowest oid = earliest-created.
        ORDER BY p.oid
        LIMIT 1
    ),
    args AS (
        SELECT
            COALESCE(proc.proargnames[i+1], 'arg' || (i+1)::text) AS name,
            format_type(proc.proargtypes[i], NULL)              AS pg_type_full,
            (SELECT typname FROM pg_type WHERE oid = proc.proargtypes[i]) AS udt,
            (i+1) > (proc.pronargs - proc.pronargdefaults)      AS has_default,
            i AS pos
        FROM proc, generate_series(0, proc.pronargs - 1) i
    )
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'name',        a.name,
        'pg_type',     a.pg_type_full,
        'eidos_type',  _eidos_pg_to_eidos_type(a.udt),
        'required',    NOT a.has_default,
        'description', descs->a.name
    ) ORDER BY a.pos), CASE WHEN EXISTS (SELECT 1 FROM proc) THEN '[]'::jsonb END)
    FROM args a;
$body$;

-- Helper: build the returns descriptor from pg_proc.
CREATE OR REPLACE FUNCTION _eidos_returns_for(p_schema TEXT, p_func TEXT, p_shape TEXT DEFAULT 'scalar')
RETURNS JSONB LANGUAGE sql STABLE SET search_path = pgsolid, public AS $body$
    WITH proc AS (
        SELECT format_type(p.prorettype, NULL) AS pg_type_full,
               (SELECT typname FROM pg_type WHERE oid = p.prorettype) AS udt
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = p_schema AND p.proname = p_func
        ORDER BY p.oid
        LIMIT 1
    )
    SELECT jsonb_build_object(
        'pg_type',    pg_type_full,
        'eidos_type', _eidos_pg_to_eidos_type(udt),
        'shape',      p_shape
    ) FROM proc;
$body$;

-- ============================================================================
-- eidos_catalog_meta — required
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_meta() RETURNS jsonb
LANGUAGE sql STABLE SET search_path = pgsolid, public AS $body$
    SELECT jsonb_build_object(
        'extension',      'pg_solid',
        -- Read the installed version live so meta can never go stale against
        -- the actual extension.
        'version',        COALESCE((SELECT extversion FROM pg_extension WHERE extname = 'pg_solid'), '0.0.0'),
        'eidos_protocol', '1',
        'display_name',   'Solid Geometry',
        'description',    '3D B-Rep solid modelling on OpenCASCADE: construction, booleans, measurement, export',
        'icon',           'box',
        'primary_color',  '#f59e0b',
        'domains',        ARRAY['geometry']
    );
$body$;

-- ============================================================================
-- eidos_catalog_entities — required
-- pg_solid is a compute extension: no domain entities. Return zero rows.
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_entities() RETURNS TABLE (
    name              text,
    schema_name       text,
    table_name        text,
    primary_key       text[],
    columns           jsonb,
    domain            text,
    display_name      text,
    icon              text,
    read_only         boolean,
    fsm_machine       text,
    default_sort      text,
    search_columns    text[]
) LANGUAGE sql STABLE SET search_path = pgsolid, public AS $body$
    SELECT NULL::text, NULL::text, NULL::text, NULL::text[], NULL::jsonb,
           NULL::text, NULL::text, NULL::text, NULL::boolean, NULL::text,
           NULL::text, NULL::text[]
    WHERE false;
$body$;

-- ============================================================================
-- eidos_catalog_functions — required
--
-- The curated public surface. SIGNATURES come from pg_proc via
-- _eidos_args_for / _eidos_returns_for (no drift possible); the side-effect
-- class + display metadata are authored here.
-- ============================================================================

CREATE OR REPLACE FUNCTION eidos_catalog_functions() RETURNS TABLE (
    name              text,
    schema_name       text,
    args              jsonb,
    returns           jsonb,
    side_effects      text,
    fsm_event         jsonb,
    suggested_roles   text[],
    domain            text,
    display_name      text,
    icon              text,
    danger            boolean
) LANGUAGE sql STABLE SET search_path = pgsolid, public AS $body$
    WITH defs(name, side_effects, domain, display_name, icon, danger, return_shape) AS (
        VALUES
            ('solid_box'             , 'query'  , 'geometry', 'Box'             , 'box'             , false, 'scalar'),
            ('solid_cylinder'        , 'query'  , 'geometry', 'Cylinder'        , 'cylinder'        , false, 'scalar'),
            ('solid_sphere'          , 'query'  , 'geometry', 'Sphere'          , 'circle'          , false, 'scalar'),
            ('solid_cone'            , 'query'  , 'geometry', 'Cone'            , 'cone'            , false, 'scalar'),
            ('solid_volume'          , 'query'  , 'geometry', 'Volume'          , 'box'             , false, 'scalar'),
            ('solid_surface_area'    , 'query'  , 'geometry', 'Surface area'    , 'square'          , false, 'scalar'),
            ('solid_bbox'            , 'query'  , 'geometry', 'Bounding box'    , 'frame'           , false, 'scalar'),
            ('solid_centroid'        , 'query'  , 'geometry', 'Centroid'        , 'crosshair'       , false, 'scalar'),
            ('solid_dimensions'      , 'query'  , 'geometry', 'Dimensions'      , 'ruler'           , false, 'scalar'),
            ('solid_face_count'      , 'query'  , 'geometry', 'Face count'      , 'hash'            , false, 'scalar'),
            ('solid_is_valid'        , 'query'  , 'geometry', 'Is valid'        , 'check-circle'    , false, 'scalar'),
            ('solid_num_solids'      , 'query'  , 'geometry', 'Body count'      , 'layers'          , false, 'scalar'),
            ('solid_distance'        , 'query'  , 'geometry', 'Distance'        , 'move-horizontal' , false, 'scalar'),
            ('solid_intersects'      , 'query'  , 'geometry', 'Intersects'      , 'git-merge'       , false, 'scalar'),
            ('solid_contains'        , 'query'  , 'geometry', 'Contains'        , 'package'         , false, 'scalar'),
            ('solid_touches'         , 'query'  , 'geometry', 'Touches'         , 'link'            , false, 'scalar'),
            ('solid_within_clearance', 'query'  , 'geometry', 'Within clearance', 'shield'          , false, 'scalar'),
            ('solid_shared_face_area', 'query'  , 'geometry', 'Shared face area', 'square'          , false, 'scalar'),
            ('solid_union'           , 'query'  , 'geometry', 'Union'           , 'git-merge'       , false, 'scalar'),
            ('solid_difference'      , 'query'  , 'geometry', 'Difference'      , 'minus-circle'    , false, 'scalar'),
            ('solid_intersection'    , 'query'  , 'geometry', 'Intersection'    , 'git-pull-request', false, 'scalar'),
            ('solid_heal'            , 'query'  , 'geometry', 'Heal'            , 'wrench'          , false, 'scalar'),
            ('solid_translate'       , 'query'  , 'geometry', 'Translate'       , 'move'            , false, 'scalar'),
            ('solid_rotate'          , 'query'  , 'geometry', 'Rotate'          , 'rotate-3d'       , false, 'scalar'),
            ('solid_to_stl'          , 'query'  , 'geometry', 'Export STL'      , 'file-down'       , false, 'scalar'),
            ('solid_to_step'         , 'query'  , 'geometry', 'Export STEP'     , 'file-down'       , false, 'scalar'),
            ('solid_to_glb'          , 'query'  , 'geometry', 'Export GLB'      , 'file-down'       , false, 'scalar')
    )
    SELECT
        d.name,
        'pgsolid'::text                                           AS schema_name,
        _eidos_args_for('pgsolid', d.name)                        AS args,
        _eidos_returns_for('pgsolid', d.name, d.return_shape)     AS returns,
        d.side_effects,
        NULL::jsonb                                                AS fsm_event,
        ARRAY['admin']::text[]                                     AS suggested_roles,
        d.domain,
        d.display_name,
        d.icon,
        d.danger
    FROM defs d;
$body$;

GRANT EXECUTE ON FUNCTION _eidos_pg_to_eidos_type(text)        TO PUBLIC;
GRANT EXECUTE ON FUNCTION _eidos_args_for(text, text, jsonb)   TO PUBLIC;
GRANT EXECUTE ON FUNCTION _eidos_returns_for(text, text, text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_meta()                 TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_entities()             TO PUBLIC;
GRANT EXECUTE ON FUNCTION eidos_catalog_functions()            TO PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/types/bbox3d.rs:5
-- pg_solid::types::bbox3d::BBox3D
CREATE TYPE BBox3D;

-- extensions/pg_solid/src/types/bbox3d.rs:5
-- pg_solid::types::bbox3d::bbox3d_in
CREATE  FUNCTION "bbox3d_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS BBox3D /* core::option::Option<pg_solid::types::bbox3d::BBox3D> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bbox3d_in_wrapper';

-- extensions/pg_solid/src/types/bbox3d.rs:5
-- pg_solid::types::bbox3d::bbox3d_out
CREATE  FUNCTION "bbox3d_out"(
	"input" BBox3D /* pg_solid::types::bbox3d::BBox3D */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bbox3d_out_wrapper';

-- extensions/pg_solid/src/types/bbox3d.rs:5
-- pg_solid::types::bbox3d::BBox3D
CREATE TYPE BBox3D (
	INTERNALLENGTH = variable,
	INPUT = bbox3d_in, /* pg_solid::types::bbox3d::bbox3d_in */
	OUTPUT = bbox3d_out, /* pg_solid::types::bbox3d::bbox3d_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/types/point3d.rs:5
-- pg_solid::types::point3d::Point3D
CREATE TYPE Point3D;

-- extensions/pg_solid/src/types/point3d.rs:5
-- pg_solid::types::point3d::point3d_in
CREATE  FUNCTION "point3d_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS Point3D /* core::option::Option<pg_solid::types::point3d::Point3D> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'point3d_in_wrapper';

-- extensions/pg_solid/src/types/point3d.rs:5
-- pg_solid::types::point3d::point3d_out
CREATE  FUNCTION "point3d_out"(
	"input" Point3D /* pg_solid::types::point3d::Point3D */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'point3d_out_wrapper';

-- extensions/pg_solid/src/types/point3d.rs:5
-- pg_solid::types::point3d::Point3D
CREATE TYPE Point3D (
	INTERNALLENGTH = variable,
	INPUT = point3d_in, /* pg_solid::types::point3d::point3d_in */
	OUTPUT = point3d_out, /* pg_solid::types::point3d::point3d_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/types/solid.rs:39
-- pg_solid::types::solid::Solid
CREATE TYPE Solid;

-- extensions/pg_solid/src/types/solid.rs:39
-- pg_solid::types::solid::solid_in
CREATE  FUNCTION "solid_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS Solid /* core::option::Option<pg_solid::types::solid::Solid> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_in_wrapper';

-- extensions/pg_solid/src/types/solid.rs:39
-- pg_solid::types::solid::solid_out
CREATE  FUNCTION "solid_out"(
	"input" Solid /* pg_solid::types::solid::Solid */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_out_wrapper';

-- extensions/pg_solid/src/types/solid.rs:39
-- pg_solid::types::solid::Solid
CREATE TYPE Solid (
	INTERNALLENGTH = variable,
	INPUT = solid_in, /* pg_solid::types::solid::solid_in */
	OUTPUT = solid_out, /* pg_solid::types::solid::solid_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/aggregates.rs:66
-- pg_solid::functions::aggregates::SolidAggBbox
CREATE TYPE SolidAggBbox;

-- extensions/pg_solid/src/functions/aggregates.rs:66
-- pg_solid::functions::aggregates::solidaggbbox_in
CREATE  FUNCTION "solidaggbbox_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS SolidAggBbox /* core::option::Option<pg_solid::functions::aggregates::SolidAggBbox> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solidaggbbox_in_wrapper';

-- extensions/pg_solid/src/functions/aggregates.rs:66
-- pg_solid::functions::aggregates::solidaggbbox_out
CREATE  FUNCTION "solidaggbbox_out"(
	"input" SolidAggBbox /* pg_solid::functions::aggregates::SolidAggBbox */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solidaggbbox_out_wrapper';

-- extensions/pg_solid/src/functions/aggregates.rs:66
-- pg_solid::functions::aggregates::solidaggbbox_recv
CREATE  FUNCTION "solidaggbbox_recv"(
	"internal" internal /* pgrx::datum::internal::Internal */
) RETURNS SolidAggBbox /* pg_solid::functions::aggregates::SolidAggBbox */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solidaggbbox_recv_wrapper';

-- extensions/pg_solid/src/functions/aggregates.rs:66
-- pg_solid::functions::aggregates::solidaggbbox_send
CREATE  FUNCTION "solidaggbbox_send"(
	"input" SolidAggBbox /* pg_solid::functions::aggregates::SolidAggBbox */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solidaggbbox_send_wrapper';


-- extensions/pg_solid/src/functions/aggregates.rs:66
-- pg_solid::functions::aggregates::SolidAggBbox
CREATE TYPE SolidAggBbox (
	INTERNALLENGTH = variable,
	INPUT = solidaggbbox_in, /* pg_solid::functions::aggregates::solidaggbbox_in */
	OUTPUT = solidaggbbox_out, /* pg_solid::functions::aggregates::solidaggbbox_out */
	RECEIVE = solidaggbbox_recv, /* pg_solid::functions::aggregates::solidaggbbox_recv */
	SEND = solidaggbbox_send, /* pg_solid::functions::aggregates::solidaggbbox_send */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/aggregates.rs:12
-- pg_solid::functions::aggregates::SolidAggUnion
CREATE TYPE SolidAggUnion;

-- extensions/pg_solid/src/functions/aggregates.rs:12
-- pg_solid::functions::aggregates::solidaggunion_in
CREATE  FUNCTION "solidaggunion_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS SolidAggUnion /* core::option::Option<pg_solid::functions::aggregates::SolidAggUnion> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solidaggunion_in_wrapper';

-- extensions/pg_solid/src/functions/aggregates.rs:12
-- pg_solid::functions::aggregates::solidaggunion_out
CREATE  FUNCTION "solidaggunion_out"(
	"input" SolidAggUnion /* pg_solid::functions::aggregates::SolidAggUnion */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solidaggunion_out_wrapper';

-- extensions/pg_solid/src/functions/aggregates.rs:12
-- pg_solid::functions::aggregates::solidaggunion_recv
CREATE  FUNCTION "solidaggunion_recv"(
	"internal" internal /* pgrx::datum::internal::Internal */
) RETURNS SolidAggUnion /* pg_solid::functions::aggregates::SolidAggUnion */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solidaggunion_recv_wrapper';

-- extensions/pg_solid/src/functions/aggregates.rs:12
-- pg_solid::functions::aggregates::solidaggunion_send
CREATE  FUNCTION "solidaggunion_send"(
	"input" SolidAggUnion /* pg_solid::functions::aggregates::SolidAggUnion */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solidaggunion_send_wrapper';


-- extensions/pg_solid/src/functions/aggregates.rs:12
-- pg_solid::functions::aggregates::SolidAggUnion
CREATE TYPE SolidAggUnion (
	INTERNALLENGTH = variable,
	INPUT = solidaggunion_in, /* pg_solid::functions::aggregates::solidaggunion_in */
	OUTPUT = solidaggunion_out, /* pg_solid::functions::aggregates::solidaggunion_out */
	RECEIVE = solidaggunion_recv, /* pg_solid::functions::aggregates::solidaggunion_recv */
	SEND = solidaggunion_send, /* pg_solid::functions::aggregates::solidaggunion_send */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/types/vec3d.rs:5
-- pg_solid::types::vec3d::Vec3D
CREATE TYPE Vec3D;

-- extensions/pg_solid/src/types/vec3d.rs:5
-- pg_solid::types::vec3d::vec3d_in
CREATE  FUNCTION "vec3d_in"(
	"input" cstring /* core::option::Option<&core::ffi::c_str::CStr> */
) RETURNS Vec3D /* core::option::Option<pg_solid::types::vec3d::Vec3D> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'vec3d_in_wrapper';

-- extensions/pg_solid/src/types/vec3d.rs:5
-- pg_solid::types::vec3d::vec3d_out
CREATE  FUNCTION "vec3d_out"(
	"input" Vec3D /* pg_solid::types::vec3d::Vec3D */
) RETURNS cstring /* alloc::ffi::c_str::CString */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'vec3d_out_wrapper';

-- extensions/pg_solid/src/types/vec3d.rs:5
-- pg_solid::types::vec3d::Vec3D
CREATE TYPE Vec3D (
	INTERNALLENGTH = variable,
	INPUT = vec3d_in, /* pg_solid::types::vec3d::vec3d_in */
	OUTPUT = vec3d_out, /* pg_solid::types::vec3d::vec3d_out */
	STORAGE = extended
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/operators.rs:7
-- pg_solid::functions::operators::bbox3d_overlaps
CREATE  FUNCTION "bbox3d_overlaps"(
	"a" BBox3D, /* pg_solid::types::bbox3d::BBox3D */
	"b" BBox3D /* pg_solid::types::bbox3d::BBox3D */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bbox3d_overlaps_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/ifc.rs:11
-- pg_solid::functions::ifc::ifc_elements
CREATE  FUNCTION "ifc_elements"(
	"filepath" TEXT /* &str */
) RETURNS TABLE (
	"global_id" TEXT,  /* alloc::string::String */
	"ifc_type" TEXT,  /* alloc::string::String */
	"name" TEXT,  /* core::option::Option<alloc::string::String> */
	"material" TEXT,  /* core::option::Option<alloc::string::String> */
	"storey" TEXT,  /* core::option::Option<alloc::string::String> */
	"solid" Solid,  /* core::option::Option<pg_solid::types::solid::Solid> */
	"properties" jsonb  /* core::option::Option<pgrx::datum::json::JsonB> */
)
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ifc_elements_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/ifc.rs:209
-- pg_solid::functions::ifc::ifc_map_conversion
CREATE  FUNCTION "ifc_map_conversion"(
	"filepath" TEXT /* &str */
) RETURNS TABLE (
	"eastings" double precision,  /* f64 */
	"northings" double precision,  /* f64 */
	"orthogonal_height" double precision,  /* f64 */
	"rotation_deg" double precision,  /* f64 */
	"scale" double precision,  /* f64 */
	"source_crs" TEXT,  /* core::option::Option<alloc::string::String> */
	"target_crs" TEXT  /* core::option::Option<alloc::string::String> */
)
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ifc_map_conversion_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/ifc.rs:82
-- pg_solid::functions::ifc::ifc_relationships
CREATE  FUNCTION "ifc_relationships"(
	"filepath" TEXT /* &str */
) RETURNS TABLE (
	"source_id" TEXT,  /* alloc::string::String */
	"target_id" TEXT,  /* alloc::string::String */
	"rel_type" TEXT,  /* alloc::string::String */
	"ordinal" INT,  /* core::option::Option<i32> */
	"properties" jsonb  /* core::option::Option<pgrx::datum::json::JsonB> */
)
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ifc_relationships_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/ifc.rs:178
-- pg_solid::functions::ifc::ifc_site_location
CREATE  FUNCTION "ifc_site_location"(
	"filepath" TEXT /* &str */
) RETURNS TABLE (
	"global_id" TEXT,  /* alloc::string::String */
	"name" TEXT,  /* core::option::Option<alloc::string::String> */
	"lat" double precision,  /* core::option::Option<f64> */
	"lon" double precision,  /* core::option::Option<f64> */
	"elevation" double precision  /* core::option::Option<f64> */
)
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ifc_site_location_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/ifc.rs:124
-- pg_solid::functions::ifc::ifc_spatial_structure
CREATE  FUNCTION "ifc_spatial_structure"(
	"filepath" TEXT /* &str */
) RETURNS TABLE (
	"global_id" TEXT,  /* alloc::string::String */
	"ifc_type" TEXT,  /* alloc::string::String */
	"name" TEXT,  /* core::option::Option<alloc::string::String> */
	"parent_global_id" TEXT,  /* core::option::Option<alloc::string::String> */
	"elevation" double precision  /* core::option::Option<f64> */
)
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ifc_spatial_structure_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/ifc.rs:252
-- pg_solid::functions::ifc::ifc_true_north
CREATE  FUNCTION "ifc_true_north"(
	"filepath" TEXT /* &str */
) RETURNS TABLE (
	"north_x" double precision,  /* f64 */
	"north_y" double precision,  /* f64 */
	"rotation_deg" double precision  /* f64 */
)
IMMUTABLE STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ifc_true_north_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/aggregates.rs:74
-- pg_solid::functions::aggregates::solid_agg_bbox_solid_agg_bbox_finalize
CREATE  FUNCTION "solid_agg_bbox_solid_agg_bbox_finalize"(
	"this" internal /* pgrx::datum::internal::Internal */
) RETURNS BBox3D /* pg_solid::types::bbox3d::BBox3D */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_agg_bbox_solid_agg_bbox_finalize_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/aggregates.rs:74
-- pg_solid::functions::aggregates::solid_agg_bbox_solid_agg_bbox_state
CREATE  FUNCTION "solid_agg_bbox_solid_agg_bbox_state"(
	"this" internal, /* pgrx::datum::internal::Internal */
	"value" Solid /* pg_solid::types::solid::Solid */
) RETURNS internal /* pgrx::datum::internal::Internal */
IMMUTABLE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_agg_bbox_solid_agg_bbox_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/aggregates.rs:20
-- pg_solid::functions::aggregates::solid_agg_union_solid_agg_union_finalize
CREATE  FUNCTION "solid_agg_union_solid_agg_union_finalize"(
	"this" internal /* pgrx::datum::internal::Internal */
) RETURNS Solid /* pg_solid::types::solid::Solid */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_agg_union_solid_agg_union_finalize_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/aggregates.rs:20
-- pg_solid::functions::aggregates::solid_agg_union_solid_agg_union_state
CREATE  FUNCTION "solid_agg_union_solid_agg_union_state"(
	"this" internal, /* pgrx::datum::internal::Internal */
	"value" Solid /* pg_solid::types::solid::Solid */
) RETURNS internal /* pgrx::datum::internal::Internal */
IMMUTABLE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_agg_union_solid_agg_union_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/measurements.rs:22
-- pg_solid::functions::measurements::solid_bbox
CREATE  FUNCTION "solid_bbox"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS BBox3D /* pg_solid::types::bbox3d::BBox3D */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_bbox_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/operators.rs:19
-- pg_solid::functions::operators::solid_bbox_distance
CREATE  FUNCTION "solid_bbox_distance"(
	"a" Solid, /* pg_solid::types::solid::Solid */
	"b" Solid /* pg_solid::types::solid::Solid */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_bbox_distance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:277
-- pg_solid::functions::export::solid_bbox_wkt
CREATE  FUNCTION "solid_bbox_wkt"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_bbox_wkt_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/constructors.rs:21
-- pg_solid::functions::constructors::solid_box
CREATE  FUNCTION "solid_box"(
	"dx" double precision, /* f64 */
	"dy" double precision, /* f64 */
	"dz" double precision /* f64 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_box_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/measurements.rs:28
-- pg_solid::functions::measurements::solid_centroid
CREATE  FUNCTION "solid_centroid"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS Point3D /* pg_solid::types::point3d::Point3D */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_centroid_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/measurements.rs:94
-- pg_solid::functions::measurements::solid_check
CREATE  FUNCTION "solid_check"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_check_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/constructors.rs:51
-- pg_solid::functions::constructors::solid_cone
CREATE  FUNCTION "solid_cone"(
	"r1" double precision, /* f64 */
	"r2" double precision, /* f64 */
	"height" double precision /* f64 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_cone_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/predicates.rs:70
-- pg_solid::functions::predicates::solid_contains
CREATE  FUNCTION "solid_contains"(
	"a" Solid, /* pg_solid::types::solid::Solid */
	"b" Solid /* pg_solid::types::solid::Solid */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_contains_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/predicates.rs:40
-- pg_solid::functions::predicates::solid_contains_point
CREATE  FUNCTION "solid_contains_point"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"pt" Point3D /* pg_solid::types::point3d::Point3D */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_contains_point_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/constructors.rs:31
-- pg_solid::functions::constructors::solid_cylinder
CREATE  FUNCTION "solid_cylinder"(
	"radius" double precision, /* f64 */
	"height" double precision /* f64 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_cylinder_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/boolean.rs:21
-- pg_solid::functions::boolean::solid_difference
CREATE  FUNCTION "solid_difference"(
	"a" Solid, /* pg_solid::types::solid::Solid */
	"b" Solid /* pg_solid::types::solid::Solid */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_difference_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/measurements.rs:84
-- pg_solid::functions::measurements::solid_dimensions
CREATE  FUNCTION "solid_dimensions"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS Vec3D /* pg_solid::types::vec3d::Vec3D */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_dimensions_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/predicates.rs:8
-- pg_solid::functions::predicates::solid_distance
CREATE  FUNCTION "solid_distance"(
	"a" Solid, /* pg_solid::types::solid::Solid */
	"b" Solid /* pg_solid::types::solid::Solid */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_distance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/explode.rs:10
-- pg_solid::functions::explode::solid_explode
CREATE  FUNCTION "solid_explode"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS SETOF Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_explode_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:208
-- pg_solid::functions::export::solid_export_glb
CREATE  FUNCTION "solid_export_glb"(
	"s" Solid, /* core::option::Option<pg_solid::types::solid::Solid> */
	"filepath" TEXT, /* &str */
	"linear_deflection" double precision DEFAULT 0.1, /* f64 */
	"angular_deflection" double precision DEFAULT 0.5, /* f64 */
	"target_srid" INT DEFAULT 4326, /* i32 */
	"georef_path" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_export_glb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:188
-- pg_solid::functions::export::solid_export_obj
CREATE  FUNCTION "solid_export_obj"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"filepath" TEXT, /* &str */
	"linear_deflection" double precision DEFAULT 0.1, /* f64 */
	"angular_deflection" double precision DEFAULT 0.5 /* f64 */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_export_obj_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:240
-- pg_solid::functions::export::solid_export_usda
CREATE  FUNCTION "solid_export_usda"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"filepath" TEXT, /* &str */
	"linear_deflection" double precision DEFAULT 0.1, /* f64 */
	"angular_deflection" double precision DEFAULT 0.5 /* f64 */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_export_usda_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/measurements.rs:40
-- pg_solid::functions::measurements::solid_face_count
CREATE  FUNCTION "solid_face_count"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_face_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:262
-- pg_solid::functions::export::solid_footprint_wkt
CREATE  FUNCTION "solid_footprint_wkt"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_footprint_wkt_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/constructors.rs:6
-- pg_solid::functions::constructors::solid_from_brep
CREATE  FUNCTION "solid_from_brep"(
	"brep_bytes" bytea /* &[u8] */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_from_brep_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/boolean.rs:111
-- pg_solid::functions::boolean::solid_from_ifc_extrusion
CREATE  FUNCTION "solid_from_ifc_extrusion"(
	"width" double precision, /* f64 */
	"height" double precision, /* f64 */
	"dx" double precision, /* f64 */
	"dy" double precision, /* f64 */
	"dz" double precision /* f64 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_from_ifc_extrusion_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:180
-- pg_solid::functions::export::solid_from_ifc_file
CREATE  FUNCTION "solid_from_ifc_file"(
	"filepath" TEXT /* &str */
) RETURNS Solid /* pg_solid::types::solid::Solid */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_from_ifc_file_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/constructors.rs:73
-- pg_solid::functions::constructors::solid_from_iges
CREATE  FUNCTION "solid_from_iges"(
	"iges_bytes" bytea /* &[u8] */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_from_iges_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/constructors.rs:95
-- pg_solid::functions::constructors::solid_from_iges_file
CREATE  FUNCTION "solid_from_iges_file"(
	"filepath" TEXT /* &str */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_from_iges_file_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/constructors.rs:62
-- pg_solid::functions::constructors::solid_from_step
CREATE  FUNCTION "solid_from_step"(
	"step_bytes" bytea /* &[u8] */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_from_step_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/constructors.rs:84
-- pg_solid::functions::constructors::solid_from_step_file
CREATE  FUNCTION "solid_from_step_file"(
	"filepath" TEXT /* &str */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_from_step_file_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/ifc.rs:288
-- pg_solid::functions::ifc::solid_georeference
CREATE  FUNCTION "solid_georeference"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"filepath" TEXT, /* &str */
	"target_srid" INT DEFAULT 4326 /* i32 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_georeference_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/transforms.rs:61
-- pg_solid::functions::transforms::solid_georeference_lonlat
CREATE  FUNCTION "solid_georeference_lonlat"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"lat" double precision, /* f64 */
	"lon" double precision, /* f64 */
	"elevation" double precision, /* f64 */
	"rotation_deg" double precision DEFAULT 0.0, /* f64 */
	"scale" double precision DEFAULT 1.0, /* f64 */
	"target_srid" INT DEFAULT 4326 /* i32 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_georeference_lonlat_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/gist.rs:65
-- pg_solid::gist::solid_gist_compress
CREATE  FUNCTION "solid_gist_compress"(
	"entry" internal /* pgrx::datum::internal::Internal */
) RETURNS internal /* pgrx::datum::internal::Internal */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_gist_compress_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/gist.rs:13
-- pg_solid::gist::solid_gist_consistent
CREATE  FUNCTION "solid_gist_consistent"(
	"entry" internal, /* pgrx::datum::internal::Internal */
	"query" Solid, /* pg_solid::types::solid::Solid */
	"strategy" smallint, /* i16 */
	"_subtype" oid, /* pgrx_pg_sys::submodules::oids::Oid */
	"recheck" internal /* pgrx::datum::internal::Internal */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_gist_consistent_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/gist.rs:99
-- pg_solid::gist::solid_gist_decompress
CREATE  FUNCTION "solid_gist_decompress"(
	"entry" internal /* pgrx::datum::internal::Internal */
) RETURNS internal /* pgrx::datum::internal::Internal */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_gist_decompress_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/gist.rs:246
-- pg_solid::gist::solid_gist_distance
CREATE  FUNCTION "solid_gist_distance"(
	"entry" internal, /* pgrx::datum::internal::Internal */
	"query" Solid, /* pg_solid::types::solid::Solid */
	"strategy" smallint, /* i16 */
	"_subtype" oid, /* pgrx_pg_sys::submodules::oids::Oid */
	"recheck" internal /* pgrx::datum::internal::Internal */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_gist_distance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/gist.rs:105
-- pg_solid::gist::solid_gist_penalty
CREATE  FUNCTION "solid_gist_penalty"(
	"orig" internal, /* pgrx::datum::internal::Internal */
	"new_entry" internal, /* pgrx::datum::internal::Internal */
	"penalty" internal /* pgrx::datum::internal::Internal */
) RETURNS internal /* pgrx::datum::internal::Internal */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_gist_penalty_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/gist.rs:126
-- pg_solid::gist::solid_gist_picksplit
CREATE  FUNCTION "solid_gist_picksplit"(
	"entry_vec" internal, /* pgrx::datum::internal::Internal */
	"split_vec" internal /* pgrx::datum::internal::Internal */
) RETURNS internal /* pgrx::datum::internal::Internal */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_gist_picksplit_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/gist.rs:236
-- pg_solid::gist::solid_gist_same
CREATE  FUNCTION "solid_gist_same"(
	"a" BBox3D, /* pg_solid::types::bbox3d::BBox3D */
	"b" BBox3D, /* pg_solid::types::bbox3d::BBox3D */
	"result" internal /* pgrx::datum::internal::Internal */
) RETURNS internal /* pgrx::datum::internal::Internal */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_gist_same_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/gist.rs:40
-- pg_solid::gist::solid_gist_union
CREATE  FUNCTION "solid_gist_union"(
	"entry_vec" internal, /* pgrx::datum::internal::Internal */
	"size" internal /* pgrx::datum::internal::Internal */
) RETURNS BBox3D /* pg_solid::types::bbox3d::BBox3D */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_gist_union_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/boolean.rs:49
-- pg_solid::functions::boolean::solid_heal
CREATE  FUNCTION "solid_heal"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_heal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/predicates.rs:137
-- pg_solid::functions::predicates::solid_hosts
CREATE  FUNCTION "solid_hosts"(
	"host" Solid, /* pg_solid::types::solid::Solid */
	"guest" Solid /* pg_solid::types::solid::Solid */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_hosts_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/boolean.rs:35
-- pg_solid::functions::boolean::solid_intersection
CREATE  FUNCTION "solid_intersection"(
	"a" Solid, /* pg_solid::types::solid::Solid */
	"b" Solid /* pg_solid::types::solid::Solid */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_intersection_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/predicates.rs:21
-- pg_solid::functions::predicates::solid_intersects
CREATE  FUNCTION "solid_intersects"(
	"a" Solid, /* pg_solid::types::solid::Solid */
	"b" Solid /* pg_solid::types::solid::Solid */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_intersects_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/measurements.rs:51
-- pg_solid::functions::measurements::solid_is_valid
CREATE  FUNCTION "solid_is_valid"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_is_valid_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/explode.rs:38
-- pg_solid::functions::explode::solid_num_solids
CREATE  FUNCTION "solid_num_solids"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS INT /* i32 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_num_solids_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/measurements.rs:63
-- pg_solid::functions::measurements::solid_obb
CREATE  FUNCTION "solid_obb"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS TEXT /* alloc::string::String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_obb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/measurements.rs:77
-- pg_solid::functions::measurements::solid_obb_volume
CREATE  FUNCTION "solid_obb_volume"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_obb_volume_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/boolean.rs:60
-- pg_solid::functions::boolean::solid_offset
CREATE  FUNCTION "solid_offset"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"distance" double precision /* f64 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_offset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/operators.rs:13
-- pg_solid::functions::operators::solid_overlaps
CREATE  FUNCTION "solid_overlaps"(
	"a" Solid, /* pg_solid::types::solid::Solid */
	"b" Solid /* pg_solid::types::solid::Solid */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_overlaps_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/operators.rs:24
-- requires:
--   BBox3D
--   Solid
--   bbox3d_overlaps
--   solid_overlaps
--   solid_bbox_distance


CREATE OPERATOR @extschema@.&& (
    LEFTARG = @extschema@.bbox3d,
    RIGHTARG = @extschema@.bbox3d,
    FUNCTION = @extschema@.bbox3d_overlaps,
    COMMUTATOR = &&,
    RESTRICT = areasel,
    JOIN = areajoinsel
);

CREATE OPERATOR @extschema@.&& (
    LEFTARG = @extschema@.solid,
    RIGHTARG = @extschema@.solid,
    FUNCTION = @extschema@.solid_overlaps,
    COMMUTATOR = &&,
    RESTRICT = areasel,
    JOIN = areajoinsel
);

CREATE OPERATOR @extschema@.<-> (
    LEFTARG = @extschema@.solid,
    RIGHTARG = @extschema@.solid,
    FUNCTION = @extschema@.solid_bbox_distance,
    COMMUTATOR = '<->'
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/gist.rs:280
-- requires:
--   overlap_operators
--   solid_gist_consistent
--   solid_gist_union
--   solid_gist_compress
--   solid_gist_decompress
--   solid_gist_penalty
--   solid_gist_picksplit
--   solid_gist_same
--   solid_gist_distance


CREATE OPERATOR CLASS @extschema@.solid_gist_ops
    DEFAULT FOR TYPE @extschema@.solid USING gist AS
    OPERATOR  3  @extschema@.&& (@extschema@.solid, @extschema@.solid),
    OPERATOR  15 @extschema@.<-> (@extschema@.solid, @extschema@.solid) FOR ORDER BY pg_catalog.float_ops,
    FUNCTION  1  @extschema@.solid_gist_consistent(internal, @extschema@.solid, int2, oid, internal),
    FUNCTION  2  @extschema@.solid_gist_union(internal, internal),
    FUNCTION  3  @extschema@.solid_gist_compress(internal),
    FUNCTION  4  @extschema@.solid_gist_decompress(internal),
    FUNCTION  5  @extschema@.solid_gist_penalty(internal, internal, internal),
    FUNCTION  6  @extschema@.solid_gist_picksplit(internal, internal),
    FUNCTION  7  @extschema@.solid_gist_same(@extschema@.bbox3d, @extschema@.bbox3d, internal),
    FUNCTION  8  @extschema@.solid_gist_distance(internal, @extschema@.solid, int2, oid, internal),
    STORAGE      @extschema@.bbox3d;
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/transforms.rs:18
-- pg_solid::functions::transforms::solid_rotate
CREATE  FUNCTION "solid_rotate"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"axis_x" double precision, /* f64 */
	"axis_y" double precision, /* f64 */
	"axis_z" double precision, /* f64 */
	"angle_deg" double precision /* f64 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_rotate_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/measurements.rs:107
-- pg_solid::functions::measurements::solid_shared_face_area
CREATE  FUNCTION "solid_shared_face_area"(
	"a" Solid, /* pg_solid::types::solid::Solid */
	"b" Solid /* pg_solid::types::solid::Solid */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_shared_face_area_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/boolean.rs:73
-- pg_solid::functions::boolean::solid_slice
CREATE  FUNCTION "solid_slice"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"ox" double precision DEFAULT 0.0, /* f64 */
	"oy" double precision DEFAULT 0.0, /* f64 */
	"oz" double precision DEFAULT 0.0, /* f64 */
	"nx" double precision DEFAULT 0.0, /* f64 */
	"ny" double precision DEFAULT 0.0, /* f64 */
	"nz" double precision DEFAULT 1.0 /* f64 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_slice_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/constructors.rs:41
-- pg_solid::functions::constructors::solid_sphere
CREATE  FUNCTION "solid_sphere"(
	"radius" double precision /* f64 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_sphere_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/measurements.rs:16
-- pg_solid::functions::measurements::solid_surface_area
CREATE  FUNCTION "solid_surface_area"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_surface_area_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/boolean.rs:94
-- pg_solid::functions::boolean::solid_to_2d
CREATE  FUNCTION "solid_to_2d"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"dx" double precision DEFAULT 0.0, /* f64 */
	"dy" double precision DEFAULT 0.0, /* f64 */
	"dz" double precision DEFAULT 1.0 /* f64 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_to_2d_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/constructors.rs:16
-- pg_solid::functions::constructors::solid_to_brep
CREATE  FUNCTION "solid_to_brep"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_to_brep_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:66
-- pg_solid::functions::export::solid_to_glb
CREATE  FUNCTION "solid_to_glb"(
	"s" Solid, /* core::option::Option<pg_solid::types::solid::Solid> */
	"linear_deflection" double precision DEFAULT 0.1, /* f64 */
	"angular_deflection" double precision DEFAULT 0.5, /* f64 */
	"target_srid" INT DEFAULT 4326, /* i32 */
	"georef_path" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_to_glb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:32
-- pg_solid::functions::export::solid_to_iges
CREATE  FUNCTION "solid_to_iges"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_to_iges_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:41
-- pg_solid::functions::export::solid_to_obj
CREATE  FUNCTION "solid_to_obj"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"linear_deflection" double precision DEFAULT 0.1, /* f64 */
	"angular_deflection" double precision DEFAULT 0.5 /* f64 */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_to_obj_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:23
-- pg_solid::functions::export::solid_to_step
CREATE  FUNCTION "solid_to_step"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_to_step_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:9
-- pg_solid::functions::export::solid_to_stl
CREATE  FUNCTION "solid_to_stl"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"linear_deflection" double precision DEFAULT 0.1, /* f64 */
	"angular_deflection" double precision DEFAULT 0.5 /* f64 */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_to_stl_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:164
-- pg_solid::functions::export::solid_to_usda
CREATE  FUNCTION "solid_to_usda"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"linear_deflection" double precision DEFAULT 0.1, /* f64 */
	"angular_deflection" double precision DEFAULT 0.5 /* f64 */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_to_usda_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/predicates.rs:105
-- pg_solid::functions::predicates::solid_touches
CREATE  FUNCTION "solid_touches"(
	"a" Solid, /* pg_solid::types::solid::Solid */
	"b" Solid /* pg_solid::types::solid::Solid */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_touches_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/transforms.rs:30
-- pg_solid::functions::transforms::solid_transform
CREATE  FUNCTION "solid_transform"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"matrix" double precision[] /* alloc::vec::Vec<f64> */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_transform_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/transforms.rs:7
-- pg_solid::functions::transforms::solid_translate
CREATE  FUNCTION "solid_translate"(
	"s" Solid, /* pg_solid::types::solid::Solid */
	"dx" double precision, /* f64 */
	"dy" double precision, /* f64 */
	"dz" double precision /* f64 */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_translate_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/boolean.rs:7
-- pg_solid::functions::boolean::solid_union
CREATE  FUNCTION "solid_union"(
	"a" Solid, /* pg_solid::types::solid::Solid */
	"b" Solid /* pg_solid::types::solid::Solid */
) RETURNS Solid /* pg_solid::types::solid::Solid */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_union_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/measurements.rs:10
-- pg_solid::functions::measurements::solid_volume
CREATE  FUNCTION "solid_volume"(
	"s" Solid /* pg_solid::types::solid::Solid */
) RETURNS double precision /* f64 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_volume_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/predicates.rs:55
-- pg_solid::functions::predicates::solid_within_clearance
CREATE  FUNCTION "solid_within_clearance"(
	"a" Solid, /* pg_solid::types::solid::Solid */
	"b" Solid, /* pg_solid::types::solid::Solid */
	"distance" double precision /* f64 */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solid_within_clearance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/export.rs:110
-- pg_solid::functions::export::solids_to_multi_glb
CREATE  FUNCTION "solids_to_multi_glb"(
	"solids" Solid[], /* core::option::Option<alloc::vec::Vec<core::option::Option<pg_solid::types::solid::Solid>>> */
	"names" TEXT[] DEFAULT NULL, /* core::option::Option<alloc::vec::Vec<core::option::Option<alloc::string::String>>> */
	"linear_deflection" double precision DEFAULT 0.1, /* f64 */
	"angular_deflection" double precision DEFAULT 0.5, /* f64 */
	"target_srid" INT DEFAULT 4326, /* i32 */
	"georef_path" TEXT DEFAULT NULL /* core::option::Option<&str> */
) RETURNS bytea /* alloc::vec::Vec<u8> */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'solids_to_multi_glb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/aggregates.rs:74
-- pg_solid::functions::aggregates::SolidAggBbox
CREATE AGGREGATE solid_agg_bbox (
	"value" Solid /* pg_solid::types::solid::Solid */
)
(
	SFUNC = "solid_agg_bbox_solid_agg_bbox_state", /* pg_solid::functions::aggregates::SolidAggBbox::state */
	STYPE = internal, /* pgrx::datum::internal::Internal */
	FINALFUNC = "solid_agg_bbox_solid_agg_bbox_finalize" /* pg_solid::functions::aggregates::SolidAggBbox::final */
);
/* </end connected objects> */

/* <begin connected objects> */
-- extensions/pg_solid/src/functions/aggregates.rs:20
-- pg_solid::functions::aggregates::SolidAggUnion
CREATE AGGREGATE solid_agg_union (
	"value" Solid /* pg_solid::types::solid::Solid */
)
(
	SFUNC = "solid_agg_union_solid_agg_union_state", /* pg_solid::functions::aggregates::SolidAggUnion::state */
	STYPE = internal, /* pgrx::datum::internal::Internal */
	FINALFUNC = "solid_agg_union_solid_agg_union_finalize" /* pg_solid::functions::aggregates::SolidAggUnion::final */
);
/* </end connected objects> */

